### ISSUE TITLE
Dragula expectations

### ISSUE THREAD

**Issue by NathanWalker** [valor-software/ng2-dragula#1]
This looks like a good representation of features this should have if not a direct port of it:
http://bevacqua.github.io/angular-dragula/

**Comment by valorkin** [comment]
Yes it is, all ng2 modules should have exactly the same external API, so guys can migrate to ng2 easily

**Comment by NathanWalker** [comment]
I'll be working on this over here:
https://github.com/NathanWalker/ng2-dragula

I don't have any ETA on it at moment, but will begin to work towards it when I can!

**Comment by valorkin** [comment]
Awesome, I don't have any ETA about dragula for now
But I suppose it should be simple enough :)

**Comment by NathanWalker** [comment]
This is complete here: https://github.com/valor-software/ng2-dragula/pull/2

:+1:
