### ISSUE TITLE
dragulaModel does not update model array when items are identical

### ISSUE THREAD

**Issue by thomasbee** [valor-software/ng2-dragula#105]
In a standard drag'n drop single bag where the items are indexed, i.e.

```
<div [dragula]='"bag"' [dragulaModel]="numbers">
    <div *ngFor="#n of numbers; #i = index">
            #{{i+1}} · {{n}} 
      </div>
</div>
```

if this is bound to an array with different items, say

```
numbers = [42, 43, 44, 45, 46]
```

Everything works fine when dragging and dropping. However, if the array contains duplicate entries, say 

```
numbers = [1, 2, 1, 1, 1, 1] 
```

than dragging and dropping will not truly reorder the model, so that the index i will eventually be in random order. Admittedly it might not make much sense to put order on identical items, but the index is ruined and that is an issue.

**Comment by cormacrelf** [comment]
Do not use identical items.
