### ISSUE TITLE
[bug report] Angular 15 Animations Dependency Bug

### ISSUE THREAD

**Issue by millerbill3** [valor-software/ng2-dragula#1081]
**REQUIRED: Before filing a bug report**

Change each `[ ]` to `[x]` when you have done it.

- [ x] My issue title starts with `[bug report]`
- [x ] I have read the [README](https://github.com/valor-software/ng2-dragula), especially the ['classic blunders' section](https://github.com/valor-software/ng2-dragula#classic-blunders), and the [dragula docs](https://github.com/bevacqua/dragula).
- [x ] I have searched through the [`ng2-dragula` issues](https://github.com/valor-software/ng2-dragula/issues) for related problems, including closed issues.
- [ x] I have browsed through the [issues labeled "future reference"](960570) for problems that have been solved before or have a known workaround.
- [ x] I am using the latest version of `ng2-dragula`.

**Describe the bug (required)**

Recently upgraded to Angular v15.0.4 and ng2-dragula v3.2.0 After updating I ran `npm install` and receive a dependency error related to @angular/animations

**To Reproduce (required)**

1. Upgrade to Angular 15 using Angular CLI
2. Change version of ng2-dragula to v3.2.0
3. run `npm install` to install listed versions of packages
4. Error:

> npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: ng2-dragula@3.2.0
npm ERR! Found: @angular/animations@15.0.4
npm ERR! node_modules/@angular/animations
npm ERR!   @angular/animations@"^15.0.4" from the root project
npm ERR!   peerOptional @angular/animations@"15.0.4" from @angular/platform-browser@15.0.4
npm ERR!   node_modules/@angular/platform-browser
npm ERR!     @angular/platform-browser@"^15.0.4" from the root project
npm ERR!     peer @angular/platform-browser@"15.0.4" from @angular/forms@15.0.4
npm ERR!     node_modules/@angular/forms
npm ERR!       @angular/forms@"^15.0.4" from the root project
npm ERR!       2 more (@ctrl/ngx-codemirror, @ng-bootstrap/ng-bootstrap)
npm ERR!     4 more (@angular/platform-browser-dynamic, @angular/router, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/animations@"^14.0.0" from ng2-dragula@3.2.0
npm ERR! node_modules/ng2-dragula
npm ERR!   ng2-dragula@"^3.2.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/animations@14.2.12
npm ERR! node_modules/@angular/animations
npm ERR!   peer @angular/animations@"^14.0.0" from ng2-dragula@3.2.0
npm ERR!   node_modules/ng2-dragula
npm ERR!     ng2-dragula@"^3.2.0" from the root project

Versions:
 - `@angular/core`: 15.0.4
 - `ng2-dragula`: 3.2.0

Is this issue being tracked or is there a current work around?

**Comment by iliakan** [comment]
Any plans to make this Angular 15 compatible?

**Comment by sokolovstas** [comment]
You can solve this by changing package.json
"overrides": {
    "ng2-dragula": {
      "@types/dragula": ">=2.1.34",
      "@angular/animations": ">=14.0.0",
      "@angular/core": ">=14.0.0",
      "@angular/common": ">=14.0.0"
    }
  }

**Comment by millerbill3** [comment]
> You can solve this by changing yours package.json
> 
> ```
> "overrides": {
>     "ng2-dragula": {
>       "@types/dragula": ">=2.1.34",
>       "@angular/animations": ">=14.0.0",
>       "@angular/core": ">=14.0.0",
>       "@angular/common": ">=14.0.0"
>     }
>   }
> ```

Yes, this is an option but it defeats the purpose which was to upgrade my application to the latest version of Angular (15).

**Comment by jarekkowol** [comment]
Any plans to make compatible? ;)

**Comment by SvetlanaMuravlova** [comment]
@jarekkowol , it will be fixed soon) thank you for issue)

**Comment by SvetlanaMuravlova** [comment]
@ghbob , yeas i saw it, today will be new version (@next) and it will be compatible with angular 15
