### ISSUE TITLE
[bug report] library is not compatible with Angular v16 

### ISSUE THREAD

**Issue by pawelofieldly** [valor-software/ng2-dragula#1089]
- [x] My issue title starts with `[bug report]`
- [x] I have read the [README](https://github.com/valor-software/ng2-dragula), especially the ['classic blunders' section](https://github.com/valor-software/ng2-dragula#classic-blunders), and the [dragula docs](https://github.com/bevacqua/dragula).
- [x] I have searched through the [`ng2-dragula` issues](https://github.com/valor-software/ng2-dragula/issues) for related problems, including closed issues.
- [x] I have browsed through the [issues labeled "future reference"](https://github.com/valor-software/ng2-dragula/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22future+reference%22) for problems that have been solved before or have a known workaround.
- [x] I am using the latest version of `ng2-dragula`.

Dragula is not compatible with Angular 16

There are two scenarios:

I. You want to install dragula in ng16 project
1. npm install --save ng2-dragula
4. See error: unable to resolve dependency tree

II. You want to migrate current project to ng16
1. use `ng update` to update ng15 to ng16
2. See error when **ng serve** has been run: `Error: node_modules/ng2-dragula/dist/components/dragula.module.d.ts:3:23 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s). static forRoot(): ModuleWithProviders;
`

**Comment by reda-alaoui** [comment]
I made it work without any issue.

**Comment by ohsk23** [comment]
Hi, I have a similar problem here.
ng2-dragula has dependency conflict with @angular/core@16.0.1
```sh
❯ npm i ng2-dragula@4.0.0                                                      took 5s
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: [PROJ_NAME]@1.16.10
npm ERR! Found: @angular/core@16.0.1
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"16.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"15.2.9" from @angular/animations@15.2.9
npm ERR! node_modules/@angular/animations
npm ERR!   peer @angular/animations@"^15.0.0" from ng2-dragula@4.0.0
npm ERR!   node_modules/ng2-dragula
npm ERR!     ng2-dragula@"4.0.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

```
Any updates for angular v16?

**Comment by mrkava** [comment]
Similar problem after update to Angular 16. Do you plan to support Angular 16?

**Comment by Petronio1982** [comment]
PS C:\Users\attim\Documents\virtualroom3d> npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: ng2-dragula@4.0.0
npm ERR! Found: @angular/animations@16.0.3
npm ERR! node_modules/@angular/animations
npm ERR!   @angular/animations@"^16.0.3" from the root project
npm ERR!   peer @angular/animations@"^16.0.0 || ^17.0.0" from @angular/material@16.0.2
npm ERR!   node_modules/@angular/material
npm ERR!     @angular/material@"^16.0.2" from the root project
npm ERR!     peer @angular/material@"16.0.2" from @angular/material-moment-adapter@16.0.2
npm ERR!     node_modules/@angular/material-moment-adapter
npm ERR!       @angular/material-moment-adapter@"^16.0.2" from the root project
npm ERR!   1 more (@angular/platform-browser)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/animations@"^15.0.0" from ng2-dragula@4.0.0
npm ERR! node_modules/ng2-dragula
npm ERR!   ng2-dragula@"^4.0.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/animations@15.2.9
npm ERR! node_modules/@angular/animations
npm ERR!   peer @angular/animations@"^15.0.0" from ng2-dragula@4.0.0
npm ERR!   node_modules/ng2-dragula
npm ERR!     ng2-dragula@"^4.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by onaluf** [comment]
I've got the same exact issue. If installed with `--force` everything works correctly so fixing this is probably as simple as updating the `package.json` to be a bit more flexible as to which version of angular it requires.

**Comment by pjc2007** [comment]
Would also like to use with Angular 16.

**Comment by pawelofieldly** [comment]
@reda-alaoui do you consider updating compatibility to ng16? I would like not to use `npm install --force`

**Comment by neodescis** [comment]
Why is this issue closed?

**Comment by ghbob** [comment]
@valorkin @SvetlanaMuravlova Could you kindly give us some information if there are plans to make this package support Angular 16? Thank you!
Someone prepared a PR as well: #1092
