### ISSUE TITLE
[feature request] Angular v17 support

### ISSUE THREAD

**Issue by alebx** [valor-software/ng2-dragula#1099]
Please add Angular v17 support.

**Comment by Malstrime** [comment]
As temporary solution, I've installed vanilla `dragula@3.7.2` package alongside with `ng2-dragula` (with `--legacy-peer-deps`).

<img width="244" alt="image" src="https://github.com/valor-software/ng2-dragula/assets/11160309/2e6a5624-bb8b-41fd-ae88-5965651c701b">

**Comment by alebx** [comment]
The alternative is to override the dependencies in your `package.json`, e.g.:
```json
"overrides": {
    "ng2-dragula": {
      "@angular/common": "$@angular/common",
      "@angular/core": "$@angular/core",
      "@angular/animations": "$@angular/animations"
    }
  }
```

**Comment by joeskeen** [comment]
Does the library work properly if you use `--legacy-peer-deps`? If so, is it just a tiny pull request to change the required Angular version?

**Comment by alebx** [comment]
Yes, the library still works with angular v17 when you do `--legacy-peer-deps` or `--force`.

**Comment by pawelofieldly** [comment]
Without this update, we are loosing version guards as we have to install all of the libraries with mentioned above flags

**Comment by neverlose-lv** [comment]
After installing in my Angular 17 project, I get build error:

```
ng serve
Node.js version v21.7.0 detected.
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/previous-releases/.
⠇ Building...
✘ [ERROR] TS2307: Cannot find module 'dragula' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/ng2-dragula/DragulaOptions.d.ts:1:50:
      1 │ import { DragulaOptions as OriginalOptions } from 'dragula';
        ╵                                                   ~~~~~~~~~


✘ [ERROR] TS2307: Cannot find module 'dragula' or its corresponding type declarations. [plugin angular-compiler]

    node_modules/ng2-dragula/DrakeWithModels.d.ts:1:22:
      1 │ import { Drake } from 'dragula';
        ╵                       ~~~~~~~~~


✘ [ERROR] TS7016: Could not find a declaration file for module 'dragula'. '/Users/apower/Desktop/important.day/important.day-frontend/node_modules/dragula/dragula.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/dragula` if it exists or add a new declaration (.d.ts) file containing `declare module 'dragula';` [plugin angular-compiler]

    node_modules/ng2-dragula/MockDrake.d.ts:5:22:
      5 │ import { Drake } from 'dragula';
```

**Comment by neverlose-lv** [comment]
As a temporary fix, I have installed these:

`npm i dragula --legacy-peer-deps`
`npm i --save-dev @types/dragula`

**Comment by neverlose-lv** [comment]
And now when I run ng serve. I get this runtime error:

<img width="944" alt="image" src="https://github.com/valor-software/ng2-dragula/assets/26433803/857edb59-0808-45d7-a792-3273d89abb9a">

**Comment by neverlose-lv** [comment]
I believe this is because I am using Angular Universal. And the server does not have the document object. I have not found a proper workaround for that.

**Comment by joeskeen** [comment]
@neverlose-lv I don't use Angular Universal but I'm wondering if there's some way that you can conditionally exclude the element using `dragula` when not in a browser (i.e. `*ngIf` or `@if(){}`? It may even require a dynamic `import()` too... but I'm not sure.
