### ISSUE TITLE
Drag into recycle bin

### ISSUE THREAD

**Issue by mburger81** [valor-software/ng2-dragula#112]
Hello,

is it possible to have some divs (widgets) which you can drag into an other div which is my recycle bin but blocking the drag and drop for change position of the widgets?

So for example I can drag 10 divs into 1 div, but the 10 divs can change position on there container.

I hope I explained it good enough.

thx
  Michael

**Comment by NathanWalker** [comment]
Would it be possible to provide a plunkr or demo project to see better what you are trying to do?

**Comment by mburger81** [comment]
Can you share a plunkr template or something else which I can fork the make an example?

**Comment by mburger81** [comment]
@NathanWalker 

Hello, here as a very stupid plnkr example which explains in angular2 without ng2-dragula what I would to do.

There are one div which is my recycle bin, then there are 2 Containers, and any container has got 3 widget divs.

What I need is, it should be able do drag and drop Container 1 and Container 2 each other, so I will change the postion of Container 1 and 2 in my page. That's clearly no problem with your lib.

But my problem is, I need the ability to DRAG Widget 1 to 6 over the RECYCLE BIN DIV, and if i'm over there and drop it i will remove the widget div, because I would delete it. But i don't wont to change the positions for widget 1 to 6, I only want to be able to "drag" my widget into the recyclebin div.

I need to reproduce a Android Dashboard onto my webapp. Doing this is not so easy because there are a lot of problems with bootsrap and so on, but one thing I need to do is the possibility to simulate a DRAG my widget with out change position into my recycle bin and delete it after.

Here my plnkr
http://plnkr.co/edit/MtBcfQJU3uXv6XRvypmT

Do you have some ideas?

thx
  Michael

**Comment by cormacrelf** [comment]
Use https://cormacrelf.github.io/angular-skyhook/ instead.
