### ISSUE TITLE
Dropping outside bag/target fails with copy: true

### ISSUE THREAD

**Issue by architruc** [valor-software/ng2-dragula#119]
Hi, it seems dropping outside a bag throws an error in `dragular.provider.ts#domIndexOf` method because the `parent` parameter there is undefined once I activate the [`copy`](https://github.com/bevacqua/dragula#optionscopy) option on the dragulaService. I worked around it by editing the `drop` event handler line 91:

Before:

```
if (!drake.models) {
  return;
}
```

After:

```
if (!drake.models || !target) {
  return;
}
```

But I am not sure it is the right fix.

Thanks for this library btw, it works great for the rest.

**Comment by architruc** [comment]
Oh, it also fails with `revertOnSpill` option (+ copy option), for another reason, and I have not found the link with ng2-dragular library.

`
EXCEPTION: TypeError: Cannot read property 'removeChild' of null
`

On dragula.js, cancel function, `parent.removeChild(_copy);` line.

**Comment by NathanWalker** [comment]
Thanks @architruc for this report. Your fix sounds reasonable. If you see any side effects, please let me know. If this fixes the issue for you, we might want to look at a PR for this.

**Comment by architruc** [comment]
Sure I will try as soon as I am pretty sure there is no side effect for my usecase.

Please be patient, I am new to PR and must debug other project bugs before ;)

For the revertOnSpill, any idea? Should I check on dragula side (instead of ng2-dragula)?

Thanks!

**Comment by architruc** [comment]
Hi, I haven't found any side effect on my use case, I have a working example of copy and a few other things. The PR has been submitted, hope I works well.
