### ISSUE TITLE
Example app fails with "TypeError: Cannot read property 'replace' of undefined"

### ISSUE THREAD

**Issue by carlgieringer** [valor-software/ng2-dragula#120]
Hi,

When I do a fresh checkout of ng2-dragula and try `npm start`, I get the following error:

```
> webpack-dev-server --inline --progress --port 3000

 70% 1/1 build modules/Users/tech/code/ng2-dragula/node_modules/webpack/lib/NormalModuleFactory.js:72
            var elements = request.replace(/^-?!+/, "").replace(/!!+/g, "!").split("!");
                                  ^

TypeError: Cannot read property 'replace' of undefined
    at /Users/tech/code/ng2-dragula/node_modules/webpack/lib/NormalModuleFactory.js:72:26
    at /Users/tech/code/ng2-dragula/node_modules/webpack/lib/NormalModuleFactory.js:28:4
    at /Users/tech/code/ng2-dragula/node_modules/webpack/lib/NormalModuleFactory.js:159:3
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/Users/tech/code/ng2-dragula/node_modules/tapable/lib/Tapable.js:75:69)
    at NormalModuleFactory.create (/Users/tech/code/ng2-dragula/node_modules/webpack/lib/NormalModuleFactory.js:144:8)
    at /Users/tech/code/ng2-dragula/node_modules/webpack/lib/Compilation.js:214:11
    at /Users/tech/code/ng2-dragula/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/Users/tech/code/ng2-dragula/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/Users/tech/code/ng2-dragula/node_modules/async/lib/async.js:209:22)
    at Compilation.addModuleDependencies (/Users/tech/code/ng2-dragula/node_modules/webpack/lib/Compilation.js:185:8)
```

I have attached the CLI output of the `git clone`, `npm install`, and `npm start`.  I have also attached the file `npm-debug.log`.  Thanks!

[cli-out.txt](https://github.com/valor-software/ng2-dragula/files/163281/cli-out.txt)
[npm-debug.log.txt](https://github.com/valor-software/ng2-dragula/files/163286/npm-debug.log.txt)

**Comment by NathanWalker** [comment]
The `webpack.config.js` was missing! Pull latest and try again. :+1:

**Comment by carlgieringer** [comment]
Thank you!

**Comment by nimatullah** [comment]
Hi, I have the same error, and I have webpack.config.json. what could be the error. please help

**Comment by Martin-Andersen** [comment]
I have the same error

**Comment by sandromaceno** [comment]
I have the same problem, has anyone managed to solve it? I already deleted the module and reinstalled the npm and nothing

**Comment by kaueburiti** [comment]
@Martin-Andersen @sandromaceno @nimatullah  try to check if you guys have a ` webpack.config.js` file (with exactly this name).

**Comment by nathanbiles** [comment]
@kaueburiti I am having this problem too AND I do have that file with the exact same name

**Comment by vagnerlucion** [comment]
@nathanbiles just had the same issue and my problem was that I wrote module.export instead module.exports in my webpack.config.js.

**Comment by real-yue** [comment]
The first answer helped me!! but  i am curious about why 

> The `webpack.config.js` was missing! Pull latest and try again. 👍

Its  helpful !!  thanks ! the  tips  are so confusing. why not just tips "do not find webpack.config.js"?

**Comment by real-yue** [comment]
> The `webpack.config.js` was missing! Pull latest and try again. 👍

Its helpful, thanks !! the tips is so confusing!  why not just give a tip like "we can not find the file named  webpack.config.js "
