### ISSUE TITLE
Failed to import with JSPM package manager

### ISSUE THREAD

**Issue by SergeyMell** [valor-software/ng2-dragula#123]
I was trying to inject ng2-dragula to Angular2 project ruled with JSPM package manager. But when I import it main boot.js file fails to compile... I've attached a part of my jspm.conf.js if it helps.

```
System.config({
  defaultJSExtensions: true,
  transpiler: false,
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },

  map: {
    "angular2": "npm:angular2@2.0.0-beta.6",
    "babel": "npm:babel-core@6.5.0",
    "babel-runtime": "npm:babel-runtime@6.5.0",
    "dragula": "npm:dragula@3.6.8",
    "jquery": "npm:jquery@2.2.1",
    "ng2-dragula": "npm:ng2-dragula@1.1.2",
    "normalize.css": "github:necolas/normalize.css@3.0.3",
    "rxjs": "npm:rxjs@5.0.0-beta.2",
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.6.0"
    },
...
```

**Comment by NathanWalker** [comment]
I unfortunately know nothing about `jspm`.

**Comment by SergeyMell** [comment]
JSPM is a package manager http://jspm.io/
Here I've created a public repository on the JSPM basis https://github.com/SergeyMell/angular2-test-project. Please, tell me how I can help

**Comment by SergeyMell** [comment]
Actually, I have the same issue with https://github.com/valor-software/ng2-file-upload
