### ISSUE TITLE
Cannot find module 'dragula'

### ISSUE THREAD

**Issue by SergeyMell** [valor-software/ng2-dragula#139]
I've added ng-2 dragula through webpack, but during project starting I get an error 
`Cannot find module 'dragula'`
Drag-n-drop works a bit weird (without any visual effects). Looks like dragula styles did not apply.

**Comment by rvetere** [comment]
I have the same error with my webpack setup - it comes from the import in the directive and the provider:

`import * as dragula from 'dragula';`

I can see the dragula package itself in my node_modules folder, but there is not "d.ts" file in there or anything else which would define the "dragula" module, what is leading to the error in my eyes..

Are some typings installs missing to get this running? Is t necessary to just fix it in our webpack project or does this need a fix in the ng-dragula package itself?

**Comment by rvetere** [comment]
Just found the fix - there is an ambient typings definition for 'dragula' :) If you're using typings for your webpack project setup, just go to your terminal and execute:

` typings install dragula --save --ambient`

After a restart, the "module not found" error must be gone ;)

**Comment by SergeyMell** [comment]
@rvetere That works! Thanks )
