### ISSUE TITLE
dragula is not a function

### ISSUE THREAD

**Issue by pallmallshow** [valor-software/ng2-dragula#145]
Hello guys,

I'm trying to insert ng2-dragula in my project but many problems appears.

So, I successfully import ng2-dragula by run : 

```terminal
npm install dragula ng2-dragula --save
```
I added in my index.html the original dragula lib : 
```html
<script src="node_modules/dragula/dist/dragula.min.js"></script>
```
And setup it in System.config : 
```javascript
System.config({
      packages: {
        app: {
          format: 'register',
          defaultExtension: 'js'
        },
        'dragula': {
          defaultExtension: 'js'
        },
        'ng2-dragula': {
          defaultExtension: 'js'
        }
    },
    map: {
        "dragula": 'node_modules/dragula/dist/dragula.js',
        'ng2-dragula' : 'node_modules/ng2-dragula',
    }
});
```

After this, I added in my component the directive and the service in `directives` and `viewProviders` array. (Like the README recommand).

At first, I've got the following error : 
```javascript
dragula is not a function in [....
```

After research, when we comment this line (in dragular.directives.ts) : 
```javascript
import * as dragula from 'dragula';
```

All work as expected, but if I keep it, I got the following : 
```javascript
dragula is not a function in
```

I don't use Webpack, did you got a idea for this problem ?

**Comment by olliholliday** [comment]
I have this same issue. Presumably I'm doing something daft but I'm not sure what.

**Comment by NathanWalker** [comment]
@pallmallshow @olliholliday Please see Wiki https://github.com/valor-software/ng2-dragula/wiki#angular2-seed on how to setup your SystemJS configuration. It's based off the angular2-seed which uses SystemJS so use it as a guide on how you need your configuration.

1 hint: You do **not** need to include:
```
<script src="node_modules/dragula/dist/dragula.min.js"></script>
```
on the page. Remove that and proceed with the wiki.

**Comment by olliholliday** [comment]
Thanks for such a quick response. Somehow I'd missed that, all working now.

**Comment by NathanWalker** [comment]
Great to hear @olliholliday thanks for letting me know!

@pallmallshow Are you still having issue or have you solved it with the above suggestions?

**Comment by pallmallshow** [comment]
Hi,

Thank for you purpose.
Finally, I choose to use angular2-seeder for a better project organization ;)

It works well with this seeder, but I never successfully used with a 'basic project'.
