### ISSUE TITLE
Remove .ts files from node package

### ISSUE THREAD

**Issue by ChristianBeilschmidt** [valor-software/ng2-dragula#148]
Hi,

you need to remove the .ts files from the node package. This means you are left with the Javascript files (.js) and the definition files (.d.ts). This is sufficient. Having the .ts files in the packages causes the typescript compiler to try to compile it, which causes a lot of trouble and is unnecessary.

In particular these files are: `ng2-dragula.ts`, `src\app\directives\dragula.directive.ts` and `src\app\providers\dragula.provider.ts`.

Best regards

**Comment by NathanWalker** [comment]
Thanks for this! For awhile I was on the side of the fence thinking some consumers may want the .ts files, but I think I've changed my mind. I'll try to change this shortly.

**Comment by NathanWalker** [comment]
@ChristianBeilschmidt I have published `1.1.4` now with this correction. Please let me know if this is better for you.

**Comment by ChristianBeilschmidt** [comment]
This works now as expected, thank you!
