### ISSUE TITLE
Instructions for Angular-CLI project?

### ISSUE THREAD

**Issue by cquillen2003** [valor-software/ng2-dragula#153]
Can someone please add instructions for getting ng2-dragula working in an Angular-CLI app?

I've tried multiple times and cannot get it working.  I posted an issue here about this previously but it was closed prematurely.

**Comment by NathanWalker** [comment]
I wish I knew. 
It uses system 'register' format out of the box. I've always had trouble with that.
Additionally, they create a `thirparty/libs.js` file for the npm install.

@jkuri - would you mind advising on what changes this lib needs to be compatible with angular-cli or what system.js config changes in the project cli generates are needed?

**Comment by cquillen2003** [comment]
@NathanWalker @jkuri gave me some advice and setup a sample repo in the following issue:

https://github.com/angular/angular-cli/issues/330

**Comment by jkuri** [comment]
I also created the sample repo for you @cquillen2003, not sure where is the problem.

**Comment by NathanWalker** [comment]
Thanks @jkuri !  

@cquillen2003 angular-cli will soon work very well with 3rd party libs thanks to the work @jkuri is doing so stay tuned.
As far as preferring manual installs vs using `ng install`... please note that `ng install` will always be purely optional and only meant as a powerful option to help speed up development when using many 3rd party libraries...that's the intent. angular-cli will be better with those libs in future. Glad you got it working.

**Comment by dioklecijan** [comment]
@cquillen2003 To setup ng2-dragula with angular-cli (1.0.0-beta.1) see my comment for the  #155 issue.

**Comment by imalhasaranga** [comment]
This is how you should do 

angular-cli-build.js

```
vendorNpmFiles: [
    'ng2-dragula/**/*.js',
    'dragula/dist/**/*.+(css|js|js.map)'
 ]
```

system-config.js

```
const map:any = {
    'ng2-dragula': 'vendor/ng2-dragula',
    'dragula' : 'vendor/dragula/dist/dragula.js'
};
```

```
const packages:any = {
    'ng2-dragula': {
        format: 'cjs',
        defaultExtension: 'js',
        main: 'ng2-dragula.js'
    }
};
```
