### ISSUE TITLE
Typescript compilation fails with module: system instead of commonjs

### ISSUE THREAD

**Issue by architruc** [valor-software/ng2-dragula#155]
The files `dragula.directive.ts` and `dragula.provider.ts` import the dragula library with a `require` instead of an `import`:

```typescript
var dragula = require('dragula');
```

This is tolerated if typescript compiles in commonjs, because the output is based on `require`, but it is not when compiling in `system` format. For multiple reasons, my project is compiled in the `system` format (`"module": "system"`).

-> Workaround I applied on my project:

- Replace `var dragula = require('dragula');` by `import dragula from 'dragula';`
- add the dragula typings to the project, and modify it to add the default export (to avoid errors):

```typescript
declare module "dragula" {
    export = dragula;
	export default dragula;
}
```

But it does not look like a clean fix. I don't know how to fix it cleanly. The idea is to keep the TypeScript syntax to allow the TS compiler to deal with it in all cases.

PS: I forgot the final error: `require` remains in the compiled version, and is undefined in the browser.

**Comment by architruc** [comment]
I just noticed that a commit 1 month ago introduced these `require`. I guess reverting this change would also be a way to solve, or at least work around the issue.

**Comment by architruc** [comment]
[Plunker here](http://plnkr.co/edit/xFZZoH0Hcr9iWuLt8AbG?p=preview). The plunker is not perfect, because even if the `require` error is solved, it will fail to load dragula for another reason (not found), but at least it allows to point the `require` error - same as my project (using JSPM to install dependencies).

**Comment by jayhamilton** [comment]
I believe I am seeing this problem as well. The dragula.directive.ts and dragula.provider.ts both include `import * as dragula from 'dragula' `but the import does not work. I added 
`/// <reference path="../../../node_modules/dragula/dist/dragula.min.js" />` but that did not help.

**Comment by architruc** [comment]
@jayhamilton `import * as dragula from 'dragula'` as a replacement for `var dragula = require('dragula');` didn't work for me for unknown reason, so I applied the previously described workaround (with default export). Your solution would be a better fix if it worked.

As far as I know, the `/// <reference ...` is only to avoid compilation warnings (displayed as error, but non-blocking). It won't fix anything in the output.

**Comment by kevinaditya** [comment]
hey @architruc, I have the same issue, after trying so many solutions now im a bit loss. where do you replace this? Replace var dragula = require('dragula'); by import dragula from 'dragula';

**Comment by architruc** [comment]
@kevinaditya Well... The version I was using seems not to be the latest. The one I got from npm at this moment was still using `require()`. `src/app/directives/dragula.directive.ts` and `src/app/providers/dragula.provider.ts` both import dragula on top of the file. So I edited these files, replaced with what you quoted, and edited the dragula typing to declare a default export (the default export seemed to be valid at runtime, but was detected as error by TypeScript compilation).

But the latest version on github already replaced by a regular TS import (update 15 days ago). I just tested to install the latest through jspm and it worked out of the box. The fix I asked was already there :D

I close the issue since the latest version seems OK.

**Comment by benwmaddox** [comment]
I hoped to get this change through NPM.  I apologize for mentioning something in a closed ticket.  How much effort would be required to update NPM with this change?

**Comment by architruc** [comment]
Oh I got the point, the fix is there but not published yet, jspm is actually using the compiled JS version, and takes care of the difference of format (it can read commonjs compiled module even if we use System format in the main code).

Let's reopen the issue until we get a confirmation from the contributors about publishing the changes.

**Comment by petervojtek** [comment]
maybe this helps someone -- this is how I managed to load dragula into Ionic 2 (Typescript):

```
import {Dragula, DragulaService} from "../../../node_modules/ng2-dragula/ng2-dragula"

@Page({ 
  templateUrl: 'path/to/html',
  directives: [Dragula],
  providers: [DragulaService]
})
```

**Comment by saimon24** [comment]
@petervojtek with Ionic 2 + TS I get this error:
ng2-dragula/src/app/directives/dragula.directive.d.ts(1,61): Error TS2307: Cannot find module '@angular/core'.
g2-dragula/src/app/providers/dragula.provider.d.ts(1,30): Error TS2307: Cannot find module '@angular/core'.

Any ideas? Anything special you did for the installation?

**Comment by petervojtek** [comment]
@saimon24 , I use ng2-dragula v1.1.6, while you seem to use latest code which is different.
e.g.  in  v1.1.6 there is `import .. 'angular/core'` instead of `import .. '@angular/core'`.

I use ng2-dragula v1.1.6 with angular 2.0.0-beta.15. Maybe latest ng2-dragula release is supposed to work with some later angular version (they already have rc1).

**Comment by dmackerman** [comment]
Running into issues as well with SystemJS, using the Angular CLI. It appears that all of the paths are correct, but for whatever reason I'm getting 404s on `src/app/directives/dragula.directive`, here's the code.

I've added the entries to my `angular-cli-build.js`, which copies it over to `dist/vendor`:

```js
module.exports = function(defaults) {
    return new Angular2App(defaults, {
        vendorNpmFiles: [
            // ...
            'dragula/dist/dragula.js',
            'ng2-dragula/**/*'
        ]
    });
};
```

```js
// works fine, the path can be resolved.
import { Dragula, DragulaService } from 'ng2-dragula/ng2-dragula';`
```

In my `system-config` `map` configuration.

```js
'ng2-dragula/ng2-dragula': 'vendor/ng2-dragula/ng2-dragula.js',
'dragula': 'vendor/dist/dragula.js'
```

So all appears well, but when System tries to load the files I get this:
![error](https://dl.dropboxusercontent.com/spa/g3yi8y5rd7pc3li/r3lxp9zu.png)

Which is strange, because the files are there. 
![error](https://dl.dropboxusercontent.com/spa/g3yi8y5rd7pc3li/2wwvxd6f.png)

The compiled source for `ng2-dragula.js`:

```js
"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
var dragula_directive_1 = require('./src/app/directives/dragula.directive');
var dragula_provider_1 = require('./src/app/providers/dragula.provider');
__export(require('./src/app/directives/dragula.directive'));
__export(require('./src/app/providers/dragula.provider'));
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = {
    directives: [dragula_directive_1.Dragula],
    providers: [dragula_provider_1.DragulaService]
};
```

To me it has to be something with the paths for those imports, but I'm not familiar enough with SystemJS to figure it out. 😢

**Comment by valorkin** [comment]
ok I got it, system.js bundles is needed :)
follow this issue https://github.com/valor-software/ng2-dragula/issues/230

**Comment by dioklecijan** [comment]
@dmackerman - Try following

**in system-config.ts**

```
const map: any = {
  'dragula': 'vendor/dragula/dist/dragula.js',
  'ng2-dragula': 'vendor/ng2-dragula'
};
```

```
const packages: any = {
//other entries
  'ng2-dragula': { format: 'cjs', defaultExtension: 'js', main: 'ng2-dragula' }
};
```

**in angular-cli.build.js**
```
    vendorNpmFiles: [
    //other entries
      'dragula/dist/dragula.js',
      'ng2-dragula/**/*.js'
    ]
```

**Comment by NejcZdovc** [comment]
@dioklecijan One optimization that you can do is to set **angular-cli.build.js** like this:
```
vendorNpmFiles: [
    //other entries
    'dragula/dist/dragula.js',
    'ng2-dragula/ng2-dragula.js',
    'ng2-dragula/src/**/*.js'
]
```

This way node_modules and other things from ng2-dragula directory, that are not needed, are not included in dist/vendor.
