### ISSUE TITLE
Issue with dragulaModel : modifying an item when dropping

### ISSUE THREAD

**Issue by RLRoux** [valor-software/ng2-dragula#156]
Hey! thanks for the Angular2 plugin. 
I face a problem when I try to override the way items are dropping between to bags in which data have different structures.

```
<div [dragula]='"slides-bag"' [(dragulaModel)]='slides'>
    <div class="slide" *ngFor="#s of slides; #idx=index">
        <div class="slidefields" [dragula]='"fields-bag"' [dragulaModel]='s.items'>
            <div class="field" *ngFor="#f of s.items; #idxs=index">
                ...
            </div>
        </div>
    </div>
</div>

<div [dragula]="'fields-bag'" [dragulaModel]='mobileFields'>
    <div class="mobilefield" *ngFor="#m of mobileFields">
</div>
```

When I drag an element from 'mobileFields' and drop it in 'slidesfields', I want to transform the mobilefield into slidefield. 
For the moment, the only solution I founded is the following :
- when the dropModel event is raised, finding the element that was inserted (what is not so easy because the dropModel event doesn't return the object that was inserted, only the html element)
- and then modify its attributes

Is there a better way to de that ? The best for me would be to acted before the models are updated.

Thanks in advance !

**Comment by ghaiat** [comment]
+1

**Comment by Bottle** [comment]
I'd also be interested if there is a better way. I ended up having to convert my source model to the target model. Which is a bit of a hack and not helpful if you need to drag to different target models from the same source. 

Thanks

**Comment by cormacrelf** [comment]
It’s easy to get items in v2. Release soon.
