### ISSUE TITLE
Drag and Drop between lists

### ISSUE THREAD

**Issue by anikets43** [valor-software/ng2-dragula#161]
Is it possible to one way drag and drop from one list to another using ng2-dragula

**Comment by 1greenapplee** [comment]
I used angular 1.5.5, and works smoothly.
update this list, works.
        dragula([$('left-defaults'), $('right-defaults'), $('right-drop2'), $('right-drop3')]);
where right-drop2', and right-drop3, are two new containers. :)

**Comment by valorkin** [comment]
it should be
