### ISSUE TITLE
Support encapsulation: ViewEncapsulation.Native (Shadow DOM)

### ISSUE THREAD

**Issue by architruc** [valor-software/ng2-dragula#178]
I don't know whether that's really possible, or if there is a link with [this issue to support iframes](https://github.com/bevacqua/dragula/issues/291) (my knowledge around Shadow DOM are limited), but when I apply the native View encapsulation (wraps the component in a Shadow root), not only the project styles are not applied, but also the **Dragula directive seems to have no effect**: elements cannot be dragged and the dropzone is not active to drop something coming from another area (outside Shadow root) of same bag name. But Angular 2 components/directives are still working, since I have components dynamically loaded inside the shadow DOM.

Any idea about this and what could be supported?

I believe Shadow DOM could be a good alternative to iframes for a dropzone with a different set of styles applied.

Thanks!

**Comment by NathanWalker** [comment]
`Native` shadow dom support is not planned at the moment, but maybe in the future when more browsers support it 'natively'. This is more related to how `dragula` interacts with it's styles actually.

Closing for now and will revisit in the future.

**Comment by aloksharma1** [comment]
Any Update On This? , its 2019 now :)
