### ISSUE TITLE
Drag/drop between multiple Angular2 components

### ISSUE THREAD

**Issue by marcoklemm** [valor-software/ng2-dragula#187]
Hi, is it possible to drag&drop between two component instances?

I have the same problem as described here:
How to drag/drop to multiple Angular2 component using ng2-dragula
http://stackoverflow.com/questions/35981273/how-to-drag-drop-to-multiple-angular2-component-using-ng2-dragula

Quote:

I have a Angular2 component using ng2-dragula to drag/drop like this:

@Component({
  selector: 'my-comp',
  directives: [
    Dragula
  ],
  viewProviders: [
    DragulaService
  ],
  template: `
    <div class="my-div">
      <div *ngFor="#item of items" [dragula]='"card-bag"' [dragulaModel]='items'>
      ...
      </div>
    </div>
`
})

My issue: if I create multiple "my-comp" component, item inside "card-bag" can not drag/drop across these component although they have the same bag name. These item are only able to drag/drop inside it owned component.

Do we have any configs for drag/drop across components, or this is ng2-dragula limitation?

Thanks.

**Comment by Smileo** [comment]
Hello all, I have same question.

**Comment by activeperception** [comment]
I have the same issue with the further complication that my components can be nested. Basically I would like a treeview with any node dragulable before/after/under any other node.

I found this example with dragula http://codepen.io/trzmaxim/pen/GppXGE but doesn't directly translate to angular2 whilst keeping models in sync.

**Comment by olliholliday** [comment]
Hi,

The only snag I hit when creating nested components was that I'd defined DragulaService as a provider in each component - which in angular2 scoping rules means that each component creates a new individual DragulaService.

If this is the same issue that you are having, the fix is to declare DragulaService *only* in your root component. Keep Dragula in the viewProviders for each component. 

Now when each component view is created, the [dragula] viewProvider call will refer to the same root DragulaService instead of one created for the individual component.

**Comment by activeperception** [comment]
Hi @olliholliday ,

That seems to partially work: for the drag and drop between layers to work I have to not load the css. The problem is that the models do not seem to be updated at all (with the [dragulaModel] directive).

I'll try to put together a jsfiddle

**Comment by ferredel** [comment]
Hello @olliholliday.

Just a suggestion: Have you tried to load the CSS on a parent component and then use `ViewEncapsulation.None` ?

That seems work for me.

**Comment by Bhushan001** [comment]
@activeperception does this feature available yet? to drag and drop between multiple components?

**Comment by activeperception** [comment]
Hi,

From my experiments If you are not using [dragulaModel] then drag and drop between nested components works well as long as, as per other users suggestions, you only set **viewProviders: [ DragulaService ]** once in the top/root component.

I've spend some time trying to understand why dragulaModel fails when dragging/dropping a subtree and I could identify the culprit in updating the storage of models in drake.models. Unfortunately I'm packed with work and I gave up trying to fix the original implementation and forked the project.

In the fork I replaced drake.models completely and I store the models in the data atttribute (requires jquery, that is not even in the dependencies) ($().data)

If I wasn't ashamed of how quick and dirty that work is I would have created a pull request. fork: https://github.com/activeperception/ng2-dragula

**Comment by denodaeus** [comment]
Any status on this?  I can get this to work across multiple components as long as the parent component uses the same instance of dragula service.  The problem now is the style when dragging and dropping the cards -- the in drag progress event for some reason isn't firing.

Here's a video showing the behavior:

http://screencast.com/t/9RtuSgxQzcLs

**Comment by valorkin** [comment]
ok, I will have to check this out
https://github.com/valor-software/ng2-dragula/compare/master...activeperception:master

**Comment by isaacplmann** [comment]
I got a tree structure drag and drop working like this:

**Top level component**

- CSS ViewEncapsulation.None, include any css here
- Dragula Directive
- DragulaService ViewProvider
- Registering an `accepts` filter on the dragula service that stops items from being dropped inside themselves

        accepts: (el: Element, target: Element, source: Element, sibling: Element): boolean => {
         return !el.contains(target); // elements can not be dropped within themselves
        },

- Registering a `moves` filter on the dragula service so that an entire item is moved together

        moves: (el: Element, container: Element, handle: Element): boolean => {
          // only move favorite items, not the icon element
          return el.tagName.toLowerCase() === 'mvp-navigation-item';
        },

- Html template looks like this

        <div class="nav--favorites__root" [class.is-dragging]="isDragging" [dragula]="'favorites'" [dragulaModel]="favoriteLinks">
          <navigation-item *ngFor="let link of links" [link]="link">
          </navigation-item>
        </div>

**Navigation item component**

- Dragula Directive
- No DragulaService ViewProvider
- Html template looks like this

        <a href class="list-group-item" linkActive="active" [linkTo]="link?.url" (click)="followLink($event, link)">
          <span class="glyphicon glyphicon-{{link?.icon ? link?.icon : 'unchecked'}}"></span>
          <span class="nav__label">{{link?.label}}</span>
        </a>
        <div *ngIf="link?.children" class="list-group list-group-inverse nav--favorites__submenu" [class.is-expanded]="link?.isExpanded" [class.is-empty]="link?.children?.length === 0" [dragula]="'favorites'" [dragulaModel]="link?.children">
          <navigation-item *ngFor="let childLink of link?.children" [link]="childLink">
          </navigation-item>
          
          <a class="btn btn-link toggle" (click)="link.isExpanded = !link.isExpanded; $event.preventDefault();"><span class="glyphicon glyphicon-triangle-{{link?.isExpanded ? 'top' : 'bottom'}}"></span></a>
        </div>

You'll need to style things to make the .nav--favorites__submenu visible as a drop target while dragging an item.

**Comment by thomasbee** [comment]
@isaacplmann Excuse the question, but how do you register the accepts() filter on the DragulaService?

**Comment by isaacplmann** [comment]
You pass an object to the setOptions function of the DragulaService view provider.

Like this:
```
    this.dragulaService.setOptions('favorites', {
      accepts: (el: Element, target: Element, source: Element, sibling: Element): boolean => {
        return !el.contains(target); // elements can not be dropped within themselves
      },
      moves: (el: Element, container: Element, handle: Element): boolean => {
        // only move favorite items, not the icon element
        return el.tagName.toLowerCase() === 'mvp-navigation-item';
      },
    });
```

**Comment by thomasbee** [comment]
@isaacplmann that give me the error
```
Error: Bag named: "favorites" already exists.
```

**Comment by isaacplmann** [comment]
It sounds like you're already calling this.dragulaService.setOptions('favorites') somewhere.  Just add a second argument to your original call.

**Comment by thomasbee** [comment]
@isaacplmann I never call that. I'll try now to reconstruct your entire example.

**Comment by isaacplmann** [comment]
I just ran into the same error message.  It happens for me when the setOptions call is in the ngAfterViewInit function (or at some point after the component has loaded).  setOptions works for me in the component constructor or the ngOnInit function.

**Comment by qnreck** [comment]
@thomasbee I think that you called `this.dragulaService.setOptions('favorites')` outside constructor or outside ngOnInit, right? If you had set bag name in template, something like `[dragula]='"favorites"'`, it will created the dragula bag with "favorite" name, and when you tried to set options for it by your code, `Error: Bag named: "favorites" already exists.` will show. Just try to put setOptions code inside constructor or ngOnInit, I think it will work.

**Comment by badpenguin** [comment]
@isaacplmann thanks! putting the "viewProviders: [DragulaService]" onto a parent component, the one without the Dragula directive maded it work!

**Comment by badpenguin** [comment]
@isaacplmann however when i added a different bag on the parent container (i wanna move pages each other, and items each other) ... everything crashes with "Bag named already exists".

**Comment by vineetsagar7** [comment]
Facing same issue while using dragula.

My app have three component **app.componenet**, **left.component**, **middle.componenet**. In app.compoenet, i am calling left.component and middle.componenet. All three are different component . i want to drag an element from left to middle component. Code below for three component. any help would be appreciable. 

**app.componenet**
```sh
`import {Component} from '@angular/core';
import {Dragula, DragulaService} from 'ng2-dragula/ng2-dragula';
import { ROUTER_DIRECTIVES } from '@angular/router';
import { leftPannel } from './leftPannel/left.component';
import { middlePannel } from './MiddlePannel/middle.component';

@Component({
    selector: 'my-app',
    directives:
    [ Dragula,
      ROUTER_DIRECTIVES,
      leftPannel,
        middlePannel
    ],
    viewProviders: [DragulaService],
    template:"
    <div class='wrapper'>
    <left-Pannel-View></left-Pannel-View>_
    <middle-Pannel-View> </middle-Pannel-View>
  "
})
export class AppComponent {
    constructor(private dragulaService: DragulaService) {
        this.dragulaService.setOptions('first-bag', {
            accepts: (el: Element, target: Element, source: Element, sibling:Element): boolean => { return !el.contains(target); },
            moves: (el: Element, container: Element, handle: Element): boolean => 
            { return el.tagName.toLowerCase() === 'mvp-navigation-item';  },
        });
}
}
```

 **left.component**
```sh
import { Component } from '@angular/core';
import {Dragula} from 'ng2-dragula/ng2-dragula';
import { middlePannel } from '../MiddlePannel/middle.component';

@Component({
    selector: 'left-Pannel-View',
    directives : [Dragula],
    template:
    `
    <div class=' leftPannel container' [dragula]='"first-bag"' [dragulaModel]='many'>
        <h3> {{Title}}: </h3> {{many|json}} 
            <div class="tileLeft text-center" *ngFor='let text of many' [innerHtml]='text'></div>           
        </div>
 `,
    styles: [`
      .leftPannel{
        border:thin groove black;
        width:20%;
        height:77%;
        float:left;
        color:white;
        background-color: #FFB85F;
        }
      .tileLeft{
        margin:10px;
        float:left;
        width:40%;
        height:10%;
        border:thin none white;
        background-color: #505050;     
        transition: transform 400ms ease, opacity 400ms ease;
        } 
    `]
})
export class leftPannel {
    Title = "Drag Element From Here";
    public many: Array<string> = ['Element1', 'Element2', 'Element3', 'Element4', 'Element4']
}
```

 **middle.componenet**
```sh
import { Component } from '@angular/core';
import {Dragula} from 'ng2-dragula/ng2-dragula';
import { leftPannel } from '../leftPannel/left.component';
import { ROUTER_DIRECTIVES , Router} from '@angular/router';
import { APP_ROUTER_PROVIDERS } from '../app.route'

@Component({
    selector: 'middle-Pannel-View',
    directives: [Dragula, ROUTER_DIRECTIVES],
    template:
    `
 <div class='middlePannel container' [dragula]='"first-bag"' [dragulaModel]='many2'>
       <h3> {{Title}}: </h3> {{many2|json}}

    <div (click)="check(text)" class="tileLeft text-center" *ngFor='let text of many2' [innerHtml]='text'>
</div>   <router-outlet> </router-outlet>   </div>
`,
    styles: [`
     .tileRight{
        margin:10px;
        width:40%;
        float:right;
        height:10%;
        border:thin none white;
        background-color:  #FF7A5A;
        } 
    .middlePannel{
        border:thin groove black;
        width:60%;
        height:77%;
        float:left;
        background-color:#77BED2;
        }
     .tileLeft{
        margin:10px;
        float:left;
        width:40%;
        height:10%;
        border:thin none white;
        background-color: #505050;     
        transition: transform 400ms ease, opacity 400ms ease;
        }     
    `]
})
export class middlePannel {
    Title = "Drop Here";
    public many2: Array<string> = [];
    check(element) {
        alert(element);
        this._router.navigate([element]);
    }
```

**Comment by isaacplmann** [comment]
Two things I noticed in your code.

1. You don’t need the `accepts` option if you’re not trying to drag an element inside of another draggable element.  Although it won’t hurt anything to leave it there.
2. Your `moves` option is only allowing you to move <mvp-navigation-item> tags - which I don’t think you want.  Those are components that I made in my app.  You could either remove the `moves` option or change it to check if className of the element contains “tileLeft”.

**Comment by isaacplmann** [comment]
That "bag named already exists” error happens when either:

1. You call dragulaService.setOptions on the same bag twice.  (You probably didn’t do that.)
2. You call dragulaService.setOptions somewhere outside of the constructor or ngOnInit.  (i.e. after the [dragula] directive has been rendered and automatically created the bag itself.)

**Comment by lluisnieto** [comment]
Just to help a bit guys: use the same name for parent and nested dragulas. I was using something like 'first-bag' and 'second-bag'. Settings the same name for both started working :)

**Comment by gnujeremie** [comment]
Is it working with the last angular version ? (RC6). I'm completely lost, and can't find how to make it work. I'd like to drag/drop elements between 2 different components. :-/

**Comment by forsak3n** [comment]
Yes, it works.

You should use the 'dragula' directive with the same bag name on both components.


Like this:

```javascript
<cmp1 [dragula]=" 'bagName' "></cmp1>
<cmp2 [dragula]=" 'bagName' "></cmp2>
```

**Comment by gnujeremie** [comment]
@forsak3n Oh god I forgot the ' between the " (so I was passing an unknown variable instead of a string). Thanks a lot

**Comment by PEsteves8** [comment]
The whole 'already exists' has been happening to me, when I switch to another component within the same module (although I'm not dragging between them or anything). I'm not sure if I'm doing something wrong, but I solved it by running dragularService.destroy() on ngOnDestroy when I get out of the component that is using it. When returning the options are set again and it works fine. Not sure if that may be problematic in the future.

**Comment by isaacplmann** [comment]
It sounds like you need to set `providers: [DragulaService]` on the individual components instead of higher up in the component tree.  If two different components use the same DragulaService instance to register the same bag name, you'll get this error.

**Comment by PEsteves8** [comment]
That does work and now I don't have to destroy it. It didn't even occur to me given that almost always providers are set in the module.

I'm still confused though. I only use it in one component. However, that component does get destroyed and recreated without leaving the same module where I'm importing DragularModule. So I'm guessing that when the component gets recreated the 'bag' still existed from the previous one. 

Isn't it possible to have the DragularModule deal with that kind of thing since it gets imported in the using module along with the service? Or is this one of the few situations where having providers at component level is really required?

I guess I still have to understand why would a component need to use providers instead of the module that consumes it, which is what almost always happens.

**Comment by andyrue** [comment]
Has anybody had success doing this between separate router-outlets? I have one bag declared in a named router-outlet, `<router-outlet name='aux'></router-outlet>`. And the other is in my main `<router-outlet></router-outlet>`. The two dropzones don't seem to know about each other. I've had it working before when both dropzones were in the same component.

**Comment by ThomasPe** [comment]
@andyrue did you get this working?

**Comment by andyrue** [comment]
@ThomasPe I did, but I don't recall what I did to get it working. In the end I don't think it was really due to the named route. Just make sure you're injecting the DragulaService as a singleton service. Looking at my commit log, I see I also ended up moving the `dragulaService.setOptions` statements for that particular dragula bag from inside my sub-components to the high level `appComponent`. I vaguely remember that having something to do with it.

**Comment by akempes** [comment]
This is what worked for me:

In the app.module.ts:  
- Replace the `import { DragulaModule } from 'ng2-dragula';` by `import { DragulaService } from 'ng2-dragula';`
- Remove the `DragulaModule` from the imports:[ ... ]
- Add the `DragulaService` at providers:[ ... ]

```js
import { NgModule } from '@angular/core';
import { AppComponent } from './app.component';
import { DragulaService } from 'ng2-dragula';

@NgModule({
    declarations: [
        AppComponent
    ],
    imports: [],
    providers: [
        DragulaService,
        ...
    ],
    bootstrap: [AppComponent]
})

export class AppModule {}
```

Next step is to add the directive to your (shared) module:

```js
import { NgModule } from '@angular/core';
import { DragulaDirective } from 'ng2-dragula';

@NgModule({
    declarations: [
        DragulaDirective,
        ...
    ],
    exports: [
        DragulaDirective,
        ...
    ]
})
export class SharedModule { }
```

**Comment by andyrue** [comment]
Upgrading to Angular 5 brought me back to this issue, and I recall now what I did to fix it originally. I forked the project and added a `forRoot` function in the DragulaModule export. This allows you to setup a singleton service with the module but still be able to import DragulaModule in different modules.

@akempes Solution does work, but it seems to fail if you build with AOT because even though you're not importing the DragulaModule anymore, AOT seems to still find it within node_modules and complains about DragulaDirective being declared in multiple modules. Without AOT enabled, it builds and runs fine.

I created a PR #805 that solves the problem.

**Comment by 1456118242** [comment]
Hello @andyrue  @isaacplmann  I want drag and drop multiple Angular5 components items Between two lists
I have no idea Can you give me an example?  Thanks

**Comment by smartm0use** [comment]
Hello, I have a parent component (A) with 2 child components (B) that are 2 instances of the same component. Every child component has a dragula container in the template so I can move items from a component to another.

In component B I use `DragulaService` in the constructor:

```
this.dragulaService.dropModel("VAMPIRES").subscribe(args => {
    // item dropped
});
```

but since the component is created twice, when I move card from a component to another, I get two drop events instead of one.

How can I trigger drop event one time?


Component B template:

```
<div class="ui cards mini" dragula="VAMPIRES" [(dragulaModel)]="items">
    <div class="ui card" *ngFor="let item of items">
        <div class="content">
            <div class="header">
                {{item.title}}
            </div>
            <div class="meta">
               {{item.date}}
            </div>
            <div class="description">
                {{item.desc}}
            </div>
        </div>
    </div>
</div>
```

**Comment by andyrue** [comment]
@smartm0use You need to move your dropModel subscription to Component A. Since it's currently in Component B, it's subscribing every time one of them is created.

**Comment by smartm0use** [comment]
> @smartm0use You need to move your dropModel subscription to Component A. Since it's currently in Component B, it's subscribing every time one of them is created.

If I do this, then how to get `args` of the drop event in the child components?

**Comment by andyrue** [comment]
I'm not sure what you're doing with the args, but you could bind an input on Component B and update it every time the subscription fires. That way you're only subscribing once, but all Component Bs will get the args.

**Comment by smartm0use** [comment]
Ok, that is the way I'm using. I thought there was a better solution, a Dragula solution.
Thank you!
