### ISSUE TITLE
EXCEPTION: Unexpected directive value 'undefined' on the View of component

### ISSUE THREAD

**Issue by triplejberger** [valor-software/ng2-dragula#188]
I added ng2-dragula to my Angular 2.0.0-beta.7 project (I used Angular's quick start version not angular2-webpack / angular2-seed) via npm install as described here: https://github.com/valor-software/ng2-dragula/wiki
I mapped `"ng2-dragula/ng2-dragula": "lib/ng2-dragula.js"` to my build folder and imported Dragula and DragulaService `import {Dragula, DragulaService} from 'ng2-dragula/ng2-dragula';`.
This works fine but does of course nothing. 😜
Adding: `directives: [Dragula], viewProviders: [DragulaService]` does not work. If I navigate to the component I receive the following error: `EXCEPTION: Unexpected directive value 'undefined' on the View of component`
That's exactly what is written in the wiki. Do I miss something? Is the wiki outdated?

**Comment by NathanWalker** [comment]
At the moment, the seeds mentioned in this wiki are "supported": https://github.com/valor-software/ng2-dragula/wiki

Additionally, there's nothing in the wiki that mentions mapping "ng2-dragula/ng2-dragula": "lib/ng2-dragula.js", not sure where you got that from?

You need to map `dragula`, not `ng2-dragula` which are 2 different things.
Once you get the mapping for `dragula` right, you should be better footing. Let me know how things go after trying that.

**Comment by triplejberger** [comment]
I need to map `ng2-dragula` because in my build file I don't have the same folder structure. Otherwise this won't work `import {DragulaService, Dragula} from 'ng2-dragula/ng2-dragula';` In `build/lib` I have ng2-dragula.js and

**Comment by NathanWalker** [comment]
I'd need to see how you have systemjs setup to help further. Possible to share github project?

**Comment by triplejberger** [comment]
This is my SystemJS setup:
```
<script>
      System.config({
        packages: {        
          app: {
            format: 'register',
            defaultExtension: 'js'
          }
        },
        map: {
          "ng2-dragula/ng2-dragula": "lib/ng2-dragula.js",
          "dragula": "lib/dragula.min.js"
        }
      });
      System.import('app/boot')
            .then(null, console.error.bind(console));
</script>
```
I started with the 5 min example from https://angular.io/docs/ts/latest/quickstart.html.

**Comment by PhilippRoessner** [comment]
I have the same problem here. my System.js - config looks like @triplejberger 's.

Why are these things have to be configured? I mean, my IDE (Visual Studio) works fine with the angular2 libs. Typescript imports are working fine, system.js works without any further configuration. I have installed ng2-dragula the same way as angular2, I am using it the same way than angular2. I really don't get why it is always such a challange.

**Comment by NathanWalker** [comment]
Challenge is not `ng2-dragula`, it's actually `dragula`, the base library that must also be setup for this lib to work. It's published in a way that was not the most 'seamless'.
System with `register` format seems to always be more of a challenge with some 3rd party libs.
I'll try the same thing today/tomorrow (from quickstart quide) and see what I can find out.

**Comment by NathanWalker** [comment]
Ok @triplejberger and @PhilippRoessner, I just added specific instructions on how to configure systemjs when using angular docs 5 Min QuickStart:

https://github.com/valor-software/ng2-dragula/wiki#5-min-quickstart

Cheers!
