### ISSUE TITLE
EXCEPTION: TypeError: dragula is not a function

### ISSUE THREAD

**Issue by vvh-empora** [valor-software/ng2-dragula#204]
hiho, sry but i have to use this channel to get some basic ng2 support. this is my first ng2 project and i'm not sure how to handle ng2 in the right way...

i'm just using an apache to provide my website and this are my scripts:

index.html

	</html>
		<head>
			<script src="/ng2app/listFlow/node_modules/dragula/dist/dragula.js"></script>
														

			
			
			<script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.35.0/es6-shim.min.js"></script>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.20/system-polyfills.js"></script>
			<script src="https://npmcdn.com/angular2@2.0.0-beta.14/es6/dev/src/testing/shims_for_IE.js"></script>

			<script src="https://code.angularjs.org/2.0.0-beta.14/angular2-polyfills.js"></script>
			<script src="https://code.angularjs.org/tools/system.js"></script>
			<script src="https://npmcdn.com/typescript@1.8.9/lib/typescript.js"></script>
			<script src="https://code.angularjs.org/2.0.0-beta.14/Rx.js"></script>
			<script src="https://code.angularjs.org/2.0.0-beta.14/angular2.dev.js"></script>

			
			<script>
				System.config({
					transpiler: 'typescript',
					typescriptOptions: {
						emitDecoratorMetadata: true
					},
					packages: {
						'app': {
							defaultExtension: 'ts'
						}
					},
					map: {
						'dragula': '/ng2app/listFlow/node_modules/dragula/dist/dragula.js',
						'crossvent': '/ng2app/listFlow/node_modules/crossvent/dist/crossvent.min.js',
						'contra/emitter': '/ng2app/listFlow/node_modules/contra/emitter.js',
						'ticky': '/ng2app/listFlow/node_modules/ticky/ticky-browser.js',
						'atoa': '/ng2app/listFlow/node_modules/atoa/atoa.js',
					}
				});
			</script>

			<script>
				System.import( '/ng2app/listFlow/main.ts' )
						.then(null, console.error.bind(console));
			</script>

		</head>
		<body>
			<list-flow>Loading...</list-flow>
		</body>
	</html>

main.ts

    import {bootstrap}  from 'angular2/platform/browser';
    import {ListFlow} from './Component/ListFlow';
    bootstrap(ListFlow);

ListFlow.ts

    import {Component} from 'angular2/core';
    import {DragulaService, Dragula} from "../ng2-dragula/ng2-dragula"; // a direct clone from git repo
    
    @Component({
        selector: 'list-flow',
        directives: [Dragula],
        viewProviders: [DragulaService],
        template: `
        <div>
            <div class='wrapper'>
                <div class='container' [dragula]='"first-bag"'>
                    <div>You can move these elements between these two containers</div>
                    <div>Moving them anywhere else isn't quite possible</div>
                    <div>There's also the possibility of moving elements around in the same container, changing their position</div>
                </div>
                <div class='container' [dragula]='"first-bag"'>
                    <div>This is the default use case. You only need to specify the containers you want to use</div>
                    <div>More interactive use cases lie ahead</div>
                    <div>Make sure to check out the <a href='https://github.com/bevacqua/dragula#readme'>documentation on GitHub!</a></div>
                </div>
            </div>
        </div>
      `,
    })
    export class ListFlow {
    
    }

as you can see, i have refer to NPM packages and also a direct clone to `ng2-dragula` repositor. i have also test with `ng2-dragula` from NPM repo, but the same error:

> EXCEPTION: TypeError: dragula is not a function in ["first-bag" in ListFlow@3:35]

plz help me to get this simple demo running :)

**Comment by valorkin** [comment]
try to add `import * as dragula from 'dragula`` in `main.ts`
