### ISSUE TITLE
feat(build): add system.js bundles

### ISSUE THREAD

**Issue by programmersharp** [valor-software/ng2-dragula#230]
I am quite new NodeJS and Angular developer.

My ultimate goal is to have only one ng2-dragula.js file on the web page to avoid several separate requests for dragula.directive.js, dragula.provider.js, dragula.js and ng2-dragula.js. 
Below you can see that there are separate requests for this:
![image](https://cloud.githubusercontent.com/assets/2078015/14883840/fc9f0358-0d40-11e6-8c98-22149827cea2.png)

My component has the line below:
`import {Dragula, DragulaService} from 'ng2-dragula/ng2-dragula';`

My tsconfig.json is below:
`{
  "compilerOptions": {
    "target": "ES6",
    "module": "commonjs",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  }
}`

So, what I am trying to do. 
Way 1:
I tried to change System config the way below:
`System.config({
            defaultJSExtensions: true,
            packages: {
                angular2: { defaultExtension: false }, rxjs: { defaultExtension: false }
            },
            paths: {
                'dragula': 'node_modules/dragula/dist/dragula.js',
                'ng2-dragula/*': 'node_modules/ng2-dragula/bundles/ng2-dragula.js',
            }
        });`

But it doesn't work, but I guess it should not, but not sure.

Way 2:
I tried to do it manually and added to my html page:
`<script src="node_modules/ng2-dragula/bundles/ng2-dragula.js"></script>`

But in this case 2 requests go as you can see below:
![image](https://cloud.githubusercontent.com/assets/2078015/14883984/1f2b7a5e-0d42-11e6-8cf3-22e175043f7e.png)
The first one is from script tag I added manually, but the second request seems is generated by import operator from my component and gives error.

**Comment by valorkin** [comment]
use webpack or rollup or system.js builder
in other words: bundler
and yes, I will add system.js bundler to this repo later on

**Comment by programmersharp** [comment]
It would be great if you can inform me when it will be in this repo. Many Thanks.
