### ISSUE TITLE
"Drag animation" not working

### ISSUE THREAD

**Issue by theunreal** [valor-software/ng2-dragula#257]
Copied the same code and CSS as the demo app, but the "drag animation" while dragging the object is not working properly.

The drag object appears in the bottom of my page:

![image](https://cloud.githubusercontent.com/assets/6171883/15274370/8987c122-1ab8-11e6-96f7-b3c7b385852e.png)

When I leave my mouse, the object (at the bottom) dissapears.

What's wrong?

**Comment by valorkin** [comment]
not enough info to guess what is wrong
welcome here to ask: https://gitter.im/valor-software/ng2-bootstrap

**Comment by crisipix** [comment]
I had the same issue, but it seems that the dragula css wasn't being picked up by my browser. 
I just had to simply clear my cache and when the dragula.css properly loaded the selected item displayed properly. 

Before : I was trying to move the "are" and it just shows up at the bottom of the page. 
![image](https://cloud.githubusercontent.com/assets/4096896/15678381/2a4727be-271c-11e6-97ce-ba32dc717502.png)

After clearing the browser cache: 
![image](https://cloud.githubusercontent.com/assets/4096896/15678540/b2f49dda-271c-11e6-972c-283607bb3d20.png)

**Comment by theunreal** [comment]
@crisipix What did you do to clear the cache?

**Comment by kthotav** [comment]
I have the same animation problem. did anyone find a solution.

**Comment by rphovley** [comment]
I have the same problem.  I am also using Angular 2 material, so I'm looking into if it's interfering

**Comment by balazsnemeth** [comment]
I had the same problem, but finally I figured out, that instead of 
`npm install ng2-dragula dragula --save`
I did just 
`npm install ng2-dragula --save`

Also, if you are using angular CLI, make sure you have included the `dragula.css` into the angular-cli.json "styles" array:
```
"styles": [
        "styles.css",
        "../node_modules/dragula/dist/dragula.css",
        ...
      ],
```
