### ISSUE TITLE
TypeError: dragula is not a function

### ISSUE THREAD

**Issue by oodboo** [valor-software/ng2-dragula#268]
I have included dragula.js referenced all the packages even included import * dragula in main and still getting this message? Any idea ?
I am using ConfigJS ...

Failing at this line ngOnInit in directives:
```
      this.drake = dragula({
        containers: [this.container]
      });
```

**Comment by oodboo** [comment]
If I change that line into 
```
this.drake = dragula.default({ containers: [this.container] });
```
It will start working, although VS Code will give me failing intellisence warning ...

**Comment by valorkin** [comment]
You need to install dragula typings
`typings install -A dragula -S`

**Comment by oodboo** [comment]
**/// <reference path="browser/ambient/dragula/index.d.ts" />**
/// <reference path="browser/ambient/es6-shim/index.d.ts" />
/// <reference path="browser/ambient/jasmine/index.d.ts" /> 

It was installed already and still has not worked. But never mind I am using other library now ...

**Comment by valorkin** [comment]
Which one if not a secret?:)

**Comment by oodboo** [comment]
ng2-dnd

**Comment by yahyaKacem** [comment]
I'm also having this problem on this  [plunker](https://plnkr.co/edit/V0VeLbPjqyC6Ie7PH4wi?p=preview),
I copied your files in this [plunker](https://plnkr.co/edit/hZDfFbUBWdqz1P2dq22w?p=preview) and it's working now by changing this:
```
import * as dragula from 'dragula';
```
to
```
import 'dragula';
declare let dragula;
```
also adding this configurations in the systemjs-config.js:
```
map: {
  '@angular': 'node_modules/@angular',
  'rxjs': 'node_modules/rxjs',
  'dragula': 'https://cdnjs.cloudflare.com/ajax/libs/dragula/3.7.1'
}
var _packageConfig = {
  'dragula': {
    main: 'dragula',
    format: 'global',
    defaultExtension: 'js'
  }
};
```
in both files the directive and the provider.
is this correct or should I do something else to the first [plunker](https://plnkr.co/edit/V0VeLbPjqyC6Ie7PH4wi?p=preview) to get it to work?

**Comment by Gajendrasinh** [comment]
mare pan nathi haltu
