### ISSUE TITLE
Typings should be a dependency

### ISSUE THREAD

**Issue by matthewdenobrega** [valor-software/ng2-dragula#269]
Ng2-dragula depends on typings to install, as typings is run in the postinstall script. Typings is currently listed as a devDependency, which means that users have to have typings installed globally on their machine to install ng2-dragula. While many people running Typescript will have typings installed, this is by no means guaranteed and ng2-dragula should depend on it explicitly. 

This is a duplicate of #252 but I can't re-open that issue so I'm creating a new one.

**Comment by nwallman** [comment]
I have this same exact issue as #252 and I can't find a work around.  This is making ng2-dragula unusable right now.

**Comment by valorkin** [comment]
I suppose will be better to remove post install script at all
it doesn't help
