### ISSUE TITLE
Add a demo example file 

### ISSUE THREAD

**Issue by dy0nysos** [valor-software/ng2-dragula#27]
Hi,
First of all, thank you for this amazing wrapper !

I'd like to know if it's plan to add some demo files following the latest angular quickstart ?
It might be very useful.

Thanks

**Comment by NathanWalker** [comment]
@dy0nysos You're welcome. 
Everything inside here is the demo:
https://github.com/valor-software/ng2-dragula/tree/master/src

You can run the demo/example by cloning the repo, then:
```
npm install
npm start
```
Hope that helps. Please let me know if this does not answer your question.
