### ISSUE TITLE
ng2-dragula and angular2 rc1: ReferenceError: require is not defined

### ISSUE THREAD

**Issue by kalumet** [valor-software/ng2-dragula#274]
I have followed the doc of the 5 Min quickstart of angular2 and than modified the code according to the demo setup of dragula for angular 2.

The Quickstart alone works as expected, but adding the files for dragula2 doesn't work. I get the Exception

zone.js:323 Error: ReferenceError: require is not defined(…)
I tried to follow the hints from similar questions, but couldn't fix the issue with those, therefore I added this questions.

Many thanks for any help!

**Comment by valorkin** [comment]
search for `require`, demo builded with webpack
but system.js doesn't understands it
so just search for it and replace with a link to file
