### ISSUE TITLE
Second container won't update

### ISSUE THREAD

**Issue by AleRob90** [valor-software/ng2-dragula#28]
Hello, so i'm trying to use an example from the demo page. The example have title "Angular-specific example. Fancy some ngFor?". So into dragula.providers.ts i changed line 75 
from:
drake.on('remove',function removeModel (el, source) { //bla bla bla }))
to:
drake.on('remove', (el, source) => { //bla bla bla})) 
Cause it was complaining about removeModel that doesn't have an emit function on line 83.

Now my class look like this:
export class Page1 {
  public many: Array<Object> = [{name: 'buton', type:'button'},{name:'container', type:'text'}];
  public many2: Array<Object> = [{name: 'alt buton', type:'button'},{name:'alt container', type:'text'}];
  constructor(private dragulaService: DragulaService) {
    dragulaService.setOptions('first-bag', {
      removeOnSpill: true,
      copy: function(el, source){
        return source.className.indexOf('can_move') != -1;
      },
      accepts: function (el, source) {
        return source.className.indexOf('can_move') === -1;
        // return el.className === 'can-copy';
      }
    });
    dragulaService.dropModel.subscribe((value) => {
      this.onDropModel(value.slice(1));
    });
    dragulaService.removeModel.subscribe((value) => {
      this.onRemoveModel(value.slice(1));
    });
  }
  private onDropModel(args) {
    let [el, target, source] = args;
    window.console.log('This is interesting fact', this.many2); // This is the line that give me a headache
  }

  private onRemoveModel(args) {
    let [el, source] = args;
  }
}

And the Html looks like this:

<blockquote>
 
    <xmp> <div class='wrapper'> </xmp><br />
      <xmp> <div class='container can_move' [dragula]='"first-bag"' [dragulaModel]='many'> </xmp><br />
        <xmp> <container1 *ngFor="#item of many" [type]="item.type" name="item.name"></container1> </xmp><br />
    <xmp>   </div> </xmp><br />
     <xmp>  <div class='container container2' [dragula]='"first-bag"' [dragulaModel]='many2' style="text-align:center"> </xmp><br />
         <xmp><div *ngFor='#text of many2'> </xmp><br />
          <xmp> <button *ngIf="text.type=='button'">{{text.name}}</button> </xmp><br />
         <xmp>  <div *ngIf="text.type=='text'">{{text.name}}</div> </xmp><br />
         <xmp></div> </xmp><br />
      <xmp> </div> </xmp><br />
     <xmp></div> </xmp><br />
</blockquote>

Ok so the problem is not a problem until i empty this.many2 and after that i try to move something from first container to second container. When i try to move one item from many1 onDropModel is called and my many2 has one object but into my Html elements it doesn't show at all...after i move some more times i get something in my second container but this.many2.length is >1 even if i have just one element showed.

I hope you understand otherwise tell me so i will explain more

**Comment by AleRob90** [comment]
Ok so i upload a little video with my issue. https://youtu.be/-7sZjUApuuY

**Comment by NathanWalker** [comment]
@AleRob90 Thanks for the report. I'm going to try to dig deeper this weekend when not so busy!
Hang in there and thanks for the video, that will help a lot.

**Comment by NathanWalker** [comment]
@AleRob90 I fixed the issue with `removeModel`, please try the new release `1.0.3` and reopen if you still encounter a problem. Thanks.

**Comment by AleRob90** [comment]
Actually the new release it's what i've done to make it work before i encounter this issue. Think that i've been one move ahead, you are now exactly where my issue start. The problem is that NgFor doesn't work properly. My this.many2 array contain some objects, but template won't update properly and don't show them all. The issue is that everytime i empty the second container it will somehow break when i try to drag from first container to second container. If i start with this.many2 = [], then it will be no issue to drag from first container to second, but it will break everytime i remove all things from second container. Just try to copy my code and see what happens. I tried with edge and firefox too, so it's not a browser issue.

**Comment by AleRob90** [comment]
So i will update my informations...same code...the issue is not when i remove(using removeOnSpill) all things from second container, the issue is when i remove anything from second container, even one element. The amount of drags that i will need to do from first container to second is equal to the amount of elements that i removed from second container in order to html update with new elements.

Legend: First Container == this.many1 && Second Container == this.many2.&& remove == removeOnSpill
Events: Init component, remove 1 element from second container, drag one element from first container to second container, second container element will not update with new element that was dragged from first container. 

Actually i think that my config is screwing with me. This removeOnSpill is set to true. 
Please try this if you have some time.

**Comment by AleRob90** [comment]
I don't have an option to open this again. 
From my first post i said i have done those things that you have included in this version.

What have i discovered so far:
My config have removeOnSpill set to true, so when i remove even one element from second container it will be deleted. Somehow this removeOnSpill is interfering with those dragulaModels, i think dragulaModels are not updating when i delete something using removeOnSpill and that's why elements are not updating properly.
If i delete n elements from second container using removeOnSpill, i will need to drag n+1 elements from first container to second one so my dragulaModel to update.

Please try above code using v 1.0.3 to see what i'm talking about.

**Comment by NathanWalker** [comment]
Thanks for the extra info. I hope to try it out over next couple days.

**Comment by AleRob90** [comment]
I removed all [dragulaModel] attribute and now is working properly. I solved my problem, but there still is a problem using removeOnSpill and [dragulaModel] at the same time, they are not working properly. Hope it helps. I am still watching this. Sorry if my explanations aren't properly to understand.

**Comment by AleRob90** [comment]
Any updates?:(

**Comment by NathanWalker** [comment]
@AleRob90 I'm going to request help on this one. 

cc/ @valorkin @dy0nysos

**Comment by valorkin** [comment]
ok, I will check it

**Comment by mbeckenbach** [comment]
This fixed it for me

constructor(private dragulaService: DragulaService, private changeDetectorRef: ChangeDetectorRef) {}

and then

this.dragulaService.dropModel.subscribe((value) => {
this.changeDetectorRef.markForCheck();
})
