### ISSUE TITLE
Not found dragula.directive, dragula.provider. (angular2 rc1)

### ISSUE THREAD

**Issue by Olexiy665** [valor-software/ng2-dragula#281]
Hi, many thanks for you component, I set up this component according to the instructions, but received an error:
 `GET http://localhost:3000/node_modules/ng2-dragula/src/app/directives/dragula.directive 404 (Not Found)`, `GET http://localhost:3000/node_modules/ng2-dragula/src/app/providers/dragula.provider 404 (Not Found)`

**Comment by mcziegler12** [comment]
I'm having the same issue.  Configuring the module from systemJS:
`
    <script>
      System.config({
        map: {
          moment: 'js/lib/moment.js',
          dragula: 'js/lib/dragula.min.js',
          'ng2-dragula/ng2-dragula': 'js/ng2-dragula/ng2-dragula.js'
        },
        packages: {
          app: {
            format: 'register',
            defaultExtension: 'js'
          },
          'ng2-dragula': { 
            format: 'cjs',
            defaultExtension: 'js'
          }
        }
      });
      System.import('app/main')
        .then(null, console.error.bind(console));
    </script>
`

the `js/` directory is created by gulp; all it's doing is piping necessary node modules into a smaller directory for easier deployment.

**Comment by dancancro** [comment]
I think I'm having the same problem in my project. I added dragula to the crisis-admin.component.ts file of [this plunk](http://plnkr.co/edit/z8VzCDYNrQR4KzpTVqI7?p=preview) from the Angular team to demonstrate it.

Any thoughts about this one?
