### ISSUE TITLE
Cross container drag&drop

### ISSUE THREAD

**Issue by dy0nysos** [valor-software/ng2-dragula#29]
Hi,

It seems to be impossible with this version to drag from a first container an item to a second container.

      <ul [dragula]='"bag1"' >
        <li>1</li>
        <li>2</li>
        <li>3</li>
        <li>4</li>
        <li>5</li>
      </ul>
      <ul [dragula]='"bag2"' >
        <li>1</li>
        <li>2</li>
        <li>3</li>
        <li>4</li>
        <li>5</li>
      </ul>

**Comment by AleRob90** [comment]
rename your bag2 into bag1 and you can drag...they need to have the same name

**Comment by dy0nysos** [comment]
I saw an issue on dragula where the guy is able to drag from a container to another one with a different name.
Here's the issue: https://github.com/bevacqua/dragula/issues/231

**Comment by AleRob90** [comment]
Yes, but they are selected by the user dragula([document.getElementById(left), document.getElementById(right)]). Inhere i think they are selected by the directive, so when you put that attribute dragula with 'bag1' i think it select all directives that have bag1. In that example from their page they selected by id that need to be unique...in this example it work like a class, so your bag1 is a class instead of an id

**Comment by NathanWalker** [comment]
Thanks @AleRob90 yes, the bag names need to be the same name. It's what is used to tie the containers together to work in the drag/drop operation. @dy0nysos Hope that makes sense.

**Comment by dy0nysos** [comment]
@NathanWalker Here's the reason for my cross container drag'n'drop.
I'd like to get some pictures from my bag 1 (availableModulesBag), that represents HTML modules (a text paragraph, an image) and, when dropping it in the second bag (droppedModules), i'd like to handle the drop to attach my HTML source instead of the picture.
Furthermore, i'd like to not be able to drop HTML modules from bag 2 into bag 1.

```
<modules-menu [Dragula]="availableModulesBag">
<available-module></available-module>
<available-module></available-module>
<available-module></available-module>
</modules-menu>
<preview [Dragula]="droppedModules">
<text></text>
<image></image>
<image-on-text></image-on-text>
</preview>
```

Do you think i'll be able to do so with some work on the lib, or should I directly use dragula without this wrapper ?

**Comment by NathanWalker** [comment]
We can likely support that use case with this lib. It will be a week or
more before I could look into unfortunately.

**Comment by dy0nysos** [comment]
I'll try to take a look by myself. I'll make a pull request if I'm able to get into it alone.
Thanks a lot for your work @NathanWalker

**Comment by AleRob90** [comment]
I've done something like this in my previous issue. I've created 2 arrays and instead of moving html i move array's objects. I use ngFor for that. You have an example on ng2-dragula demo page...it's almost at the bottom at the page. Hope it helps

**Comment by dy0nysos** [comment]
I almost finished handling this particular behavior.
@AleRob90 I copied a small part of your script, thank you it was helpful.

I'm not using arrays, I just use objects class to handle them properly.
My last problem is that my source object is copied into my second container, and I would like to prevent the lib from doing this.

**Comment by NathanWalker** [comment]
@dy0nysos Exciting news, thanks for giving it a go. If you get it working, a PR would be appreciated :+1:

**Comment by dy0nysos** [comment]
Hi @NathanWalker,
I overrode copy, accepts and moves in order to be able to drag from the first part of my container to the second.

I was able to modify the way elements are copied to the second part of the container by subscribing to the drop event.

I just removed copied element and replaced it with my html modules creation.
So there's no lib modification but I'll try to dig into it when I'll have some time to spend.

You can find a gist just here: https://gist.github.com/dy0nysos/15dcada235911bd5caaf

Thanks for your help, thanks to @AleRob90 too.

**Comment by NathanWalker** [comment]
@dy0nysos Sounds like this is resolved? If so, please close this issues :+1:
