### ISSUE TITLE
*help wanted* Ability to catch the drop event but reverting the dragged element back to original container

### ISSUE THREAD

**Issue by GhazalAghvami** [valor-software/ng2-dragula#326]
Hi there, 

This is not an issue but I am trying to build a drag and drop component where the user can associate different items on the left with options on the right. I am using the `drop` event to save the ids of the dragged element and the target:

`    dragulaService.drop.subscribe((value) => {
      this.draggedElementId = value[1].getAttribute('file-id');
      this.targetId = value[2].id
    }) `

My question is, how can I catch the drop event but revert the dragged item back to its original container?

**Comment by dedeibel** [comment]
What was your solution to the problem?
