### ISSUE TITLE
Cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by tushartgsit** [valor-software/ng2-dragula#332]
angular2.dev.js:23597 EXCEPTION: TypeError: Cannot read property 'appendChild' of nullBrowserDomAdapter.logError @ angular2.dev.js:23597BrowserDomAdapter.logGroup @ angular2.dev.js:23608ExceptionHandler.call @ angular2.dev.js:1260(anonymous function) @ angular2.dev.js:12576NgZone._notifyOnError @ angular2.dev.js:13620onError @ angular2.dev.js:13528Zone.run @ angular2-polyfills.js:1247(anonymous function) @ angular2.dev.js:13543zoneBoundFn @ angular2-polyfills.js:1220
angular2.dev.js:23597 STACKTRACE:BrowserDomAdapter.logError @ angular2.dev.js:23597ExceptionHandler.call @ angular2.dev.js:1262(anonymous function) @ angular2.dev.js:12576NgZone._notifyOnError @ angular2.dev.js:13620onError @ angular2.dev.js:13528Zone.run @ angular2-polyfills.js:1247(anonymous function) @ angular2.dev.js:13543zoneBoundFn @ angular2-polyfills.js:1220
angular2.dev.js:23597 TypeError: Cannot read property 'appendChild' of null
    at F (dragula.min.js:1)
    at HTMLHtmlElement.N (dragula.min.js:1)
    at Zone.run (angular2-polyfills.js:1243)
    at Zone.run (angular2.dev.js:13543)
    at HTMLHtmlElement.zoneBoundFn (angular2-polyfills.js:1220)

**Comment by taras-budzyn** [comment]
@tushartgsit 
probably it's the same reason that I was have
try to set options for dragulaService at the ngOnInit function
