### ISSUE TITLE
Drag'n'Drop between two components possible?

### ISSUE THREAD

**Issue by ospaarmann** [valor-software/ng2-dragula#353]
Lets say I have a component that displays a list of projects and a component that displays a list of tasks. Is it possible to use ng2-dragula to drag a task into one project? I set up everything according to the docs but no event is fired. It works within a component. 

Would be great if someone could help me!

**Comment by ildarnm** [comment]
Solution in https://github.com/valor-software/ng2-dragula/issues/187#issuecomment-208504080
