### ISSUE TITLE
Ionic 2 - Drag doesn't scroll out of screen

### ISSUE THREAD

**Issue by dhndeveloper** [valor-software/ng2-dragula#355]
Hello,

I'm working on a ionic 2 project. I set it up so that I could drag between different arrays like the last example in the ng2 demo. 

The only issue is that I can't drag below the fold or the last item current in the view. The screen does not scroll with the drag. 

Anyone have any ideas? I would love some help.

Thanks!!

**Comment by kuiperr005** [comment]
@audan2009 have you already found a solution? I'm looking for something similar for my app.

**Comment by audan2009** [comment]
Yes, I modified the built in reorder functionality and made it a custom provider but that was before RC0. I'm waiting until a more stable release before I try that again.

**Comment by kuiperr005** [comment]
Ah thanks for your reply, that could be a solution for me too! Now hoping that a more stable version will arrive soon!

**Comment by quiringk** [comment]
@dhndeveloper @kuiperr005 Did either of you find a solution to this? I saw this issue from the dragula repo (https://github.com/bevacqua/dragula/issues/121) points to dom-autoscroller. I am going to attempt to try and make that work but not sure it will.

**Comment by copeus** [comment]
I got next solution 
```
<ion-content  [attr.noScroll]="shouldScroll">
```
At scss:
```
[noScroll] .scroll-content {
  overflow: hidden;
}
```

```
  shouldScroll: boolean|null = null;
...
  this.drag.drag.subscribe(() => {this.shouldScroll = true; });
  this.drag.dragend.subscribe(() => {this.shouldScroll = null; });
```

For me it works

**Comment by zxc19890923** [comment]
@copeus  我感觉最好在单机的时候就隐藏滚动条会更好一点。

**Comment by zxc19890923** [comment]
this.drag.drag.subscribe(() => {this.shouldScroll = true; });

add touchstart  touchend 

touchstart  => this.shouldScroll = true;
touchend => this.shouldScroll = false;

**Comment by haroldhalcyon28** [comment]
@copeus 



> At scss:
> 
> ```
> [noScroll] .scroll-content {
>   overflow: hidden;
> }
> ```

> Replace to:
> 
> ```
> [noScroll="true"] .scroll-content {
>   overflow: hidden;
> }
> ```
