### ISSUE TITLE
Update to RC 5?

### ISSUE THREAD

**Issue by psyCodelist** [valor-software/ng2-dragula#357]
Hi guys.

Thank you for this amazing lib. I was wondering if you guys have any plan to update the module for RC-5?

Cheers

**Comment by simonpeters** [comment]
Is it possible to get it working for RC5?

**Comment by nimaen** [comment]
Yes it is, you have to import it in a module like this :

```js
@NgModule({
  imports: [...],
  exports: [..., Dragula],
  declarations: [..., Dragula],
  providers: [..., DragulaService]
})
```

**Comment by jamiewastin** [comment]
@nimaen - That's only a sticking plaster. 

By declaring the Dragula directive / service in your own module, you are claiming ownership of them. 

Using this approach, if you have two modules in the same project both using Dragula, or if you use a third-party component that has done the same you will end up with:

    Type Dragula is part of the declarations of 2 modules: MyModule1 and MyModule2

The above might keep you going in the meantime, but the `ng2-dragula` project will have to export it's own module before the release of Angular 2.

**Comment by nimaen** [comment]
@jamiewastin - Indeed, but I haven't said anything regarding the ownership 😄 
Of course it should be declared in its own module, that's common sense 😉

**Comment by PRR24** [comment]
+1 for RC6 level.

**Comment by otelnov** [comment]
https://github.com/valor-software/ng2-dragula/pull/396
