### ISSUE TITLE
Drag and drop between two dragula bags called different?

### ISSUE THREAD

**Issue by maik10** [valor-software/ng2-dragula#365]
`<ul class="nav nav-pills" [dragula]='"tools"'>
            <li><span class="fa fa-plus-square"></span></li>
            <li><span class="fa fa-plus-square"></span></li>
            <li><span class="fa fa-plus-square"></span></li>
</ul>`
`<workspace [dragula]='"workspace"'></workspace>`

`constructor(private route: ActivatedRoute, private router: Router,private activatedRoute: ActivatedRoute,private dragulaService: DragulaService) {
        dragulaService.setOptions('workspace',{copy: true});
        dragulaService.setOptions('tools',{});
     }`

I need move elemets to the workspace or send data to create a new element. I really aprecciated your help.

**Comment by daniele-zurico** [comment]
Hi @maik10 I got your same problem have you fixed in same way?

**Comment by PEsteves8** [comment]
Me too. Either moving between two bags. Or being able to define different options for different <div> referencing the same bag.
