### ISSUE TITLE
Getting require is not defined error while trying to include ng2-dragula in Angular CLI

### ISSUE THREAD

**Issue by ankama-archana** [valor-software/ng2-dragula#372]
I have tried to download ng2-dragula@1.1.3 and also installed typings for dragula but still I'm getting require is not defined while doing an ng build -prod. Can you please help in resolving this issue?

**Comment by cmeredith** [comment]
Just got this working after a weekend away from working on it to no avail on Friday. Here's how you do it. This is using SystemJS with angular cli at 1.0.0-beta.10, I haven't tried it with WebPack yet.

1. Run the npm install command from the main documentation
2. Add this to the vendorNpmFiles array in angular-cli-build.json:
````
'ng2-dragula/**/*.+(js|ts)',
'dragula/dist/*.+(min.css|min.js)'
````
3. Run ng build and double check that the files get copied into vendor.
4. Open system-config.ts, add this into the map object at the top of the file:
````
'dragula': 'vendor/dragula/dist/dragula.min.js',
'ng2-dragula': 'vendor/ng2-dragula'
````
5. Under that map object, add this to the packages object: 
````
'ng2-dragula': {
    defaultExtension: 'js',
    main: 'ng2-dragula.js'
}
````
6. You should now be able to use `import { Dragula, DragulaService } from 'ng2-dragula/ng2-dragula';` on your components.

**Comment by ankama-archana** [comment]
Thanks cmeredith for quick reply.

Still I'm getting error as below while building 
    Loading main.js
    **Error: ENOENT: no such file or directory, open 'C:\Projects\ControlCenter\CCNT_Content\emgcms\ControlCenter\tmp\
le_plugin-input_base_path-XLY4AoCr.tmp\0\vendor\dragula\dist\dragula.js'
at Error (native)**

Can you please help?

**Comment by cmeredith** [comment]
It looks like you're trying to build on a Windows machine... I'm on a Mac, but it looks like the vendor files are not being copied to the dist/ folder. Can you verify that your project has dist/vendor/dragula/dragula.js? You may need to tweak the file paths in the build json and the system-config to work for Windows.

**Comment by ankama-archana** [comment]
Hi cmeredith,

Thanks for your reply.
Actually i have added 
'dragula' {
defaultExtension: 'js',
    main: 'ng2-dragula.js'
} 
in map.
removed above code and it worked.

Thanks.
