### ISSUE TITLE
RemoveModel looks at models in target container not source

### ISSUE THREAD

**Issue by philippkoelmel** [valor-software/ng2-dragula#382]
https://github.com/valor-software/ng2-dragula/blob/master/src/app/providers/dragula.provider.ts#L76

is:
`drake.on('remove', (el: any, source: any) => {`

should be?
`drake.on('remove', (el: any, parent:any, source: any) => {`

According to https://github.com/bevacqua/dragula/blob/master/dragula.js#L275:
`drake.emit(_copy ? 'cancel' : 'remove', item, parent, _source);`

**Comment by cormacrelf** [comment]
Done
