### ISSUE TITLE
rc6, dragulaModel

### ISSUE THREAD

**Issue by snarum** [valor-software/ng2-dragula#397]
Hi
I'm trying to get dragulaModel to work on angular2 rc6, but jspm complains about:

```
Can't bind to 'dragulaModel' since it isn't a known property of 'li'. ("
```

here's my list:

```
<ul [dragula]='"first-bag"' class="collection">
  <li class="collection-item" *ngFor='let permission of (inactivePermissions)' [dragulaModel]='inactivePermissions'>{{permission.name}} </li>
</ul>
```

I've imported DragulaModule in my NgModule imports, and the [dragula] attribute is working fine.

Any clue what I am missing? using ng2-dragula 1.2.0

**Comment by snarum** [comment]
I was just being silly here. putting the [dragulaModel] on the <ul> tag solved this. 

But I would love to have an example of how the dragulaModel binding is supposed to work. I cant see that my model is being updated when changes occur. Maybe the demo could include a dragonModel example?

**Comment by magiccrafter** [comment]
It may be the case that the documentation is wrong because in the examples provided it is on the outer tag (in that case the ul):
```
    <div class='wrapper'>
        <div class='container' [dragula]='"another-bag"' [dragulaModel]='many'>
            <div *ngFor='let text of many' [innerHtml]='text'></div>
        </div>
        <div class='container' [dragula]='"another-bag"' [dragulaModel]='many2'>
            <div *ngFor='let text of many2' [innerHtml]='text'></div>
        </div>
    </div>
    <div class='wrapper'>
        <div class='container'>
            <pre>{{many | json}}</pre>
        </div>
        <div class='container'>
            <pre>{{many2 | json}}</pre>
        </div>
    </div>
```

https://github.com/valor-software/ng2-dragula/blob/master/demo/templates/repeat-example.html
