### ISSUE TITLE
Question: How to collapse structure while dragging?

### ISSUE THREAD

**Issue by hassanasad** [valor-software/ng2-dragula#398]
Hi - I know this is not really a ng2-dragula question but perhaps someone can help me here.

I want to be able to collapse my panels when i start dragging and open them up again once the drag stops. Now i am able to achieve this by adding CSS class when the dragging starts and remove them when it stops. However, because of collapsing the structure, when i start dragging the panels in the middle they move up from the actual holding position (because the heights change for all the elements).

I believe this can be resolved if i can get an event that fire before the dragging actually starts. Perhaps like a pre-drag event followed by drag event.

Can anyone please suggest me how to do this. Or perhaps if anyone ran into the same issue?

**Comment by fkrajcar-cirtuo** [comment]
Hi,

having the same problem here. Did anyone manage to resolve this issue somehow?

Thanks!

**Comment by hassanasad** [comment]
Not sure if the code will help but this is what i have. Its been several years so forgot how it works:

```
// Logic to detect ROOM-ITEMS dragging to expand Nest component to receive items - If Nest already has items then return false
private readonly dragStart = this.dragulaService.drag( RoomDragGroupEnum.Items ).pipe( map( ( { el } ) => el.querySelectorAll('app-proposal-room-nest app-proposal-room-item').length === 0 ) );
private readonly dragEnd   = this.dragulaService.dragend( RoomDragGroupEnum.Items ).pipe( mapTo( false ) );
readonly isDragging$       = merge( this.dragStart, this.dragEnd ).pipe( startWith( false ) );
```
