### ISSUE TITLE
ng2-Dragula for Angular2 RC4 - unable to download via npm.

### ISSUE THREAD

**Issue by BartoszBaczek** [valor-software/ng2-dragula#399]
At my company we are currently using Angular 2 RC4, and I am trying to add ng2-Dragula for that version. It seems, that it was created in commit e85edf0f58ab677f98e58c6290267de1f3fa7368. Hovewer it seems like version in package.json was not updated and now I am not able to download it via npm. 

Next commit in this repository occured 4 days ago (update to RC5), and than 2 days ago version was updated. 

Is it somehow possible to add missing version to package.json, so ng2-Dragula for Angular2 RC4 was possible to get via npm?

**Comment by quigleyj97** [comment]
We had this issue ourselves, in our package.json we just pin the version to `1.1.10`. Here's the relevant line from the package.json:  
```"ng2-dragula": "1.1.10",```  
Note the lack of a caret (`^`) in the version name. Once you make this change, just run `npm install` and it'll pull the RC4 version. 

Alternatively you can install it from the command line like so:  
```npm install ng2-dragula@1.1.10 --save```

and this will do exactly the same thing.

**Comment by BartoszBaczek** [comment]
Glad to hear, I am not the only one :) It works perfectly thanks.
