### ISSUE TITLE
ng2-dragula has no exported member 'Dragula'

### ISSUE THREAD

**Issue by liorsharabi** [valor-software/ng2-dragula#406]
when i'm trying to install my project throw npm i'm getting this error
"ng2-dragula has no exported member 'Dragula'"
the funny thing is that it worked just yesterday and i didnt change anything on the code

the error refering to this code line:

import {Dragula, DragulaService} from 'ng2-dragula/ng2-dragula';

it has no problem with DragulaService just with Dragula

**Comment by ViktorFarkas93** [comment]
Use DragulaModule or DragulaDirective instead of Dragula 

Here's  my imports

import { DragulaService, DragulaModule } from 'ng2-dragula/ng2-dragula';

imports: [ DragulaModule ],
providers:    [ DragulaService ]

in app.module.ts

**Comment by arnjmllr** [comment]
I'm having similar issue, though I have not be able to get Dragula to work at all.   I get a 404 error (shown in npm console output) with:
import { DragulaModule, DragulaService } from "../node_modules/ng2-dragula/ng2-dragula";
import { DragulaModule, DragulaService } from "ng2-dragula/ng2-dragula";

if I add .js:
import { DragulaModule, DragulaService } from "../node_modules/ng2-dragula/ng2-dragula.js";

I get 404 error on these files:
404 GET /node_modules/ng2-dragula/components/dragula.directive
404 GET /node_modules/ng2-dragula/components/dragula.provider

my systemjs.config.js look like this (i've tried adding paths and map entries, but i'm not getting it right)  I also noticed that there is a dragula directory under ng2-dragula so I tried pointing path to that version.

 paths: {
        // paths serve as alias
        //'dragula': 'node_modules/ng2-dragula/node_modules/dragula/dist/dragula.js',
       //tried this too:
      //'dragula':  'node_modules/dragula/dist/dragula.js', 
        //'ng2-dragula/*': 'node_modules/ng2-dragula/ng2-dragula.js',
        'npm:': 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      .....
      //'dragula': "node_modules/ng2-dragula/dragula/dist/dragula.js",
      //'dragula': "node_modules/dragula/dragula.js",
      //'ng2-dragula': "node_modules/ng2-dragula/ng2-dragula.js",

     ....
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
        .....
        //'ng2-dragula': { defaultExtension: 'js', main: './ng2-dragula.js' },
       // 'dragula': { defaultExtension: 'js', main: './dragula.js' }
        // and
       // 'dragula': { defaultExtension: 'js', main: './ng2-dragula/node_modules/dragula/dist/dragula.js' }
    }
  });
})(this);

truly appreciate any help.

**Comment by danyalette** [comment]
@arnjmllr two things: 
- in `systemjs.config.js`, you might need to change dragula package to `'dragula': { defaultExtension: 'js', main: './dist/dragula.js' },`
- in `app.module.ts`, you might need to change dragula import to `import { DragulaModule, DragulaService } from "ng2-dragula";`

**Comment by Apps-23** [comment]
I had a similar problem it showed : "ng2-dragula has no exported member 'Dragula'"
So instead of using Dragula , I used DragulaModule 
So my .ts file has:
import {DragulaModule , DragulaService} from "../../../node_modules/ng2-dragula/ng2-dragula"

and inside component:
 directives: [DragulaModule],
 viewProviders: [DragulaService]

but while using the code in html template of the component:
<ul style="list-style: none" *ngIf="data1.status_code!=404" [dragula]='"bag-one"' [dragulaModel]='data1' class="collection">

<li *ngFor="let project of data1"  >

<div class="col-md-4">
<div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">
            <favourite></favourite>  
            {{project.project_id}}:{{project?.project_name}}
          </h4>
        </div>     
</div>    
</div>   

</li>
</ul>

I get the error: Can't bind to 'dragula' since it isn't a known property of 'li'.
