### ISSUE TITLE
Update to final Angular 2 release

### ISSUE THREAD

**Issue by VadimDez** [valor-software/ng2-dragula#408]
Angular 2 final release was released today

```
npm WARN ng2-dragula@1.2.0 requires a peer of @angular/common@2.0.0-rc.6 but none was installed.
npm WARN ng2-dragula@1.2.0 requires a peer of @angular/core@2.0.0-rc.6 but none was installed.
npm WARN ng2-dragula@1.2.0 requires a peer of @angular/compiler@2.0.0-rc.6 but none was installed.
npm WARN ng2-dragula@1.2.0 requires a peer of @angular/forms@2.0.0-rc.6 but none was installed.
```

**Comment by hassanasad** [comment]
Even though the package files have been updated - running this `npm i ng2-dragula --save` command still produces the above warnings.

I tried clearing npm cache as well but still no luck. (`npm cache clean`)

**Comment by kiswa** [comment]
@hassanasad I think that's because @blackbaud-brandonstirnaman didn't run `npm version minor` to update npm. I just did a completely fresh install and it downloads the `package.json` from before the edits were made.

**Comment by valorkin** [comment]
@kiswa I hope you are right, will be fixed

**Comment by BjornMelgaard** [comment]
@valorkin please, fix this as soon as possible, thanks for work

**Comment by valorkin** [comment]
please do clean install
and try v1.2.1

**Comment by VadimDez** [comment]
@valorkin, Thank you!
