### ISSUE TITLE
Get new item position after dragging

### ISSUE THREAD

**Issue by theunreal** [valor-software/ng2-dragula#415]
I need to sort a list, and in order to send the data to the server side I need to get the new item position after dragging.

How I can do this with ng2-dragula?

**Comment by BojanKogoj** [comment]
Check this issue for a hacky solution https://github.com/valor-software/ng2-dragula/issues/306

**Comment by katesowles** [comment]
Try this github post, I found myself similarly stuck today and so I shared my solution there: http://stackoverflow.com/questions/41007356/angular-2-dragula-model-updating-incorrectly/43083873#43083873
