### ISSUE TITLE
Can't resolve all parameter in Angular 2 Final release

### ISSUE THREAD

**Issue by aldrindizonh** [valor-software/ng2-dragula#416]
here is my homeComponent.ts

<img width="834" alt="screen shot 2016-09-18 at 1 28 22 am" src="https://cloud.githubusercontent.com/assets/17155863/18609878/4a761710-7d3f-11e6-8dae-816efcb31464.png">

Home.module.ts
<img width="1146" alt="screen shot 2016-09-18 at 1 28 33 am" src="https://cloud.githubusercontent.com/assets/17155863/18609882/65569ee2-7d3f-11e6-9f6d-744a71ee7889.png">

**Comment by aldrindizonh** [comment]
This is now ok..

**Comment by mayconjcm** [comment]
What you did to work properly? I'm getting this problem now.

**Comment by aldrindizonh** [comment]
Just import DragulaModule in your module file
