### ISSUE TITLE
Ionic 2 - drag is working but drop isnt

### ISSUE THREAD

**Issue by maxvanloosbroek** [valor-software/ng2-dragula#421]
Hi,

Dragula is loading fine in my freshly created app and I can even drag my items, the drop behaviour is very erratic however, sometimes it moves to the other div but 9 out of 10 times it doesn't.

There's also no preview of the new position when you drag and hover over the other 'bucket' like on the [demo](https://bevacqua.github.io/dragula/).

No errors in inspector (chrome).

This is my code (it's a clean ionic 2 app with ng2-dragula@1.1.10 since ionic 2 doesn't have the latest angular2 version):

**home.ts**

``` ts
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import { Dragula, DragulaService } from 'ng2-dragula/ng2-dragula';

@Component({
  templateUrl: 'build/pages/home/home.html',
  directives: [Dragula],
  providers: [DragulaService]
})
export class HomePage {
  constructor(public navCtrl: NavController, private dragulaService: DragulaService) {

  }
}
```

**home.html**

``` html
<ion-row>
  <ion-col width-50 class="left">
    <div class="header">First Bucket</div>
    <ion-list [dragula]='"my-bag"'>
      <button ion-item>
        1
      </button>
      <button ion-item>
        2
      </button>
      <button ion-item>
        3
      </button>
    </ion-list>
  </ion-col>

  <ion-col width-50 class="right">
    <div class="header">Second Bucket</div>
    <ion-list [dragula]='"my-bag"'>
      <button ion-item>
        4
      </button>
      <button ion-item>
        5
      </button>
      <button ion-item>
        6
      </button>
    </ion-list>
  </ion-col>
</ion-row>
```

Does someone have the same issues or any clue how to find out what's going wrong?

I've tried with regular divs instead of ionic directives, but no luck.

Max

![untitled](https://cloud.githubusercontent.com/assets/16321767/18782215/a1f5fb8c-8185-11e6-9711-62810e7bd141.jpg)

**Comment by stefanmeschke** [comment]
I have the same issue, when a directive or component is beneath the bag.

My example:

`
<div *ngFor="let ticket of openTickets"
     [dragula]="'ticketsBag'" [dragulaModel]="openTickets">
  <div ticket-list-item
       [ticket]="ticket"
       id="ticket-{{ticket.id}}"
  ></div>
</div>
<div *ngFor="let ticket of inProgessTickets"
     [dragula]="'ticketsBag'" [dragulaModel]="inProgessTickets">
  <div ticket-list-item
       [ticket]="ticket"
       id="ticket-{{ticket.id}}"
  ></div>
</div>
`

Did you found a solution?

**Comment by stefanmeschke** [comment]
I figured out everything works well, when I add the css to my project.
`"../node_modules/ng2-dragula/demo/assets/css/dragula.min.css"`

**Comment by maxvanloosbroek** [comment]
Good to hear, sorry for the late reply. In my case I believe the ionic elements were messing things up. Probably the styling attached to them. I used regular divs instead.

**Comment by Helison** [comment]
Where I put the css? @stefanmeschke

**Comment by stefanmeschke** [comment]
@Helison I put it into the `.angular-cli.json` file or you can `import` it in your component `import 'ng2-dragula/demo/assets/css/dragula.min.css'`

**Comment by Helison** [comment]
My project don't  the file **.angular-cli.json**
![image](https://user-images.githubusercontent.com/5553539/40500995-fa82f76c-5f5c-11e8-9b92-a9e34a1c7119.png)

End if I do in component does not work
![image](https://user-images.githubusercontent.com/5553539/40501158-6dc19a6c-5f5d-11e8-8606-39467fd64a93.png)

Could you share your example @stefanmeschke ?
