### ISSUE TITLE
dropModel does not work among differents components

### ISSUE THREAD

**Issue by xLama** [valor-software/ng2-dragula#423]
- Module imported in App (top of App)
- Two components that belong to another one. (B and C. They belong to A)
- Same bag.
- I want to  drag and drop from B to C.
- C has dragulaModel.
- Drag and drop between them works nice but dropModel event does not fire, so I cant move data.

Angular 2.0.0 (final)
ng2-dragula 1.21
dragula 3.7.2

**Comment by GitHubish** [comment]
same problem :(

**Comment by xLama** [comment]
Be sure you have dragulaModel in both components. It solved my problem.

**Comment by GitHubish** [comment]
From my side it works. But sometimes my component raises an error because the model is ultimately not updated when onDropModel ... I do not know why.

**Comment by michaelyuen** [comment]
This is a demo I put together for just this use case: https://github.com/michaelyuen/angular-2-drag-n-drop
