### ISSUE TITLE
How to prevent drag on certain items in Angular ngFor

### ISSUE THREAD

**Issue by kildareflare** [valor-software/ng2-dragula#433]
I have two collections rendered in separate panels that share the same container (bag).
Each item in the collections is itself a component.
I would like to be able disable some of the items, based on their status. I.e. prevent them from being dragged. Ideally, the cursor would update to reflect this.
Is there an easy way to do this built into ng2-dragula?

**EDIT:** 
For now I am achieving this by adding the following class to each element that should not be dragged.

 `.no-drag {
 pointer-events: none 
}`

**Comment by SimonErich** [comment]
I actually need the same thing.
pointer-events none is sadly not an option, since the button should still be clickable.

In my case I have an image gallery, that should be sortable, but there is also button in that list to add new images. And I don't want that button to be sortable.

Any news on this yet?

**Comment by scopsy** [comment]
Try adding this snippet: 

```
constructor(private dragulaService: DragulaService) {
        dragulaService.setOptions('your-bag-name', {
            moves: (el, source, handle, sibling) => !el.classList.contains('no-drag')
        });
    }
```

And then simply add the `no-drag` class to items you don't want to drag.

**Comment by cormacrelf** [comment]
@scopsy's solution is the canonical dragula way of doing this, and works very well.

**Comment by cormacrelf** [comment]
And @SimonErich probably an easier solution would be to move the button out of the dragula container. Plus, extra elements clogging up your dragula containers, though they may not be directly draggable, can end up out of order if you drag another element over them. The button at the end of the sortable list would be second last if you moved something past it. The only good solution is not to have anything else in there.
