### ISSUE TITLE
add support for AoT

### ISSUE THREAD

**Issue by vdclouis** [valor-software/ng2-dragula#444]
using
- `"angular-cli": "1.0.0-beta.17"`
- `"dragula": "3.7.2"`
- `"ng2-dragula": "1.2.1"`

I get the following error:

```bash
Unexpected value 'DragulaModule' imported by the module 'FooModule'
```

**Comment by audan2009** [comment]
Looks similar

https://github.com/valor-software/ng2-dragula/issues/443

**Comment by mayconjcm** [comment]
@valorkin , can we close? Similar and resolved issue.

**Comment by valorkin** [comment]
Yep
