### ISSUE TITLE
Incompatibility with angular 2.0.2

### ISSUE THREAD

**Issue by ht89** [valor-software/ng2-dragula#446]
Hi guys, 
I have these problems. Please help. Thank you.
npm WARN ng2-dragula@1.2.1 requires a peer of @angular/common@2.0.0 but none was installed.
npm WARN ng2-dragula@1.2.1 requires a peer of @angular/core@2.0.0 but none was installed.
npm WARN ng2-dragula@1.2.1 requires a peer of @angular/compiler@2.0.0 but none was installed.
npm WARN ng2-dragula@1.2.1 requires a peer of @angular/forms@2.0.0 but none was installed.

**Comment by thejoecode** [comment]
Trying to install with @angular 2.1 and running into the same issue.

**Comment by amabdelmongy** [comment]
The ng2-dragula is not working with release version . 

Please give us road map when ng2-dragula will work fine with angular JS version 2.1

**Comment by ht89** [comment]
Thanks for sharing your thoughts, guys. The only way I use that works is to use angular 2.0.0 for now.

**Comment by mayconjcm** [comment]
ng2-dragula is using 2.1.0, so we can close this issue, okie? @valorkin
