### ISSUE TITLE
Horizontal containers wrong insert position

### ISSUE THREAD

**Issue by Haewk** [valor-software/ng2-dragula#447]
All of the examples seem to be using vertical containers. I am trying to drag and drop between horizontal containers and frequently the insert position is incorrect. 

Sometimes dragging the element to the end of the target collection will highlight the first position and if you keep dragging it around then sometimes it would highlight the correct position and other times it seems to get stuck at the start or stuck at the back. 

Can anyone confirm they are seeing the same behavior? Otherwise I can try setting it up in a codepen/fiddle.

**Comment by lazar-vuckovic** [comment]
+1
would like to use horizontal containers as well

**Comment by AmirTugi** [comment]
Happens to me too.
This renders the dragula unusable

**Comment by doender** [comment]
+1

**Comment by fpmk** [comment]
I'm getting same problem. Any fix?

**Comment by cormacrelf** [comment]
Uh. People! Dragula is perfectly capable of doing horizontal collections. Set the options on the drake, refer to the README on how to do that, and refer to Dragula's documentationon ehat they options are. Your one is `{ direction: 'horizontal' }`.

**Comment by cormacrelf** [comment]
For future reference, googling 'Dragula horizontal' will get you a long way in situations like this.

**Comment by zxc19890923** [comment]
我也遇到这个问题 请问您解决了吗
