### ISSUE TITLE
Separated onDropModel listeners?

### ISSUE THREAD

**Issue by BojanKogoj** [valor-software/ng2-dragula#449]
I need to have several different drag and drops. The problem is, `onDropModel` doesn't listen to a specific bag or a model (that I know of), and will fire for all. That of course leads to many issues. Is there a way I can tell which bag to listen to? 
It's impossible for me to use the same onDropModel because they are in different Components with completely different functionality, and all three of them can be displayed at the same time.

**Comment by BojanKogoj** [comment]
No ideas? So far I only managed to block wrong bag to effect onDropModel by checking which bag it is
```TypeScript
private onDropModel(args: any): void {
  let [el, target, source] = args;

  if (target.attributes.getNamedItem('ng-reflect-bag').value !== 'my-bag')
     return;

  // Do something
}
```

**Comment by BojanKogoj** [comment]
Do **NOT** use the solution above. It works on development, but on production there is no ng-reflect!

Instead, add `data-bag` (or change name if you wish) like this
`<div [dragula]='"my-bag"' [dragulaModel]='myModel' data-bag="my-bag">`

and check with the following:
```
if (target.attributes.getNamedItem('data-bag').value !== 'my-bag')
     return;
```

**Comment by cormacrelf** [comment]
Well, firstly, all events come with a bag name that your copy/pasting has ignored: args[0].

Secondly, that solution sucks, so check out the new events in v2 when it lands.
