### ISSUE TITLE
ran npm install on angular-seed, getting unmet peer dependency error

### ISSUE THREAD

**Issue by VinishaDsouza** [valor-software/ng2-dragula#450]
I'm using this angular seed (Link Below)
https://github.com/mgechev/angular-seed,
when I run npm install, I get these warnings, any advice how to fix it?

+-- UNMET PEER DEPENDENCY @angular/common@2.1.0
+-- UNMET PEER DEPENDENCY @angular/compiler@2.1.0
+-- UNMET PEER DEPENDENCY @angular/core@2.1.0
+-- UNMET PEER DEPENDENCY @angular/forms@2.1.0
+-- dragula@3.7.2
| +-- contra@1.9.4
| | +-- atoa@1.0.0
| | `-- ticky@1.0.1
|`-- crossvent@1.5.4
|   `-- custom-event@1.0.0
`-- ng2-dragula@1.2.1

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN ng2-dragula@1.2.1 requires a peer of @angular/common@2.0.0 but none was installed.
npm WARN ng2-dragula@1.2.1 requires a peer of @angular/core@2.0.0 but none was installed.
npm WARN ng2-dragula@1.2.1 requires a peer of @angular/compiler@2.0.0 but none was installed.
npm WARN ng2-dragula@1.2.1 requires a peer of @angular/forms@2.0.0 but none was installed.

**Comment by ps-chill** [comment]
I believe this problem is related to this: #425
