### ISSUE TITLE
Drag & Drop anywhere on the screen

### ISSUE THREAD

**Issue by theunreal** [valor-software/ng2-dragula#452]
Is it possible to drag & drop elements anywhere on the screen (within the window) and get the X & Y position of the element?

**Comment by sireneweb** [comment]
you can get X & Y with windows or class element or maybe you can check ng2drag where you can see in directive, they use mouse position

**Comment by cormacrelf** [comment]
No.

**Comment by elrafael** [comment]
```javascript
// consider constructor(private dragula: DragulaService).....

this.dragula.drag().subscribe(val => {
  document.ontouchend = (e) => {
    clientX = e.changedTouches[0].clientX;
    clientY = e.changedTouches[0].clientY;
  }
});
```
