### ISSUE TITLE
make aot compatible version available in npm

### ISSUE THREAD

**Issue by fcrocce** [valor-software/ng2-dragula#455]
Hi!
Could you please make the last version available in npm?
Currently, when I run npm install ng2-dragula@latest I get the 1.2.1 version. 

Thanks! 
I will open another issue regarding problems trying to use the last version

**Comment by borislemke** [comment]
v1.2.2 has been available for over 20 days. Did the author forget to update the npm repo? 😅 
Waiting for this as well

**Comment by borislemke** [comment]
@fcrocce try `npm i ng2-dragula@beta` temporary fix until npm package updated
