### ISSUE TITLE
Use app with AOT compile error

### ISSUE THREAD

**Issue by sdeuvarow** [valor-software/ng2-dragula#456]
Hi, I'm using ng2-dragula v1.2.2-0. When I run:

`\node_modules\.bin>ngc -p ../../src`

I get

```
....\workspaceFrontend\node_modules\.bin>ngc -p ../../src
Error: Error at ..../workspaceFrontend/node_modules/ng2-dragula/components/dragula.class.ts:1:30: Cannot find module 'dragula'.
    at check (....\workspaceFrontend\node_modules\@angular\tsc-wrapped\src\tsc.js:31:15)
    at Tsc.typeCheck (....\workspaceFrontend\node_modules\@angular\tsc-wrapped\src\tsc.js:86:9)
    at ....\workspaceFrontend\node_modules\@angular\tsc-wrapped\src\main.js:33:23
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
Compilation failed
```

I think it's missing the ng2-dragula module file, am I rigth?
thanks!

**Comment by borislemke** [comment]
@sdeuvarow How did you install v1.2.2?

**Comment by sdeuvarow** [comment]
Hi, I had to download from GIT, and compile the repo, and then replace the files in the node_modules folder, because it isn't available from npm.

**Comment by borislemke** [comment]
@sdeuvarow I tried this as well and got the same error. The metadata of ng2-dragula has been added since over 20 days ago. Maybe the author forgot to publish the updated package? 😓 

@valorkin did you?

**Comment by valorkin** [comment]
npm install ...@beta

**Comment by valorkin** [comment]
Should help

**Comment by borislemke** [comment]
Thanks! Works like a charm 👀  @sdeuvarow
