### ISSUE TITLE
Change peer-dependency to @angular 2.1.0

### ISSUE THREAD

**Issue by arrowman53** [valor-software/ng2-dragula#459]
Current version 1.2.1 has a peer dependency to 
* @angular/compiler@2.0.0
* @angular/core@2.0.0
* @angular/forms@2.0.0

Could you please upgrade this to 2.1.0? Or get rid of the peer dependency all together?

**Comment by Appius** [comment]
Version is updated in 1.2.2-0 ([link](https://github.com/valor-software/ng2-dragula/blob/v1.2.2-0/package.json#L55)). Just need to wait 1.2.2 release.

**Comment by hntan** [comment]
Hi guys, nearly a month and nothing new?

**Comment by thielCole** [comment]
Definitely waiting on this!

**Comment by tsu1980** [comment]
There is beta version `1.2.2-0`. It is a workaround until publish new latest version.

ref #464
