### ISSUE TITLE
Disable/enable bag ?

### ISSUE THREAD

**Issue by dany-sh** [valor-software/ng2-dragula#460]
Hi, I'm stuck with an issue in my code...

I can't disable and re-enable the bag.

this is how I disable the drag bag
`   dragOff() {
        const bag: any = this.dragulaService.find('gridBag');
        console.log('bag ' + JSON.stringify(bag));
        if (bag !== undefined) {
            this.dragulaService.destroy('gridBag');
        }`

How to re enable a bag ?

**Comment by arkoak** [comment]
well, one way is to use a new instance of drake to initialize as below, (did not use the directlve at all)

`let drake = dragula({
              containers: [document.getElementById(elementId)]
});
this.dragulaService.add("yourdynamicbagname", this.drake);`


However it requires dragula to be imported separately, I believe ng2-dragula should give a way to iniitate a drake without doing so, would be just a few more lines of code.

**Comment by dany-sh** [comment]
I found how to do it :
`       this.dragulaService.setOptions('gridBag', {});
        this.dragulaService.find('gridBag').drake.containers.push(document.getElementById('dragBag'));
        this.dragulaService.find('gridBag').drake.models = [this.images];
`

Thanks :)
