### ISSUE TITLE
Maybe a bug

### ISSUE THREAD

**Issue by keyiis** [valor-software/ng2-dragula#462]
In source **dragula.provider.ts**
```
drake.on('drop', (dropElm: HTMLElement, target: HTMLElement, source: HTMLElement) => {
     ......
        target.removeChild(dropElm); // element must be removed for ngFor to apply correctly
      }
      this.dropModel.emit([name, dropElm, target, source]);
    });
```
issuse sence:
1、when i set copy:true
2、i moving a element from contianerA to contianerA.
3、i drop it after repeatedly triggered this over event.
4、below error ocurr
`Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`
5、through debug i find error placed in **dragula.provider.ts**  `target.removeChild(dropElm); `
**additional remarks:**
i find the dropElm missing  after repeatedly triggered over event. so `target.removeChild(dropElm);` excute failed.

**now i used a temporary solution:**
in **dragula.provider.ts** change 
`target.removeChild(dropElm);`
to
```
try{
          target.removeChild(dropElm);
        }catch(err){
          console.log('dropElm has removed!');
        }
```

**Comment by franbueno** [comment]
Same bug here

**Comment by shikhaBasra** [comment]
I am  getting same issue while dropping element. Please suggest the possible solution.

**Comment by chrillewoodz** [comment]
Having the same issue, any updates?

**Comment by sruthivarghese15** [comment]
I'm facing the same issue..Any updates?
