### ISSUE TITLE
Peer Dependency issue

### ISSUE THREAD

**Issue by rphovley** [valor-software/ng2-dragula#464]
I'm getting a peer dependency issue when attempting to add dragula.  I've tried to revert back to older versions of angular-cli but that didn't work either.  Other valor-software is working out of the box, like ng2-select

I'm using 
angular-cli: 1.0.0-beta.19-3
node: 6.3.1

├── UNMET PEER DEPENDENCY @angular/common@2.1.2
├── UNMET PEER DEPENDENCY @angular/compiler@2.1.2
├── UNMET PEER DEPENDENCY @angular/core@2.1.2
├── UNMET PEER DEPENDENCY @angular/forms@2.1.2
├── dragula@3.7.2 
└── ng2-dragula@1.2.1 

npm WARN ng2-dragula@1.2.1 requires a peer of @angular/common@2.0.0 but none was installed.
npm WARN ng2-dragula@1.2.1 requires a peer of @angular/core@2.0.0 but none was installed.
npm WARN ng2-dragula@1.2.1 requires a peer of @angular/compiler@2.0.0 but none was installed.
npm WARN ng2-dragula@1.2.1 requires a peer of @angular/forms@2.0.0 but none was installed.

**Comment by kapill-clarion** [comment]
I am getting the same issue as well.

**Comment by andy2708** [comment]
Also getting the same

**Comment by thielCole** [comment]
+1, I am trying to use this with an ionic project and they have hard angular dependencies on 2.1.1

**Comment by Myqilixiang** [comment]
get the same issue when  i try to use ng2-data-table

**Comment by Natanael1234** [comment]
Same problem here using latest Ionic 2.

**Comment by Gajendrasinh** [comment]
how to developed dragula in app
