### ISSUE TITLE
Free Move

### ISSUE THREAD

**Issue by adelemam** [valor-software/ng2-dragula#465]
Hi there , 
I need a way to have some kind of containers where i can free move items ( like canvas) , beside the normal sorting containers already done, 

is there is  simple way to accomplish this?

**Comment by sireneweb** [comment]
i think you need add first bag on your main body with class

**Comment by adelemam** [comment]
what you mean exactly, can you explain in steps please?

**Comment by cormacrelf** [comment]
No.
