### ISSUE TITLE
TypeScript error from accessing private variable bags in DragulaService

### ISSUE THREAD

**Issue by Sako73** [valor-software/ng2-dragula#469]
I am writing an AngularJS2 application using ng2-dragula.  It is working, but in order to prevent the creation of the new DOM element on drop, I do the following:

```
this.dragulaService.drop.subscribe((v) => {
            // Prevent the creation of the new DOM element, since the ngFor will add it anyway.
            this.dragulaService.bags[0].drake.cancel(true);
            // Other code here...
        });
```

I am getting a TypeScript error that "bags" is a private property.  Since this is private I assume this is not the correct way to cancel the drop creation.  Is there a better way to accomplish this?

Thanks.

**Comment by sireneweb** [comment]
have you try public ?

**Comment by cormacrelf** [comment]
Use DragulaService.find(...).
