### ISSUE TITLE
IE11 not dropping after drag

### ISSUE THREAD

**Issue by unsafecode** [valor-software/ng2-dragula#475]
I'm currently using `v.1.2.2-0` and I've been experiencing issues with **IE11 only**: whenever I begin to drag items from a list, I can't drop releasing the left mouse button, but I need to click again.

This doesn't happen with Chrome.

I'm basically using this example https://github.com/valor-software/ng2-dragula#dragulamodel

**Comment by natablbt** [comment]
I am using v.1.2.1, IE11 and have the same issue.
Any ideas how to solve it?
What kind of information do you need to reproduce it?

**Comment by unsafecode** [comment]
AFAIK, I was able to fix this by changing styling my HTML and styles. In my case IE11 could not handle a `<a>` element with large padding inside a `<li>` (essentially a list of clickable items).

This anchor looks like not to be draggable, while the list item is handled correctly.

**Comment by natablbt** [comment]
Thanks for hint. I have the same structure, <li> element with <a> inside.
I could solve it with

**Comment by Owenzh** [comment]
unselectable=on  this hack for IE, it works fine! 
Thanks.
