### ISSUE TITLE
Call to Node module failed with error: ReferenceError: document is not defined

### ISSUE THREAD

**Issue by aaltotsky** [valor-software/ng2-dragula#477]
We are using the ng2-dragula in our Angular2 project with Universal (server pre-rendering). We are getting the 

> Exception: Call to Node module failed with error: ReferenceError: document is not defined 
error as soon as we declared DragulaModule in the import.

Do you have any workaround for universal and  the "document is not defined"?

Thanks,

**Comment by Moalpima** [comment]
I have the same problem. Does anyone has an idea?

**Comment by suisgrand** [comment]
did any of you manage to fix that by any chance?

**Comment by cormacrelf** [comment]
#737
