### ISSUE TITLE
model not updating in correct order

### ISSUE THREAD

**Issue by Dooblr** [valor-software/ng2-dragula#480]
After a drop, my models get updated, but in the wrong order. It looks like it's inserting the dropped one in the correct place, but pushes the others down the array rather than getting their new location.

TL;DR: Has anyone implemented numbered reordering of objects in a database after a drop?

stackoverflow question if you fancy:

http://stackoverflow.com/questions/41007356/angular-2-dragula-model-updating-incorrectly

**Comment by marcalj** [comment]
Duplicated of #506
