### ISSUE TITLE
Dragula with md-grid-list

### ISSUE THREAD

**Issue by AmirTugi** [valor-software/ng2-dragula#481]
I can't seem to make the dragging work with angular2/material's `md-grid-list`.

Here's the code:

```
 <md-grid-list cols="4" rowHeight="5:2" [dragula]="'picture-bag'" [dragulaModel]="item.pictures">
    <md-grid-tile colspan="1" rowspan="3" *ngFor="let picture of item.pictures; let index=index">
        <item-picture [(picture)]="item.pictures[index]"></item-picture>
    </md-grid-tile>
</md-grid-list>
```

What happens is that I can't even seem to drag any tile.
This is caused because in reality, `md-grid-list` has a nested `div` just between `md-grid-list` and -md-grid-tile'.
How can I overcome this, and let's say, decide which offspring elements are to be draggable within the container?

**Comment by arat3091** [comment]
AmirTugi , Did you find the fix for your problem

**Comment by AmirTugi** [comment]
No, I eventually switched to ng2-dnd, which worked for me

**Comment by DanielNetzer** [comment]
This should be a high priority issue since at the moment this entire library is not compatible with angular.material.

**Comment by mgurnani** [comment]
+1

**Comment by cormacrelf** [comment]
If there's a div in between, then ng2-dragula won't work. Recall that this is a bare-bones wrapper around Dragula, which deals only with the DOM and direct children. This issue and the hydra of near-identical ones cannot be fixed without scrapping Dragula entirely.

Although... I got sick of limitations like this and wrote [`angular-skyhook`](https://cormacrelf.github.io/angular-skyhook/). You will note that it is quite low-level, so `ng2-dnd` might be helpful, although it appears not to be maintained at the moment.
