### ISSUE TITLE
How to disable moving some element

### ISSUE THREAD

**Issue by vitaly87** [valor-software/ng2-dragula#492]
Hi,
How can I disable moving some element like if this group name on the top?

**Comment by marcalj** [comment]
You can see Dragula options, there's a ```moves``` config option to test for elements. For example:

```ts
constructor(private dragulaService: DragulaService) {
        dragulaService.setOptions('test-492', {
            moves: (el, source, handle, sibling) => !el.classList.contains('ignore-item')
        });
    }
```

```html
<ul [dragula]='"test-492"'>
        <li class="ignore-item">drag ignored</li>
        <li>item 1</li>
        <li>item 2</li>
    </ul>
```

**Comment by eagor** [comment]
Doesn't work, as `setOptions()` seems to create a new bag.

Following your example, I'm getting this error: 
        `Bag named: "columns" already exists.`

**Comment by marcalj** [comment]
Add a destroy call on `ngOnDestroy`:

```ts
    ngOnDestroy():void {
        if (!!this.dragulaService.find('test-492')) {
            this.dragulaService.destroy('test-492');
        }
    }
```

If using ```ngUpgrade``` module with NG1 router you should check first if already exists before setting config:

```ts
        if (!!this.dragulaService.find('test-492')) {
            this.dragulaService.destroy('test-492');
        }

        this.dragulaService.setOptions('test-492', {
            ...
        });
```

**Comment by AKAust** [comment]
I have the same issue. I have some target areas on the right hand side each of them has a title with a class of non mover and i am using
`function (el, source, handle, sibling)
        {
          if (el.classList.contains('nonMover'))
            {
                return false;
            }
          else
          {
            return true;
          }
        }`
This is working fine to prevent these items being dragged. This however does not stop me dropping an item above it essentialy moving it to index 1 instead of 0 which I am trying to prevent. Does anyone know a way i can prevent this being moved at all?

**Comment by bincTW** [comment]
Setting item's css to _pointer-events: none_ also works for me.
