### ISSUE TITLE
Error: DragulaModule is not an NgModule

### ISSUE THREAD

**Issue by LucasReSilva** [valor-software/ng2-dragula#493]
I'm heaving this error with angular cli 1.0.0-beta.22-1

**Comment by deugene** [comment]
Have this error too. If build project without importing DragulaModule, and then add it all works fine.

**Comment by montella1507** [comment]
Well you have to use version  1.2.2-0 because it is built with Angular AOT Metadata.. it worked yesterday.. but now (after changes made 3hours ago) it doesnt work even with "aot compliant version - 1.2.2-0"

**Comment by sirhcybe** [comment]
I got this too but I just upgraded to version 1.3 and everything worked.
