### ISSUE TITLE
Rewrite NG1-dragula to NG2 instead of wrapping it

### ISSUE THREAD

**Issue by peterps-health** [valor-software/ng2-dragula#5]
Rewrite the current NG1-dragula to the NG2 standard.
Make it totally NG2 app.

**Comment by valorkin** [comment]
@peterps-health may be you want to propose it here https://github.com/bevacqua/angular-dragula
or I did not understood you

**Comment by peterps-health** [comment]
@valorkin raising it there would not be totally correct as dragula 1 does not talk about building anything in angular 2. Whilst, here it does !

p.s. thank you for your work on the port !

**Comment by valorkin** [comment]
@peterps-health not me, thanks to @NathanWalker :)

**Comment by NathanWalker** [comment]
:+1:
