### ISSUE TITLE
Filter on dragula collection

### ISSUE THREAD

**Issue by snarum** [valor-software/ng2-dragula#509]
I have a list of divs that the use can select from. My problem is that this list is quite large, so I though I should make a filter box so that the user can filter the items and make the set smaller.  The filter is an input field and a Pipe.

so the .ts file has these elements:

```
private fromCollection:Array<MyEntity> = new Array<MyEntity>();
private toCollection:Array<MyEntity> = new Array<MyEntity>();
private filterString : string;
```
the pipe looks like this
```
import {Pipe, Injectable, PipeTransform} from '@angular/core';
import {Fond} from '../Models/reportInput';
@Pipe({
    name: 'entityFilter',
    pure: false
})
@Injectable()
export class EntityFilterPipe implements PipeTransform {
    transform(items: MyEntity[], args: string): any {
        if( args == undefined || args.length<2)
            return items;
        return items.filter(item => item.name.toLowerCase().indexOf(args.toLowerCase()) !== -1 || item.type.toLowerCase().indexOf(args.toLowerCase()) !== -1 );
    }
}
```
and my html looks something like this:
```
<div [dragula]='"first-bag"' class="" [dragulaModel]='fromCollection'>
    <div *ngFor='let entity of (fromCollection | entityFilter:filterString)'>{{entity.name}} </div>
</div>
<div [dragula]='"first-bag"' class="collection" [dragulaModel]='toCollection'>
    <div class="collection-item" *ngFor='let entity of (toCollection)'>
</div>
```

My problem is that when the collection is filtered, the drag and drop is completely broken. Wrong elements are moved, and sometimes lots of the elements in fromCollection are deleted.

Is there a better way to do this? Or can I fix this in some way?

Any comments are appreciated.

**Comment by snarum** [comment]
I solved this by removing the filter and instead using the style display:none for the div's that didn't match my filter string.

**Comment by calebeaires** [comment]
@snarum Can you share with us part os code you used to make display:nome work with pipe. I have created one pipe that filter by search, but is does not work with dragula module.

**Comment by ipodjms** [comment]
I make a shot example in stackblitz, but, some settings of dragula, dont work.

You can use filter code, i test it in separeted project and work fine.

[https://stackblitz.com/edit/ng2-dragula-base-search]

**Comment by ipodjms** [comment]
I make a short example in stackblitz, but, some settings of dragula, dont work (in stackblitz).

You can use filter code. I test it in separeted project and work fine.

[https://stackblitz.com/edit/ng2-dragula-base-search](https://stackblitz.com/edit/ng2-dragula-base-search)
