### ISSUE TITLE
Is the 'animation' option supported?

### ISSUE THREAD

**Issue by BBaysinger** [valor-software/ng2-dragula#511]
On this page: [https://www.npmjs.com/package/dragula-with-animation](https://www.npmjs.com/package/dragula-with-animation), it appears that animation is supported with the `animation` option, but I searched and I'm not seeing this anywhere in the ng-dragula package. Of course I tried it first, and it didn't do anything, so I did some more investigation, and not seeing support of this feature.

**Comment by cormacrelf** [comment]
This is not the same package.
