### ISSUE TITLE
'DragulaModule' is not exported by node_modules\ng2-dragula\index.js

### ISSUE THREAD

**Issue by Ibrahim-Islam** [valor-software/ng2-dragula#530]
@NathanWalker @valorkin 

```
'DragulaModule' is not exported by node_modules\ng2-dragula\index.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
app\app.module.js (13:9)
11: import { BrowserModule } from '@angular/platform-browser';
12: import { AppComponent } from './app.component';
13: import { DragulaModule } from 'ng2-dragula';
             ^
14: import { FileUploadModule } from "ng2-file-upload";
```

rollup.config.js
```
import rollup      from 'rollup'
import nodeResolve from 'rollup-plugin-node-resolve'
import commonjs    from 'rollup-plugin-commonjs';
import uglify      from 'rollup-plugin-uglify';

export default {
  entry: 'app/main.js',
  dest: 'dist/build.js',
  sourceMap: false,
  format: 'iife',
  plugins: [
      nodeResolve({jsnext: true, module: true}),
      commonjs({
        include: 'node_modules/rxjs/**',
      }),
      uglify()
  ]
}
```
Using Rollup for tree-shaking and build gives me the above error after successfully generating files with aot. Any suggestion is highly appreciated.

**Comment by alexlovato303** [comment]
@valorkin same issue as above

**Comment by valorkin** [comment]
Exports should be named, but I don't have a time until Friday to fix it

**Comment by kgiroux** [comment]
@valorkin do you have a release ready for this fix ? 

Sincerely,

**Comment by HitomiTenshi** [comment]
Hi, I'd also be interested in a release fixing this issue. 👍

**Comment by gomesNazareth** [comment]
This same issue is there on ng2-file-upload too 
 Error: 'FileUploadModule' is not exported by node_modules/ng2-file-upload/ng2-file-upload.js

**Comment by kgiroux** [comment]
No new about that ?

**Comment by PleasantD** [comment]
When will this be released? Need this for production.

**Comment by siddharthashw** [comment]
Getting the same issue in 1.5.0 version.

Even though I have used custom named exports
         
    commonjs({
            include: 'node_modules/rxjs/**',
            namedExports: {
                'node_modules/ng2-dragula/ng2-dragula.js': ['DragulaModule', 'DragulaService']
            }
        }),

Need help
Thanks in advance

**Comment by mityaz** [comment]
Same issues as above.

**Comment by egniteall** [comment]
same issue here ng2 dragula fails my Angular 7 built is there any option to fix this


ERROR in node_modules/ng2-dragula/dist/MockDrake.d.ts(41,5): error TS2416: Property 'on' in type 'MockDrake' is not assignable to the same property in base type 'DrakeWithModels'.
  Type '(event: string, callback: Function) => void' is not assignable to type '(events: string, callback: Function) => Drake'.
    Type 'void' is not assignable to type 'Drake'.
src/app/theme/extension/event-calendar/event-calendar.module.ts(17,5): error TS2554: Expected 1-2 arguments, but got 0.

**Comment by PRR24** [comment]
kixarinum, siddharthashw, did you manage to solve it (with 1.5)?
