### ISSUE TITLE
dragulaOptions attribute not working

### ISSUE THREAD

**Issue by nvernooy** [valor-software/ng2-dragula#536]
Following the readme and due to my needs I tried to set the options on the drake using an options object in the html.

I declare my options object in my component:
```
    options: any = {
        removeOnSpill: false,
        revertOnSpill: true,
        accepts: (el, target, source, sibling): boolean => {
            return (source.dataset.parent == target.dataset.parent);
        },
    }
```

And insert it in the html:

```
<div *ngFor="let content of contents"
    [attr.data-parent]="parent.id"
    [dragula]='"childContent" + parent.id' 
    [dragulaModel]='contents' 
    [dragulaOptions]="options">
</div>
```
But then I get this error:

> Unhandled Promise rejection: Template parse errors:
> Can't bind to 'dragulaOptions' since it isn't a known property of 'div'. ("nt.item_id"
>     [dragula]='"sectionContent" + section.id' [dragulaModel]='orderedContent' [ERROR ->][dragulaOptions]="options">

What is happening here?

**Comment by lossless1** [comment]
+1

**Comment by cormacrelf** [comment]
Maybe use latest ng2-dragula?

**Comment by cormacrelf** [comment]
dragulaOptions has been removed in v2
