### ISSUE TITLE
When using a filtered ngFor the DOM element index differs from model index

### ISSUE THREAD

**Issue by TheFirstAvenger** [valor-software/ng2-dragula#539]
This exact issue from angularjs-dragula exists in ng2-dragula:
https://github.com/bevacqua/angularjs-dragula/issues/98
If you use a filtered ngFor, the index gets confused, and the incorrect item is dragged.

**Comment by Brookke** [comment]
Having the same problem

**Comment by cormacrelf** [comment]
Thing of it less as a bug. You're just not using it correctly. Don't filter in ngFor, obviously that will mess things up given how dragula has to sync DOM changes back to mutable arrays. Make sure the exact same array is used for ngFor and dragulaModel. If that means doing your filtering somewhere else, I'm sure you'll find a way.

**Comment by Denfie** [comment]
I found a possible easy way to do this.

Little change here: **dragula.provider.ts**
```
drake.on('drag', (el: any, source: any) => {
    dragElm = el;
    dragIndex = this.domIndexOf(el, source);
});
```

---> to this one:
```
drake.on('drag', (el: any, source: any) => {
    dragElm = el;
    dragIndex = (el.getAttribute('filter-index')) ? +el.getAttribute('filter-index') : this.domIndexOf(el, source);
});
```
**HTML**:
```
<div [dragula]='dragType' [dragulaModel]='users' [attr.id]="id">
  <div  *ngFor="let item of arraylist" [attr.filter-index]="arraylist.indexOf(item)">
    <!-- HTML here -->
  </div>
</div>
```

Works for me perfectly... 🍨

**Comment by KroanNL** [comment]
Any chance of getting this change into the main fork?
