### ISSUE TITLE
Unsubscribing from drop events causes ObjectUnsubscribedError error

### ISSUE THREAD

**Issue by nitramau** [valor-software/ng2-dragula#547]
Hi All

I've just started using Dragula with Angular 2. I've copied some of your example code to subscribe to the "Drop" events like this:
  constructor(private dragulaService: DragulaService) {
    .....
    dragulaService.drop.subscribe((value) => {
        this.onDropSuccess();
    });
  }

This works well, though, when I unsubscribe in ngOnDestroy(), I noticed that if I open up my component again, I get an error:- ObjectUnsubscribedError: object unsubscribed
This is my unsubscribe code:
  ngOnDestroy() {
    this.dragulaService.drop.unsubscribe();
  }

If I don't unsubscribe, then everything works without an error, but I am concerned about the possibility of a memory leak, in not unsubscribing.

Any input would be greatly appreciated.

Thanks so much.

**Comment by Slaschnikoff** [comment]
Did you ever find a solution? I'm having the same issue at the moment.

**Comment by Slaschnikoff** [comment]
Got it, if you add 'dropSubscription' as a class property and then change:

dragulaService.drop.subscribe((value) => {
this.onDropSuccess();
});

to 

this.dropSubscription = dragulaService.drop.subscribe((value) => {
this.onDropSuccess();
});

, later you can do this.dropSubscription.unsubscribe() and it should work.

**Comment by nitramau** [comment]
My solution ended up being similar to yours. I didn't do any debugging as to whether it did actually free up all of the resources, but I think it will.

**Comment by jfx** [comment]
Same issue, thanks for the solution

**Comment by cormacrelf** [comment]
Anyone stumbling upon this might find my answer here https://github.com/valor-software/ng2-dragula/issues/714#issuecomment-302947373 helpful.
