### ISSUE TITLE
ng2-dragula seems incompatible with Angular 2.4.5

### ISSUE THREAD

**Issue by vega3000** [valor-software/ng2-dragula#548]
npm WARN ng2-dragula@1.3.0 requires a peer of @angular/compiler@2.4.3 but none was installed.
npm WARN ng2-dragula@1.3.0 requires a peer of @angular/forms@2.4.3 but none was installed.

**Comment by HeitorFonseca** [comment]
same issue

**Comment by ferreirocm** [comment]
It seems like they have strong dependency on the 2.4.3 version of both packages or forgot to change it.
The following dependencies appears inside the ng2-dragula package.json:
  "peerDependencies": {
    "@angular/common": "^2.3.0",
    "@angular/core": "^2.3.0",
    **"@angular/compiler": "2.4.3",
    "@angular/forms": "2.4.3"**
  },

**Comment by dbogdantech101** [comment]
Super annoying, really could use to be updated - especially if there aren't any breaking changes to newer angular versions

**Comment by hosseinAga** [comment]
I have the same problem.

**Comment by abuiliazeed** [comment]
same problem!!!!

**Comment by ngKisor** [comment]
i am facing same how to solve this?

**Comment by NeuralChris** [comment]
Same problem here using Angular 2.4.6.

**Comment by xatzistnr** [comment]
ng2-dragula@1.3.0 requires a peer of @angular/compiler@2.4.3 but none was installed.
npm WARN ng2-dragula@1.3.0 requires a peer of @angular/forms@2.4.3 but none was installed.

**Comment by lucasinoue** [comment]
Same issue

**Comment by vaidd4** [comment]
It isn't a compatibility problem but a pear dependency problem.
It's just a warning and may be resolved in next version
See https://github.com/valor-software/ng2-dragula/issues/636#issuecomment-299962384
