### ISSUE TITLE
Class ex-moved wrongly set

### ISSUE THREAD

**Issue by DblK** [valor-software/ng2-dragula#550]
The class "ex-moved" isn't set on existing element with class.

Steps:
1) Just set a class (for example "dblk") to one of the item you want to move (bellow [dragula='first-bag']).
2) Drag an element
3) See that the class "ex-moved" isn't set and instead the element has the class "dblkex-moved".

**Comment by cormacrelf** [comment]
The example code is correct for itself. If you want better class list manipulation, let Angular do it with [class.ex-moved]="foo". Or install the `classlist` package.
