### ISSUE TITLE
Events on a group bag

### ISSUE THREAD

**Issue by Gillardo** [valor-software/ng2-dragula#558]
Is there any way to add an event to a particular group bag?  Can this not be done by using some sort of tag

Eg
```
<div [dragula]="'group-bag'" [dragulaModel]="myCollection" (onDrop)="onDrop($event)">
```
.ts
```
onDrop($event: any) {
    // handle drop event here
}
```

If i use the method in the documentation, where i bind to the dragula service, then my event is raised on all my dragula bags, when i only want the event raised on 1 bag. (The bag that is created within the component, as my components have 1 bag in each) but i have several components available on the page.

Is this possible?  Cant see anything in documentation, and would seem like a simple requirement.

**Comment by cormacrelf** [comment]
Groups and bags are different words for the exact same thing.

Also, no. V2 DragulaService events are better. See recent commits, milestone and release soon.
