### ISSUE TITLE
Nested level 

### ISSUE THREAD

**Issue by harshpatel79** [valor-software/ng2-dragula#559]
Hi,

I was trying out ng2-dragula. It looks great.

I have a question regarding this library. Here is my use case -

1. There are two containers - Container 1 and Container 2
2. Container 1 has  a nested container (Container 1.1)
3. Container 2 has fields that can be dropped (cloned) in Container 1 or Container 1.1
4. Container 1 and Container 1.1 elements should be sortable.

It looks like everything is doable with ng2-dragula but we are NOT sure how to achieve point number 3 i.e nested droppable containers.

Similar to nestable library http://dbushell.github.io/Nestable/

Is this doable with ng2-dragula? Please let me know if you have any question with my use case.

Thanks.

**Comment by harshalpatel91** [comment]
Hi,

I have achieved the above use case but have two issue which are as follow: 
1. When container is empty, new field is not inserted in it.
2. When I move the nested fields from one container to upper level container randomly getting error of  "Cannot read property 'getAttribute' of null".

Any help on above would be appreciated.

Thanks

**Comment by harshpatel79** [comment]
Hi,

I have achieved the above use case but have two issue which are as follow: 
1. When container is empty, new field is not inserted in it.
2. When I move the nested fields from one container to upper level container randomly getting error of  "Cannot read property 'getAttribute' of null".

Any help on above would be appreciated.

Thanks

**Comment by kjmohit** [comment]
@harshpatel79 , I'm stuck in the same kind of issues. can you provide me any solutions?

**Comment by rabierAmbroise** [comment]
Same issue here.

**Comment by cormacrelf** [comment]
#309.
