### ISSUE TITLE
AOT error: require is not defined

### ISSUE THREAD

**Issue by quiringk** [valor-software/ng2-dragula#569]
I am getting this error in the browser when trying to compile with AOT: (build & rollup are successful before I get this error)

```
Uncaught ReferenceError: require is not defined
    at dragula.js:3
    at main-aot.js:6
```

Any idea how to get passed this? I added require.js and spent hours trying to get requirejs bugs going away but just kept going farther and farther down the rabbit hole. (I've never used requirejs before today trying to get this to work.) What seems odd to me as that I am the only one raising this issue when lots of people are using this library and I assume are using AOT too.

PS: ng2-dragula is working fine with systemjs JIT compilation

**Comment by quiringk** [comment]
I figured it out, mistake in my rollup-config file. I had to add node_modules/dragula/** to the commonjs include section of rollup-config plugins section (also had to add atoa/, ticky/, contra/**, because dragula uses them I think.)

**Comment by irapopova** [comment]
Hi ,
I faced with the same issue today.

I added '/contra/**', './node_modules/ticky/**', './node_modules/atoa/**',  './node_modules/custom-event/**',  './node_modules/ng2-dragula/**', './node_modules/dragula/**'

Nothing works for me.
for now I still have an error in dragula.js file "**require is not defined**" in the line where '**contra/emitter**' is used.

Any ideas how to fix this??
