### ISSUE TITLE
How to read the contents of the bag

### ISSUE THREAD

**Issue by tosehee75** [valor-software/ng2-dragula#576]
Sorry for dumb question here..

I have one bag with two contains, and I want to drag from one container to the next.

I followed the example, and got that working. 

Now, I want to save the sort order and contents of the 2nd container.

How do I do that?

**Comment by tosehee75** [comment]
Anyone?

**Comment by tosehee75** [comment]
Any help is greatly appreciated.

**Comment by codyjdalton** [comment]
@valorkin I'm also wondering the best way to do this. Would it be parsing the dom?

**Comment by codyjdalton** [comment]
@tosehee75 FYI there are several ugly solutions:

1. Use the "find" method of the dragula service.
```
let myElements = dragulaService.find('first-bag').drake.containers[0];
```
2. Use the dom.
```
let myElements = Array.from(document.getElementsByClassName('some-container-class'))
```
You can read which element is which by adding an angular 2 attribute to each item in your for loop
```
<div class="some-container-class" [dragula]="first-bag">
    <div *ngFor="let item of items">
        <div [attr.data-id]="item.id"></div>
    </div>
</div>
```

Would like to hear if there is a way we are specifically meant to do it. Would be nice if the module updated the A2 model automatically but alas...

**Comment by fuerst** [comment]
Best way seems to use [dragulaModel](https://github.com/valor-software/ng2-dragula#dragulamodel). See the **Angular-specific example. Fancy some ngFor?** example at http://valor-software.com/ng2-dragula/index.html.

Unfortunately this seems partly broken in Angular 4.0.3 and ng2-dragula 1.3.1 so I currently stick to the "find" method of the dragula service as mentioned above. For my 3 "widget regions" which are simply 3 DIV's belonging to one Dragula bag this looks like this:

```
  constructor(private widgetService: WidgetService, private dragulaService: DragulaService) {
    dragulaService.drop.subscribe((value) => {
      // Get the parent container elements of the widgets.
      let regions = dragulaService.find('widgets-bag').drake.containers;
      this.moveWidget(regions);
    });
  }

  moveWidget(regions) {

    // Set weight and region of widgets to reflect new order.
    regions.forEach((column, regionIndex) => {
      // Use querySelectorAll() to get a static node list of the widgets.
      // Contrary to this getElementsByClassName() would return a live "HTMLCollection".
      // Both are no Arrays so Array.foreach() et all can not be used.
      // Converting it to an array looks like a workaround to this
      // but does also seems to change the object structure of a widget.
      let widgetsFromDOM = column.querySelectorAll('div.widget');

      // Array.map() callback to set new region and weight for widgets in the widgetList array.
      // Using a anonymous function inside a callback allows additional function parameters when
      // using the callback. See http://stackoverflow.com/a/12344111/1546181.
      let reorderWidgets = function(weight, region, wDomModule, wDomDelta) {
        return function(w) {
          // Widget from widgetList (w) does not match the widget from DOM
          // identified by wDomDelta and wDomModule.
          if (w.delta != wDomDelta || w.module != wDomModule) {
            return w;
          }

          // Set new weight and region.
          w.weight = weight + 1;
          w.region = region + 1;
          return w;
        };
      };

      // Loop through the widgets and apply the new weight and region.
      for (let weight = 0; weight < widgetsFromDOM.length; weight++) {
        let widget = widgetsFromDOM[weight];
        // Array.map() loops through all widgets from widgetList to find and set
        // their matches from widgetsFromDOM which at this point is a
        // subset of widgets belonging to only one region.
        this.widgetList.map(reorderWidgets(weight, regionIndex, widget.dataset.module, widget.dataset.delta));
      }
    });

    this.widgetService.saveWidgetList(this.widgetList);
  }
```

Some notes:

* `widget` from `widgetList` is an object containing meta data like vertical position (weight) and source of it's content (module, delta). `widgetList` will be loaded from a service and saved back to this service as soon as a widget got dragged.
* `module` and `delta` in combination are the identifier for a widget. By applying them to the widget HTML code as data attribute I can use them to identify a widget inside the `moveWidget()` method. You can use any other key instead. Just apply it to the widget HTML like `[attr.data-module]="widget.key"` or similar.

**Comment by cormacrelf** [comment]
@fuerst #670 is a non-issue. Please use dragulaModel, it's not broken.

**Comment by cormacrelf** [comment]
Also, finding the drake and accessing its `containers` property is not ugly, it's the simplest possible way. That's where they're stored.

**Comment by AlexGrafic** [comment]
Thank you @fuerst . You solved my problems with saving the order into database
