### ISSUE TITLE
How to re-initialize the container contents?

### ISSUE THREAD

**Issue by tosehee75** [valor-software/ng2-dragula#579]
I am following the example, and I got the one bag moving items with drag and drop. 

Now, I am using this along with the ng2-bootstrap and popup, and I am running into some weird issues that I am losing my hairs on.

The dragulaModel is synced and it shows up fine when the popup windows show up.

If I remove anything from 'right' bag to 'left' (removing), and then re-open the popup, it re-initializes or maintains the same state.

However, if I move anything from 'left' to 'right' (adding), then it persists the state, and subsequent re-opening doesn't show the initial state.

Second of all, I need to read the sort order and the contents of the either container so I can persist it to the database.

However, it doesn't seem like there is any example or thread answering to similar questions.

Any help is greatly appreciated. Thanks.

**Comment by tosehee75** [comment]
Any help is greatly appreciated.

**Comment by tosehee75** [comment]
Any help is greatly appreciated.

**Comment by cormacrelf** [comment]
Sorry about the lag, there's a bit of an issue backlog.

Two containers you're trying to move stuff between should have the **same bag**. It looks like you've been using two different bags, and you're running into behaviour defined by `removeOnSpill` and friends. I am not sure it's documented well enough that you should use one bag name.
