### ISSUE TITLE
This supports ng-version 2.4.7 also..?

### ISSUE THREAD

**Issue by Srinivasan756** [valor-software/ng2-dragula#588]
Hi Techies,

Can anyone tell me why it's not supporting for ng-version 2.4.7
dragula -- ng-version="2.4.3"

Please let me know someone is having any workaround.

**Comment by bouchepat** [comment]
Hello,

Any news on supporting angular versions above 2.4.3 (current is 2.4.10)? Just a quick response would be appreciated, even if not a priority... Thanks
