### ISSUE TITLE
Dragging over another container and letting go off the container removes both model visually

### ISSUE THREAD

**Issue by kamok** [valor-software/ng2-dragula#589]
When I have `removeOnSpill: true`, and I drag one model over another (same [dragula]), both of them will disappear even-though the `this.dragulaService.removeModel.subscribe` only emits one of them. 

Using the latest version of `ng2-dragula`.  Here's my template:

```
  <div class="row panel-body">
    <div *ngFor="let location of locations$ | async">
      <div class='panel panel-default'>
        <div class=panel-body [dragula]='"assignment-bag"' [dragulaModel]='usersByLocationId[location.uuid]' id="{{location.uuid}}">
          <div *ngFor="let user of usersByLocationId[location.uuid]" class="assignment" id="{{user.uuid}}">
            {{user.first_name}} {{user.last_name}}<br />
          </div>
        </div>
      </div>
    </div>
  </div>
```

Here's a gif of what's happening:
http://g.recordit.co/pa7mjpmMKQ.gif

Note, that I'm printing out the dragulaModel every 3 seconds. I'm also console logging the `this.dragulaService.removeModel.subscribe`. The `removeModel` only get's fired once. The dragulaModel only changes once too. But I'm missing 2 objects on the template.

**Comment by dylanerichards** [comment]
@kamok Noob.

**Comment by cormacrelf** [comment]
I’m closing this, but if you’re still having this issue in v2, please file another one with a StackBlitz to reproduce instead of a gif that’s just a 404 now.
