### ISSUE TITLE
Environment configuration does not contain "environmentSource" entry

### ISSUE THREAD

**Issue by karol-depka** [valor-software/ng2-dragula#591]
Hi.

```
Environment configuration does not contain "environmentSource" entry.

A new environmentSource entry replaces the previous source entry inside environments.

To migrate angular-cli.json follow the example below:

Before:

"environments": {
  "source": "environments/environment.ts",
  "dev": "environments/environment.ts",
  "prod": "environments/environment.prod.ts"
}


After:

"environmentSource": "environments/environment.ts",
"environments": {
  "dev": "environments/environment.ts",
  "prod": "environments/environment.prod.ts"
}
```

Should I contribute by fixing that?

I've already done this for another project successfully.

**Comment by neosoko** [comment]
Hi,

Found the solution. If you the error above still persist then try this:

open angular-cli.json
find-
"environments": {
"source": "environments/environment.ts",
"dev": "environments/environment.ts",
"prod": "environments/environment.prod.ts"
}

and replace with:
"environmentSource": "environments/environment.ts",
"environments": {
"dev": "environments/environment.ts",
"prod": "environments/environment.prod.ts"
}

**Comment by kaleemullah360** [comment]
it happens after upgrading from `angular-cli` to latest `@angular/cli@latest`.
and updating `angular-cli.json` as decribed by ng-cli, solve the issue,

```
"environmentSource": "environments/environment.ts",
"environments": {
  "dev": "environments/environment.ts",
  "prod": "environments/environment.prod.ts"
}
```

**Comment by AzharKhan04** [comment]
Hi,
I got this error
Environment configuration does not contain "environmentSource" entry.

A new environmentSource entry replaces the previous source entry inside environments.

To migrate angular-cli.json follow the example below:

Before:

"environments": {
  "source": "environments/environment.ts",
  "dev": "environments/environment.ts",
  "prod": "environments/environment.prod.ts"
}


After:

"environmentSource": "environments/environment.ts",
"environments": {
  "dev": "environments/environment.ts",
  "prod": "environments/environment.prod.ts"
}

replaced 
"environments": {
  "source": "environments/environment.ts",
  "dev": "environments/environment.ts",
  "prod": "environments/environment.prod.ts"
}

with 
"environmentSource": "environments/environment.ts",
"environments": {
  "dev": "environments/environment.ts",
  "prod": "environments/environment.prod.ts"
}

then tried ng build now getting


Environment configuration does not contain "source" entry.

**Comment by axtho** [comment]
@AzharKhan04 this may your environment. The cli JSON is fine. What is your output for `ng -v`?
This issue should actually be closed.

**Comment by rjanya** [comment]
this code will not help me.....still i am getting error

**Comment by rjanya** [comment]
can you give me the better code for me? 
please....

**Comment by rjanya** [comment]
Environment configuration does not contain "source" entry. This is my error will you give the another solution for this error...

**Comment by sarojrout** [comment]
This issue should be closed. right solution given by @neosoko

**Comment by developer234** [comment]
Please friends how can i navigate to the angular-cli.json file.

**Comment by EmielSito** [comment]
Same question as @developer234 
is there another angular-cli.json file other than the one in the root of my project ?

**Comment by AwaisZaki** [comment]
Same error came in my project and I follow the @neosoko  method and replace tha script but not work for me. any other solution.

**Comment by cormacrelf** [comment]
This really has nothing to do with ng2-dragula.
