### ISSUE TITLE
How to make multiple containers droppable ?

### ISSUE THREAD

**Issue by saratSubramaniam** [valor-software/ng2-dragula#592]
I want to make a quadrant-like drag-drop UI. A big square divided into 4 smaller squares, and another element should be draggable and droppable inside any area, in any of these 4 squares.

HTML structure I have is as follows.

        <div class="quadrant-box">
            <div class="quadrant q1" [dragula]='"bag-one"'></div>
            <div class="quadrant q2" [dragula]='"bag-one"'></div>
            <div class="quadrant q3" [dragula]='"bag-one"'></div>
            <div class="quadrant q4" [dragula]='"bag-one"'></div>
            <div class="draggable-items-container" [dragula]='"bag-one"'>
                <div class="draggable-item">Drag me</div>
            </div>
        </div>

Below is how the UI would somewhat look like. The circle inside should be draggable.

![capture](https://cloud.githubusercontent.com/assets/16252589/23601861/9b5dac60-0273-11e7-8c19-4ca31df39c8e.PNG)

The above code does not help me achieve what I want.
Could anyone please help ?

**Comment by Bilkiss** [comment]
I think your code should structure like this:
` <div class="quadrant-box">
      <div class="quadrant q1" [dragula]='"bag-one"'>
            <div class="draggable-item">Drag me</div>
        </div>
        <div class="quadrant q2" [dragula]='"bag-one"'></div>
        <div class="quadrant q3" [dragula]='"bag-one"'></div>
        <div class="quadrant q4" [dragula]='"bag-one"'></div>
    </div>`

Add the "draggable-item" item in anyone of your `[dragula]` container for it to work.

**Comment by cormacrelf** [comment]
If you want it to drop anywhere and retain the position it had when you were dragging it... dragula is not for you. I'm guessing that circle is a fine-grained XY selector, it sure looks like one. Dragula can't do it. Try something else, or maybe take the dragula codebase and customise it for your purposes.

**Comment by cormacrelf** [comment]
FYI, I created almost exactly this demo in [angular-skyhook](https://github.com/cormacrelf/angular-skyhook) -- see [here](https://cormacrelf.github.io/angular-skyhook/modules/examples.html#/drag-layer/xy-pad).
