### ISSUE TITLE
Auto Scrolling – dom-autoscroller

### ISSUE THREAD

**Issue by manuelfink** [valor-software/ng2-dragula#618]
I'm looking for a way to make my larger list auto scrollable. What you think of integrating autoscroll into this package? I guess its a really typical use case for most (larger) scrollable lists.

https://www.npmjs.com/package/dom-autoscroller

**Comment by stephanoapiolaza** [comment]
do you have a plunkr?

**Comment by ghybs** [comment]
Hi,

Looks like it is not too difficult to integrate both functionalities:
https://plnkr.co/edit/mDNw7pDDp5oHFeHZApB5?p=preview

However I am not sure how to get the `drake` in `ng2-dragula`?

**Comment by cormacrelf** [comment]
I'll just leave this here: https://github.com/cormacrelf/dragula-touch-demo. It's easy enough to integrate, so easy that it doesn't warrant baking into ng2-dragula, but this will probably end up in the docs.

**Comment by PierreDugue** [comment]
I trying to use it but I have an issue while I build : Cannot find DOM-autoscroller (thought I added the import) : Cannot find module 'dom-autoscroller'

Anyone with the error?

**Comment by ghybs** [comment]
Hi,

Hard to tell if you do not share your code…
What does your import statement look like?

**Comment by PierreDugue** [comment]
Yes I know but I really don't understand where it can come from
For the import : 
import autoScroll from 'dom-autoscroller';

I tried to delete and re-install dom-autoscroller but same error.

**Comment by ghybs** [comment]
The default imported file from `dom-autoscroller` package is `dist/bundle.js`, which uses a CommonJS pattern.

As such, you should use the statement:

```javascript
import * as autoScroll from 'dom-autoscroller';
```

Otherwise, you can also import the ES compatible module.
The statement would probably be in that case:

```javascript
import AutoScrollerFactory from 'dom-autoscroller/dist/bundle.es';
```

Hope this helps.

**Comment by PierreDugue** [comment]
Thx for your help but i tried both and I still have the same error. I download the project of cormacrelf and it is working so I think there is really a problem with the versions of CLI and Angular.

**Comment by cormacrelf** [comment]
Did you install it in the correct folder? Npm and yarn will happily install in any folder you happen to be in, make sure it actually appears in your package.json.

**Comment by PierreDugue** [comment]
Yep, I have it in my package : dom-autoscroller": "^2.3.1" and the folder dom-autoscroller is actually in my node_modules folders.

**Comment by PierreDugue** [comment]
Ok I tried with Angular 4 and it's working now.

**Comment by paw1** [comment]
So upgrading from angular 2 to 4 will detect dom-autoscroller? any workaround without upgrading to angular 4? How did you finally import the dom-autoscroller?

**Comment by PierreDugue** [comment]
I don't know for Angular 2 sorry, I have upgraded my project on V4 and it's working.

**Comment by costea93** [comment]
**this.down** property, where it comes from?

**Comment by ghybs** [comment]
Hi @costea93,

…from dom-autoscroll [usage example](https://github.com/hollowdoor/dom_autoscroller#usage)

Looks like it is a boolean indicating whether a mouse button or touch is down, i.e. if user is likely to be trying to scroll.

**Comment by moniuch** [comment]
@costea93 From dom-autoscroller README:
Auto Scroller Properties
down = Boolean
Is the pointer down?

**Comment by moniuch** [comment]
I agree with the OP - lack of auto-scroll capability is a bad drag-and-drop UX. I would vote to have that as an option in dragula.

**Comment by moniuch** [comment]
Regarding the example from dom-autoscroller - here is how I managed to get it working.

```
dragulaService.drag.pipe(
      takeUntil(this._destroy$),
    ).subscribe(([bag, movingEl, containerEl]) => {
      autoScroll(containerEl.parentNode, {
        margin: 20,
        pixels: 5,
        scrollWhenOutside: false,
        autoScroll: function () {
          const drake = dragulaService.find('bag-todos');
          return this.down && drake.drake.dragging;
        },
      });
    });
```

Note that the result of dragulaService#find is not the drake that we can use, but it contains it - under `drake` key - hence `drake.drake`.

Feels like we could benefit from the usable drake being passed as an argument in the drag observable.
