### ISSUE TITLE
Get dragged/dropped item object in event subscriptions #enhancement

### ISSUE THREAD

**Issue by manuelfink** [valor-software/ng2-dragula#619]
Is it anyhow possible to get dragged item instance?

eg bind item to draggable element

```
<ul [dragula]='"bag-one"' [dragulaModel]='items'>
  <li *ngFor="let item of items" [dragulaItem]="item"></li>
</ul>
```

return item on drop

```
constructor(private dragulaService: DragulaService) {
    dragulaService.drop.subscribe((value) => {
      console.log('dragged',value.dragged); // the item which was dragged
      console.log('bag',value.bag);
      console.log('index',value.index); // index where the element was inserted into bag
      console.log('after',value.after); // element after the inserted element
      console.log('before',value.before); // element before the inserted element
    });
  }
```

I guess the html elements currently returned by dragula makes working hard in angular.

**Comment by borislemke** [comment]
I circumvented this issue by adding `[attr.item-id]="someUniqueId"` to each item and get the attribute value with simple `el.getAttribute('item-id')` to somehow match which item object has been dragged (where `el` is the HTML element returned by dragula's drop event)

**Comment by doug62** [comment]
+100

**Comment by nicolassharp** [comment]
I agree, this is essential, especially if you're sync through a service with a server / other components.

**Comment by cormacrelf** [comment]
There's a PR over at https://github.com/valor-software/ng2-dragula/pull/704 that needs a little refinement, but it's simple enough. Instead of using a `[dragulaItem]` prop, it just sends indexes the DOM and grabs that index from the array. I think that's the route to take.

**Comment by ctchisholm** [comment]
+1

**Comment by mgurnani** [comment]
+1

**Comment by cormacrelf** [comment]
This will be available in v2.
