### ISSUE TITLE
Storing items inside a bag in an array

### ISSUE THREAD

**Issue by Hehohehoheho** [valor-software/ng2-dragula#623]
I have a bag which looks like this:

      <td [dragula]='"right"'>
                        <div i18n>Item</div>
                        <div i18n>Item 2</div>
                        <div i18n>Item 3</div>
                        <div i18n>Item 4</div>
                    </td>
         <td [dragula]='"right"'></td>

How can I store the items in the second table cell in an array? If I use the onDrop event, I cannot differentiate between the two cells since they have to be in one bag.

**Comment by cormacrelf** [comment]
Probably use two different `[dragulaModel]="..."` arrays, one for each. Move an element from the first to the second, and ng2-dragula will move the underlying object from the first to the second array.

Or, just use a `ViewChild` referring to each `<td>` and check whether a child's `nativeElement` is the same as the container element supplied in the drop event.
