### ISSUE TITLE
relax peer dependency to support angular 4.0.0

### ISSUE THREAD

**Issue by Ketec** [valor-software/ng2-dragula#636]
currently it results in "requires a peer of" warnings.
It works on current angular 4 release, so perhaps the peerDep could be relaxed to >=4.0.0?

**Comment by Drol** [comment]
On 1.3.1 i get the following errors
```
warning "ng2-dragula@1.3.1" has incorrect peer dependency "@angular/compiler@2.4.3".
warning "ng2-dragula@1.3.1" has incorrect peer dependency "@angular/forms@2.4.3".
```

Packages
```
  "dependencies": {
    "@angular/common": "4.0.1",
    "@angular/compiler": "4.0.1",
    "@angular/core": "4.0.1",
    "@angular/forms": "4.0.1",
    "@angular/http": "4.0.1",
    "@angular/platform-browser": "4.0.1",
    "@angular/platform-browser-dynamic": "4.0.1",
    "core-js": "2.4.1",
    "ng2-dragula": "1.3.1",
    "rxjs": "5.3.0",
    "zone.js": "0.8.5"
  },
  "devDependencies": {
    "@angular/compiler-cli": "4.0.1",
    "@types/node": "7.0.12",
    "angular2-template-loader": "0.6.2",
    "awesome-typescript-loader": "3.1.2",
    "raw-loader": "0.5.1",
    "ts-loader": "2.0.3",
    "ts-node": "3.0.2",
    "tslint": "^5.1.0",
    "typescript": "2.2.2",
    "webpack": "2.3.3",
    "webpack-notifier": "1.5.0",
    "xml-loader": "1.2.1"
  }
```

**Comment by peterlaraia** [comment]
Seeing the same as @Drol, look like maybe ngm is picking up & merging the peer dependencies in src/package.json in the build step?

**Comment by fredpolicarpo** [comment]
I'm also having the same problem as @Drol 

```
npm WARN ng2-dragula@1.3.1 requires a peer of @angular/compiler@2.4.3 but none was installed.
npm WARN ng2-dragula@1.3.1 requires a peer of @angular/forms@2.4.3 but none was installed.

```

**Comment by lawrencebass1992** [comment]
Same here. Is there a current work around to getting rid of these warnings?

**Comment by fluky** [comment]
+1, please get rid of fixed versions as well:

"@angular/compiler": ">=2.0.0 || >=4.0.0-beta.0"

**Comment by Hesesses** [comment]
+1

**Comment by basst314** [comment]
+1

**Comment by NeuralChris** [comment]
+1

**Comment by vaidd4** [comment]
In the `ng2-dragula` github sources, `@angular/compiler` & `@angular/forms` are mentionned as `devDependencies`, but when pulled from npm they are added to `peerDependecies`.
Any reason why ?

**Comment by peterlaraia** [comment]
@vaidd4 I'm pretty sure it's because the build tool being used, ngm-cli is merging this [package.json](https://github.com/valor-software/ng2-dragula/blob/master/src/package.json#L7) from the src folder, and using the version it finds in the root package.json's devDependencies.

So I figure either the peerDependencies versions of compiler & forms need to be explicitly set in the root package.json, like core & common, or they need to be removed from the src/package.json. I haven't made a PR because I'm not sure which is more appropriate

**Comment by malecki-se** [comment]
+1

**Comment by BogalooDev** [comment]
+1

**Comment by rphovley** [comment]
+1

**Comment by gabrielrosset** [comment]
+1

**Comment by BogalooDev** [comment]
Committed fix regarding @angular/compiler & @angular/forms fixed version and migrated Karma to @Angular/CLI  approach in order to fix failing test run

**Comment by vaidd4** [comment]
thanks for the comment @BogalooDev !
Is the fix available in the v1.3.1 ? 
If not, will it be available in next version ? 
If so, why did you close the issue if the fix isn't published yet ?

**Comment by cormacrelf** [comment]
Chill out, this fix is literally just two lines of warnings no longer appearing when you do a build. Will be the only thing in 1.3.2 when that's released, I'm not in charge of that though. Shouldn't have closed in the commit message, I meant to just close the PRs.

**Comment by vaidd4** [comment]
Oh It wasn't meant to be an aggressive comment, I was just covering the possible answers ^^
Sorry and thanks for your answer

**Comment by emin93** [comment]
Actually this causes more than just a warning. If you do work with NPM Shrinkwrap, then this won't work because of invalid peer dependencies.

`
npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! peer invalid: @angular/compiler@2.4.3, required by ng2-dragula@1.3.1
npm ERR! peer invalid: @angular/forms@2.4.3, required by ng2-dragula@1.3.1
`

**Comment by cormacrelf** [comment]
Folks at valor-software are in charge of releasing. I asked about a week ago, got a reply but no action yet.

**Comment by fluky** [comment]
Somebody needs to fork this, it meets all the criteria of dead software.  When you can't even get a 3 character change done in 2 months...

**Comment by cormacrelf** [comment]
@fluky Yeah look, you're probably right. Plus there's lots of stuff we just can't do without a bit of rewriting, see #728. Ideally we should be able to do most stuff [react-dnd](http://react-dnd.github.io/react-dnd/examples-chessboard-tutorial-app.html) can do.

**Comment by axtho** [comment]
If valor is not actively maintaining this I too am all for forking. It is a great library and it would be a pity if it stalls. There are not many good dnd libs for Angular4 out there. What would be in improvement on react-dnd would be to enable proper touch enabled drag/drop/sort (AFAIK dragula does that to some degree).

**Comment by OliverNeff** [comment]
It is fixed on master branch. How can I include it in npm directly from github?

**Comment by aeimer** [comment]
psss... A new release is comming soon ;)

**Comment by aeimer** [comment]
Since the version 1.5.0 is out we can close this issue?! @Ketec

**Comment by valorkin** [comment]
published

**Comment by stewx** [comment]
Where is 1.5.0? It's not in the list of releases: https://github.com/valor-software/ng2-dragula/releases

**Comment by vaidd4** [comment]
@stewx FYI, I made an issue on this here : https://github.com/valor-software/ng2-dragula/issues/747
