### ISSUE TITLE
Is this thing still maintained?

### ISSUE THREAD

**Issue by bouchepat** [valor-software/ng2-dragula#638]
Hi,

I'm just wondering if this package is still maintained? It does look like there is much activities. Would like a support for latest ng2 versions!

Thanks.

**Comment by cormacrelf** [comment]
It looks like it needs a few more people with commit/merge rights. It's not obvious who at valor-software has this (apart from @valorkin, who has been quiet) and can give it to others.

**Comment by valorkin** [comment]
Lately my workload is killing almost all my free time, so more contributors and maintainers would good for project

**Comment by cormacrelf** [comment]
I'm happy to help. My company is using ng2-dragula in a soon-to-be alpha, so I'm invested in angular with Dragula. Will happily keep greenkeeper at bay and fix some bugs, obviously most problems are upstream.

**Comment by valorkin** [comment]
Write access granted

**Comment by valorkin** [comment]
Find me in slack,
Fastest way to get in touch with me - twitter,
Then ngx slack.
Dm me if you will need anything

**Comment by cormacrelf** [comment]
Thanks!
