### ISSUE TITLE
Receiving error issues

### ISSUE THREAD

**Issue by hennessyben** [valor-software/ng2-dragula#656]
Receiving several issues in installing Dragula. There is no Git file, fails using Git.

[error.txt](https://github.com/valor-software/ng2-dragula/files/918642/error.txt)

**Comment by asnelling** [comment]
Make sure you have Git installed, you can get it from here:

https://git-scm.com/downloads

**Comment by asnelling** [comment]
Make sure that:
- you have Git installed:
  https://git-scm.com/downloads
- `git.exe` is [on your PATH](https://github.com/inexor-game/code/wiki/%5BWindows%5D-add-git-to-PATH)
- running `git --version` in Command Prompt doesn't give you an error:
```Batchfile
:: good
F:\Documents\Angular\ng2-dragula-master>git --version
git version 2.12.2

:: bad
F:\Documents\Angular\ng2-dragula-master>git --version
'git' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by cormacrelf** [comment]
Looks like @asnelling is probably right.
