### ISSUE TITLE
drag & drop from different bags?

### ISSUE THREAD

**Issue by ebeem** [valor-software/ng2-dragula#659]
```
<div class="content container" dragula='"bag-1"'>
items ...
</div>

<div class="content container" dragula='"bag-2"'>
items ...
</div>

```

is it possible to drag and drop items between bag 1 & 2?

**Comment by cormacrelf** [comment]
No. If you want to allow dragging items between two containers, you set them to be part of the same bag. That's the idea.

**Comment by cormacrelf** [comment]
Slight extension on the above answer:

Bags correspond to 'drakes' from vanilla dragula. ng2-dragula will create a drake when it encounters a new bag name, but you can create them yourself. So, if you want a single container to be involved in two different bags, you can create two drakes manually (read the docs) and have them both enlist the same container.
