### ISSUE TITLE
Having a difficult time figuring out how to include ng2-dragula with System.js

### ISSUE THREAD

**Issue by denodaeus** [valor-software/ng2-dragula#66]
So I've bootstrapped an angular2 project and I'm trying to use ng2-dragula.

Here's what my System.config looks like (in terms of ng2-dragula)
```javascript
paths: {
  'ng2-dragula': './node_modules/ng2-dragula/ng2-dragula.js'
}
```

And my index.html importing ng2-dragula:
```html
<script src="node_modules/ng2-dragula/ng2-dragula.js"></script>
```

Everything seems to load fine after this and I'm not getting 404's on finding the ng2-dragula module.  However, after I actually try importing the Dragula directive and DragulaService provider, I get these errors:

```bash
[1] GET /ng2-dragula/src/directives/dragula.directive 404 0.708 ms - 57
[1] File change detected /Users/bsmith/Development/git/sample.com/sample-ui/app/work-board/work-board.component.ts
[1] GET /ng2-dragula/src/directives/dragula.directive 404 0.967 ms - 57
```

My component code just follows the FAQ:

```typescript
import { Dragula, DragulaService } from 'ng2-dragula';
@Component({
  directives: [Dragula],
  viewProviders: [DragulaService]
})
```

Any help on troubleshooting this would be greatly appreciated.

**Comment by denodaeus** [comment]
Also, I've tried adding a global 'defaultJSExtensions: true' property to my system.config, but then I run into issues linked here:  https://github.com/systemjs/systemjs/issues/761

So I've also tried putting a entry for ng2-dragula in the system.config.packages property like so:
```javascript
    'ng2-dragula': {
      defaultExtension: 'js'
    }
```

But I encounter the same problem.  I'm also having the duplicate directives issue (another issue on the list here) which I think might be related to this package still using angular2-2.0.0.beta0 (I'm using beta3).

**Comment by NathanWalker** [comment]
Take out the script tag in your index.html

Don't need it if system config is right.
May be the cause of the issue.

**Comment by brianaprince** [comment]
I am having an issue when I upgrade Angular2 to beta3 and zone.js to 0.5.11.  I am just trying to run the example.  I get the following in the console:

![dragerror](https://cloud.githubusercontent.com/assets/10246578/12953178/4d3fd16c-cfe7-11e5-98a1-13e2bff51d10.png)

I am not 100% sure of the build process.  I did a 'npm run build.dev' and 'npm run start'.

**Comment by denodaeus** [comment]
Thanks, I think I got a little further but now I'm running into this:  https://github.com/valor-software/ng2-dragula/issues/62

Indeed, no need to link script to index.html because I already referenced where it's supposed to be in the System.config.

**Comment by NathanWalker** [comment]
@denodaeus Please try the latest `1.1.0` which was just released:
https://www.npmjs.com/package/ng2-dragula

**Comment by thomasbee** [comment]
I am trying to use ng2-dragula with the system.js seed https://github.com/mgechev/angular2-seed
When I simply do 
> npm install ng2-dragula --save 
1.1.0 is install but no dependencies, so I manually added
> npm install dragula@3.6.3 --save
Then, in a component, when I do
import { Dragula, DragulaService} from 'ng2-dragula/ng2-dragula';
I get a runtime error where the browser tries to load dragula.js from 
http://localhost:5555/node_modules/dragula.js // where obviously, the directory name is missing?
How do I configure the seed to load the file from the correct directory?

**Comment by xLama** [comment]
I don´t know if you got it works but you have to add these lines in systemjs.config

In map object:
```js
    'dragula': 'node_modules/dragula',
    'contra': 'node_modules/contra',
    'atoa': 'node_modules/atoa',
    'ticky': 'node_modules/ticky',
    'crossvent': 'node_modules/crossvent/src',
    'custom-event': 'node_modules/custom-event',

```
In packages object

```js

    'dragula': { main: 'dragula.js', defaultExtension: 'js' },
    'contra': { main: 'contra.js', defaultExtension: 'js' },
    'atoa': { main: 'atoa.js', defaultExtension: 'js' },
    'ticky': { main: 'ticky.js', defaultExtension: 'js' },
     'crossvent': { main: 'crossvent.js', defaultExtension: 'js' },
     'custom-event': { main: 'index.js', defaultExtension: 'js' },
```

**Comment by nanthil** [comment]
ERR_FILE_NOT_FOUND
.../node_modules/ng2-dragula/ng2-dragula

Anyone figured this out? I've tried everything the op tried. fresh clone of angular 2 quickstart, npm install, and followed everything in documentation, and on this thread. I'm finding the support for this package to be extremely aggravating, since nobody has a clear answer on how to install and use this package reliably.
