### ISSUE TITLE
[bug] Drop does not fire when item is dropped outside of track or in the same place it came from

### ISSUE THREAD

**Issue by alshdavid** [valor-software/ng2-dragula#660]
If I drag and item from it's track then drop it where it originally was or outside of the drag-sensative area, the drop command doesn't fire.

**Comment by SieBrum** [comment]
Im pretty sure it fires DragulaService.Cancel when you keep it at its original place.

**Comment by cormacrelf** [comment]
@SieBrum is correct. You can modify the behavior for drops outside any containers with the `removeOnSpill` and `revertOnSpill` options in the `DragulaService.setOptions` call.
