### ISSUE TITLE
Combining with other drag libraries

### ISSUE THREAD

**Issue by imjustd** [valor-software/ng2-dragula#661]
It would be nice if we can combine the dragula with other DnD libraries. Namely, I need to combine it with angular tree component https://angular2-tree.readme.io/docs/drag-drop. I need support to drop items from dragula container to the tree. But now I don't have a way to do this unless I use custom drag handle for dragula, but this is not the way I want to use it.

**Comment by cormacrelf** [comment]
Sorry, out of scope. There's an issue on this repo somewhere about doing what angular2-tree does in dragula (use the search function), but we're not building interop just for you, or for any other drag and drop solution.
