### ISSUE TITLE
Groups and nested items

### ISSUE THREAD

**Issue by Hesesses** [valor-software/ng2-dragula#663]
Is it possible to have "groups" and nested items and then you could reorder the groups or items (inside the group)  and also move items to another group:

![image](https://cloud.githubusercontent.com/assets/2721970/25227121/0ee30084-25d0-11e7-9120-8a8d71f1cbc9.png)
```
<ul [dragula]='"groups"'>
            <li>
              <div>group name</div>
              <ul [dragula]='"items"'>
                <li>item name</li>
                <li>item name</li>
                <li>item name</li>
              </ul>
            </li>
            <li>
              <div>group name</div>
              <ul [dragula]='"items"'>
                <li>item name</li>
                <li>item name</li>
                <li>item name</li>
              </ul>
            </li>
            <li>
              <div>group name</div>
              <ul [dragula]='"items"'>
                <li>item name</li>
                <li>item name</li>
                <li>item name</li>
              </ul>
            </li>
          </ul>```

With the code above you can only reorder the groups

**Comment by dlcooper** [comment]
+1 
I need this too.  Would be a great enhancement

**Comment by jcroldan** [comment]
+1
I also need it. Please, can you consider it?

**Comment by jcroldan** [comment]
Found a solution using Invalid method in dragulaService.setOptions.

In your case it would be:

```
    dragulaService.setOptions('groups', {
      invalid: function (el, handle) {
        return el.tagName === 'UL';
      }
    });
```
If you want, you can change el.tagName for another property that match your 'items' tag.

Hope this helps.

**Comment by alexsmartsky** [comment]
I created an infinitely recursive tree using ng2-dragula and firebase. This library is fantastic .. 

Perhaps something like this may get you closer - 

```
<div [dragula]="'myBag'" >
<ul  draggable="true" [class]="'groupClass'" *ngFor="let group of groups">
            <li>
              <div>{{group.title}}</div>
              <ul [dragula]="'myBag'">
                <li  draggable="true" [class]="'itemClass'" *ngFor="let item of group">{{item.title}}</li>
              </ul>
            </li>
          </ul>
</div>
```

in your component ngOnInit 
```
    const bag: any = this.dragulaService.find('myBag');
    if (bag !== undefined) this.dragulaService.destroy('myBag');
    this.dragulaService.setOptions('myBag', {
      revertOnSpill: true,
      accepts: function (el, target, source, sibling) {
        return !el.contains(target);
      },
    });
```
I made it all one bag called "myBag". I believe if you extend the accepts function, you should be able to use the class names to only allow groups to be dragged into group target areas and items into the item target area.

Below I've also pasted my html for tree component for inspiration. 

Cheers, Alex

```
<div class="elem wholeItem">
  <div class="titleItem"> {{ node?.item?.title }}</div>
</div>

<div *ngIf="node" class="childArea" [dragula]="'abtree'" [dragulaModel]="children" [attr.data-id]="node?.item?.itemCode">
  <div class="insetChild" draggable="true" *ngFor="let child of children  | orderBy : 'sortOrder' : 'number' : false; let i = index" [attr.data-id]="child.itemCode">
    <document-tree [entireDocument]="entireDocument" [projectId]="projectId" [documentType]="documentType" [itemCode]="child.itemCode" [parentCode]="node?.item?.itemCode" [sortOrder]="i" (change)="bubbleEmit($event)"></document-tree>
  </div>
</div>
```

**Comment by Hesesses** [comment]
Thank you @alexsmartsky for the ideas! Works perfectly now :)

**Comment by chrillewoodz** [comment]
I have a similar example but I can't get it working.. https://stackoverflow.com/questions/48325157/angular-nested-draggable-rows-and-columns

**Comment by jooshifa** [comment]
Hi. I need the same. but I don't need drag into another group.only within the group.Then how can i do this? Can anyone help me?

**Comment by CoolGuyInHotTown** [comment]
I also need this too.

**Comment by tatsujb** [comment]
@jcroldan I tried a similar implementation of your fix but I get a `TypeError: sourceModel.splice is not a function`
```
  options = {
    direction: 'horizontal',
    invalid: (element, source, handle, sibling) => {handle.className.includes('bag-one')},
  };
```

can you help me?

**Comment by hariharan618** [comment]
Looks like setOptions is deprecated or changed now ? I can't seem to get mine working on a simple nested list. Here i have my stackblitz. Any help is appreciated

https://stackblitz.com/edit/ng2-dragula-vukxda

**Comment by hariharan618** [comment]
> @Hesesses @jcroldan I need simillar functionality.Based on your code suggestions , below code worked for me. Thank you :)
> 
> In your component.ts
> 
> ```ts
> dragulaService.setOptions('groups', {
>       invalid: function (el, handle) {
>         return el.tagName === 'UL';
>       }
> });
> 
> //sample array format...
> public nestedLists = [
> 		{
> 			section: 'Section 1',
> 			units: [
> 				{
> 					name: 'Item 1a',
> 					section_id: 1,
> 				},
> 				{
> 					name: 'Item 1b',
> 					section_id: 1,
> 				},
> 				{
> 					name: 'Item 1c',
> 					section_id: 1,
> 				}
> 			]
> 		},
> 		{
> 			section: 'Section 2',
> 			units: [
> 				{
> 					name: 'Item 2a',
> 					section_id: 2,
> 				},
> 				{
> 					name: 'Item 2b',
> 					section_id: 2,
> 				},
> 				{
> 					name: 'Item 2c',
> 					section_id: 2,
> 				}
> 			]
> 		},
> 		{
> 			section: 'Section 3',
> 			units: [
> 				{
> 					name: 'Item 3a',
> 					section_id: 3,
> 				},
> 				{
> 					name: 'Item 3b',
> 					section_id: 3,
> 				},
> 				{
> 					name: 'Item 3c',
> 					section_id: 3,
> 				}
> 			]
> 		},
> 		
> 	];
> ```
> 
> ## ===================
> In your component html:
> ```
> <ul [dragula]='"groups"' [dragulaModel]='nestedLists'>
> 	<li *ngFor="let lesson of nestedLists;let index = index">
> 		<div>{{ lesson.section }}</div>
> 		<ul [dragula]='"items"' [dragulaModel]='nestedLists[index].units'>
> 			<li *ngFor="let unit of lesson.units">
> 			   {{ unit.name }}
> 			</li>
> 		</ul>
> 	</li>
> </ul>
> ```

Thanks for this, but looks like there's no animation ?

**Comment by s-gbz** [comment]
In my case, child elements of the "actual" group-drag-handle were not accepted.
I solved the problem by checking if the clicked handle is part of the "whole drag-handle".

Feel free to ping me if someone needs more help.

```ts
  private initDropRules_EDITOR_CODELINES() {
    this.dragulaService.createGroup("EDITOR_CODELINES", {
      direction: 'horizontal',
      moves: (_el, _source, handle) => {
        return this.elementIsChildOfDragHandleCodeLine(handle) ? true : false;
      }
    });
  }

  private elementIsChildOfDragHandleCodeLine(child) {
    const possibleParentNodes = document.getElementsByTagName("DRAG-HANDLE");
    let foundChild = false;

    for (let i = 0; i < possibleParentNodes.length; i++) {
      if (possibleParentNodes[i].contains(child)) {
        foundChild = true;
        break;
      }
    }

    return foundChild;
  }
```  

```html
<div dragula="EDITOR_CODELINES" [(dragulaModel)]="codeLines">
    <div *ngFor="let codeLine of codeLines; let lineNumber = index">
        <drag-handle></drag-handle>
        <div *ngFor="let child of codeLine>
            <dragula child ...></dragula child>
        </div>
    </div>
</div>
```  

Inside of the `<drag-handle>` (just to understand what went wrong - clicking on any of the child elements didn't trigger the group handle)
```html
<span class="icon-text">
    <span class="icon">
        <svg
            width="24px"
            fill="currentColor"
            viewBox="0 0 24 24"
        >
            <path
                d="M10 9h4V6h3l-5-5-5 5h3v3zm-1 1H6V7l-5 5 5 5v-3h3v-4zm14 2l-5-5v3h-3v4h3v3l5-5zm-9 3h-4v3H7l5 5 5-5h-3v-3z"
            >
            </path>
            <path
                d="M0 0h24v24H0z"
                fill="none"
            ></path>
        </svg>

    </span>
    <span>{{ textInput }}</span>
</span>
```
