### ISSUE TITLE
Possible ? More Complex Drag&Drop

### ISSUE THREAD

**Issue by darklinki** [valor-software/ng2-dragula#664]
I love dragula and make very much use of it. But from what I see its limited.
Eventually somethings are possible and I just don´t know. Can you tell me if the following scenario is possible ?

I want a grind with lets say 16x16 cells and Objects with a size of 4x4. Now I want to move this object within the grid from starting position 8/10 to 10/10.

**Comment by cormacrelf** [comment]
You could try setting all the elements' CSS to float:left and width:25%? (With a clear:left on the container).

**Comment by cormacrelf** [comment]
On re-reading, your use case is slightly more complicated, but nonetheless I think dragula is somewhat up to the task. Try creating a 16x16 grid of dragula containers (ie all with the same bag name). Set the CSS overflow property on each to 'visible', and the same width/height. Then your 4x4 sized object can be in one of them, and extend beyond the size of that individual container.

**Comment by darklinki** [comment]
I kinda builded it very well with bootstrap, I can even resize the grid elements. Its a little bit laggy (Final Version has a grid with 128x128) caused by the big amount if listeners. Scrolling is at the moment insane :D But I work on it an will get it to work.

**Comment by cormacrelf** [comment]
For future reference, probably use CSS grid and maybe use setOptions to make Dragula go horizontally.
