### ISSUE TITLE
Can't save changes using dragulaService.setOptions

### ISSUE THREAD

**Issue by cherrera50** [valor-software/ng2-dragula#668]
I'm working in a project that run as a Power Point add-in. Each component represent an individual diagram. Two of them has two columns and the items on this columns might been dragged inside each column or among them.

Additionally, I have a save() method to keep the changes when the user add or remove items, drag and drop items or enter a text.

At this point everything work fine and the changes has keeped when the Power Point presentation ends or when the current slide is changed.

The problem is when I need to put some restriction. For example, I need to keep at least one item in each column and forbid the drag when a column has only one element. At the same time, when a column has five elements I also need forbid the drag.

Using dragulaService.setOptions, I can put this restrictions, but for some weird reason, the changes are not saved, and, for example, when I drag some element, after change the slide and return to the diagram, the element previously dragged had returned to its original position.

The code in my constructor is the follow:

<code>
  constructor(private _element: ElementRef, private _renderer: Renderer,
    private _service: TemplateService, private dragulaService: DragulaService) {
    super(_service);

    this.configurationName = 'VGOWIN_CONFIG';
    this._items = [];
    this._properties = {};

    dragulaService.drag.subscribe((value: any) => {
      this.onDrag(value.slice(1));
    });
    dragulaService.drop.subscribe((value: any) => {
      this.onDrop(value.slice(1));
    });
    dragulaService.over.subscribe((value: any) => {
      this.onOver(value.slice(1));
    });
    dragulaService.out.subscribe((value: any) => {
      this.onOut(value.slice(1));
    });
    dragulaService.setOptions('first-bag', {
      accepts: function (el: Element, target: Element, source: Element, sibling: Element): boolean {
        return (source.childElementCount > 1 && target.childElementCount < 5);
      }
    });
  }
</code>

Thanks for your tips.

**Comment by cormacrelf** [comment]
You haven't posted where you call your save function. I can't determine if this has anything to do with ng2-dragula if you don't do that. I suspect is it not ng2-dragula's fault that it isn't getting called. My guess would be that you're calling save in the wrong place, and it should only be called in the onDrop handler, but this repo isn't responsible for debugging your own code.
