### ISSUE TITLE
Dragging ng2 components

### ISSUE THREAD

**Issue by pete2014** [valor-software/ng2-dragula#7]
Hi,

Do you have an example how to implement dragging on a simple ng2 component. The demo website just uses strings. 

I was using the 'RepeatExample' section and replaced the string with the component object:
<code>many: Array<any> = [new TestComponent];</code>
All I get there is the text '[object Object]' and not the actual visual component.

I realize that I might be mis-understanding this completely so any help would be appreciated.

**Comment by NathanWalker** [comment]
Hi @pete2014 that's actually more of an Angular 2 question related to `ngFor` usage.
You might ask on stackoverflow. 

Bascially how could I use `ngFor` to iterate through an array of component classes?

**Comment by NathanWalker** [comment]
The process would be something like the ability to pull the `selector` from the component to place on the element possible? Or there may be some other Angular 2 magic you could use to pull something like that off.
