### ISSUE TITLE
Changing the way drop position is calculated

### ISSUE THREAD

**Issue by imjustd** [valor-software/ng2-dragula#710]
How can we change the way drop target position is calculated? For example, sometimes I need to move the dragged item to the far left position in order to drop it there. The way I want to work is, when I drag the item over some other item, I want immediately put the dragged item at the hovered item position.

**Comment by cormacrelf** [comment]
This is more of a dragula issue than ng2-dragula. There's lots of discussion already over at https://github.com/bevacqua/dragula/issues/165, and a couple of nice PRs including https://github.com/bevacqua/dragula/pull/461.
