### ISSUE TITLE
Drag start / stop event

### ISSUE THREAD

**Issue by nicolassharp** [valor-software/ng2-dragula#713]
Hi all. 

Is there something I can subscribe to which will fire when an item is picked up and dropped? 

I'm looking for something like: 

```
dragulaService.dragStart.subscribe((value) => {
     this.dragging$.next(true);
}); 

dragulaService.dragEnd.subscribe((value) => {
     this.dragging$.next(true);
}); 
```

I basically only want to show the drop targets when the drag starts. Thanks!

**Comment by cormacrelf** [comment]
Did you read the docs? All the events you need are right there in https://github.com/bevacqua/dragula#drakeon-events. Subscribe to `drag` and `dragend`.

This way is standard RxJS and doesn't create any hanging subscriptions either:

```typescript
import 'rxjs/add/operator/mapTo';
import 'rxjs/add/operator/merge';
import 'rxjs/add/operator/startWith';
import { Observable } from "rxjs/Observable";

// ...

this.dragging$ = this.dragulaService.drag.asObservable().mapTo(true)
        .merge(this.dragulaService.dragend.asObservable().mapTo(false))
        .startWith(false);
```

**Comment by rmcsharry** [comment]
@cormacrelf I used your exact code above in the ngOnInit of a component. All I want to do is know if the user is dragging and NOT trigger a save, like this, which I put in the blur of an input control:

    this.dragging$.subscribe(result => {
      console.log('dragging:', result);      
      if (!result) this.saveTemplate();
    });

The dragging$ observable usually emits true when a drag starts, but while the user is still dragging it often emits false - even if I only drag 2mm and don't drop.

Is there a guide on how to use these events, because it's not every intuitive. Thanks in advance.

**Comment by cormacrelf** [comment]
There’s a lot more information on dragula itself; it uses native events, but they’re approximately equatable to observables. Remember this library is just a wrapper around dragula, which does not have the best API, but I don’t feel like re-documenting is the best idea. If you get stuck and think it’s different... the source code in this repo is VERY small, you could read it in two minutes and figure out if anything is different than you expect.

I’ll post this on issues from time to time, but this use case is tackled very well by my as-yet-unpublished Angular front-end to `react-dnd`.

**Comment by cormacrelf** [comment]
There you go, I did link to the definitive guide to the events. See the comment you copied code from.

**Comment by cormacrelf** [comment]
Hm, you also seem to be doing subscribe wrong. To check whether someone is currently dragging, you’ll need to subscribe to `dragging` in ngoninit, and save each new value to a local variable, and refer to the latest one in the Blur handler.

If you subscribe inside an event handler, it will not run the subscription handler synchronously, it will wait until a new value is emitted, which offers no guarantees about whether it’ll be the ‘leading edge’ or ‘trailing edge’ of the drag. I don’t know when Blur is fired (before the drag starts? After? Who knows?).

**Comment by rmcsharry** [comment]
@cormacrelf  Thank you so much - those last two paragraphs were esp. enlightening (and kind of obvious now you point it out, lol!).
