### ISSUE TITLE
Drag with icon as handle

### ISSUE THREAD

**Issue by OKrawi** [valor-software/ng2-dragula#715]
Hi , 

Many thanks for your work. 

I am trying to set an icon to be the handle for my draggable item. 

Apparently, I can only drag if the handle span has text in it.

These works perfectly: 
`<span class="handle">Drag</span> 
`and
`<span class="handle">+</span >
`
While this doesn't: 
`<span class="handle"><i class="fa fa-bars" aria-hidden="true"></i></span> 
`
Is there a way to fix this?

**Comment by cormacrelf** [comment]
Have a look with the Inspector and see how big your actual span is. It might be zero height, for whatever reason.

**Comment by OKrawi** [comment]
Hi, 
Thanks for the fast reply.

This also does not work:

```
<span class="handle" style="min-height:30px;min-width:30px">
  <i class="fa fa-bars" aria-hidden="true" style="min-height:30px;min-width:30px"></i>
</span>
```
It is not a height issue.

**Comment by OKrawi** [comment]
No update on this? 

Can you please give a working example on how to style an icon to be a handle? 
I have tried many combinations of adding height, width and padding but none worked. 
Is this even possible with this library? 

Thank you for your work.

**Comment by cormacrelf** [comment]
If it's not a size issue, then ok. But you haven't included any of your code so I can't really guess any better than that, and I'm very busy at the moment, so please keep trying.

**Comment by mgween** [comment]
I just ran into this same solution and found a solution that worked for me. Instead of using
```
moves: function (el, container, handle) {
    return handle.className === 'handle';
}
```
like the example shows, try using
```
moves: function (el, container, handle) {
    return handle.classList.contains('handle');
}
```

**Comment by OKrawi** [comment]
Thank you very much! 
It works like a charm!

This issue can be closed now.

**Comment by DevPrasan1** [comment]
Hi Mgween,
Thanks for your solution.
I have the same issue, but your solution is not working on my project .
 I'm using 
```
    moves: function (el, container, handle) {
        return handle.classList.contains('panel-drag');
      }
```
and my html is 
```
<div class="panel-drag">
         Drag to change order<span><i class="icon-drag ml-2"></i></span>            
</div>
```
it's work on the text but not on icon.
Can you please help.

**Comment by missionraj** [comment]
hello everyone,  
i want the same for  drag with icon but in my case there is nested drag and drop 
i also want my inside child bag to be dragged with the icon

**Comment by chaosbiber** [comment]
The problem with the newer svg icons is the real dom structure and what part you hit with your mouse. Some times it's the `<svg>`, sometimes it's `<path>` (also depending on the icon structure, but that's how it is with fontawesome svg/js edition).
A quick solution for chrome was:
`<span class="fas fa-bars handle">`
with
```
moves: function (el, container, handle) {
    return handle.classList.contains('handle') || 
        handle.parentNode.classList.contains('handle');
}
```
But at least in IE, it returns an empty classList on any svg item and the whole thing fails. So you have to create a little more complex handle check depending on your actual DOM structure and supported browsers.

**Comment by 2advancesolutions** [comment]
https://github.com/bevacqua/dragula#optionsmoves

**Comment by xssharan** [comment]
Thanks worked for me too

**Comment by pjc2007** [comment]
Hi I am just looking at this component, but also only want to drag by using a handle.

My question is, where does the `moves:`come from?
