### ISSUE TITLE
Emit also ES2015/ES6 bundle

### ISSUE THREAD

**Issue by Eddman** [valor-software/ng2-dragula#735]
To have best compatibility with all tools/platforms you should emit also an ES6 bundle.

As a good example see [angular/material2](https://github.com/angular/material2).

Based on `package.json` entries:
- Browsers should use `main` path (UMD package, or minified UMD)
- TypeScript compiler uses `typings` path only
- AOT compiler is using `typings` path to get `*.metadata.json` files
- Rollup uses `module` for tree-shaking

So `package.json` should contain the following entries:
```
{
  "main": "./bundles/ng2-dragula.umd.js", (for all UMD)
  "module": "./bundles/ng2-dragula.es.js", (ES 2015 for tree-shaking tools)
  "es2015": "./bundles/ng2-dragula.es.js", (ES 2015 for tree-shaking tools, for other tools)
  "types": "./index.d.ts" (typings for other tools)
  "typings": "./index.d.ts" (for AOT and TypeScript compilers)
}
```
This config will allow correct AOT, tree-shaking, dynamic browser usage...

Currently you have twice the same ES5 JavaScript (as bundle and also separate files). The separate files are obviously useless. They can fully be omitted.

**Comment by cormacrelf** [comment]
Submit a PR if it's valuable to you. This isn't exceptionally valuable to me at the moment since the entire library weighs about a kilobyte.

**Comment by Eddman** [comment]
Sure. Could you just point me to your build scripts :) Thanks.

**Comment by cormacrelf** [comment]
Mate, even I don't know how our build scripts work. I think they're inverted compared to standard practice; usually the plain package goes on the outside and the `./examples/package.json` refers to `"dragula": "../"` or something, but this has the example repo on the outside with a heap of build scripts to compile a subdirectory into `./dist`. This is part of the reason I can't be bothered!

**Comment by danwulff** [comment]
In case someone wants to tackle this at some point. This is a good reference: https://github.com/filipesilva/angular-quickstart-lib

It builds all the necessary bundles and provides unit, integration jit and integration aot tests.

**Comment by cormacrelf** [comment]
Closing because fixed in v2.
