### ISSUE TITLE
1.5 release not documented

### ISSUE THREAD

**Issue by altschuler** [valor-software/ng2-dragula#739]
1.5.0 has been released on npm, but I can't find any mention of it anywhere else. Is it a mistake or has 1.4 been skipped and if so, what's in 1.5?

Thanks! :slightly_smiling_face:

**Comment by cormacrelf** [comment]
There's nothing new of master compared to yesterday, I think it's just the angular 4 stuff and 1.5 is probably a mistake.

**Comment by altschuler** [comment]
It's still there, might want to pull it off npm to avoid confusion. Closing as you're aware :)

**Comment by cormacrelf** [comment]
Pull it off npm? I'm prett sure discontinuing 1.5 in favour of 1.4 would count as a breaking change requiring a SEMVER version 2.0.0.

**Comment by rgant** [comment]
I think the question is, what is version 1.5? It isn't listed in the CHANGELOG.md nor is there a tag for it on github. Can you clairfy what changes are in this release?

**Comment by cormacrelf** [comment]
I said 'probably' so as to express that I had nothing to do with it. ng2-dragula is a sentient piece of software that releases itself; we can only hope that one day it will reveal its great mysteries in a spewing forth of changelogs and on that day much rejoicing will be had.

In the meantime, I'm sure you could install the npm release and have a look see if it's different. As I said, it's probably just the one or two new commits on master to fix that angular 4 issue.
