### ISSUE TITLE
Loosing items from Array when dragging

### ISSUE THREAD

**Issue by tidusjar** [valor-software/ng2-dragula#742]
Hi!

I'm trying to use dragula but running into an issue.

Can't seem to work out why this isn't working.

So as you can see in this GIF I am dragging a div from one container to another, ondrop` the object disappears and the array becomes undefined.
[![enter image description here][1]][1]

Here is the code I have:

**Main View.html**

    
    <div *ngIf="tvRequests">
        <div class="col-md-4">
            <div class="landing-box">
                <md-card-title>Title</md-card-title>
                <div [dragula]='"requests-bag"' [dragulaModel]="tvRequests.new">
                    <br />
                    <br />
                    <request-card *ngFor="let item of tvRequests.new" [request]="item"></request-card>
                </div>
            </div>
        </div>
    
        <div class="col-md-4">
            <div class="landing-box">
    
                <div [dragula]='"requests-bag"' [dragulaModel]="tvRequests.approved">
                    <br />
                    <br />
                    <request-card *ngFor="let item of tvRequests.approved" [request]="item"></request-card>
                </div>
            </div>
        </div>
    
        <div class="col-md-4">
            <div class="landing-box">
                <md-card-title>Title</md-card-title>
                <div style="border: dashed">
                    <div [dragula]='"requests-bag"' [dragulaModel]="tvRequests.available">
                        <br />
                        <br />
                        <request-card *ngFor="let item of tvRequests.available" [request]="item"></request-card>
                    </div>
                </div>
            </div>
        </div>
    </div>

**Main View.ts**

    import { Component, OnInit } from '@angular/core';
    import { DragulaService } from 'ng2-dragula/ng2-dragula';
    import { RequestService } from '../services/request.service';
    import { ITvRequestModel, IMovieRequestModel, IRequestGrid } from '../interfaces/IRequestModel';
    
    @Component({
        moduleId: module.id,
        templateUrl: './request-grid.component.html'
    })
    export class RequestGridComponent implements OnInit {
    
        constructor(private dragulaService: DragulaService, private requestService: RequestService) {
            this.dragulaService.dropModel.subscribe((value: any) => {
                console.log(value);
                console.log(this.tvRequests.new);
                console.log(this.tvRequests.approved);
                console.log(this.tvRequests.available);
            });
        }
    
        ngOnInit(): void {
            this.requestService.getMovieGrid().subscribe(x => {
                this.movieRequests = x;
            });
            this.requestService.getTvGrid().subscribe(x => {
                this.tvRequests = x;
            });
        }
    
    
        movieRequests: IRequestGrid<IMovieRequestModel>;
        tvRequests: IRequestGrid<ITvRequestModel>;
    
    }

**RequestsGrid<>.ts**

    export interface IRequestGrid<T> {
        available: T[],
        new: T[],
        approved:T[]
    }

The `request-card` component is just some styling and doesn't contain any code.

When I drop as you can see in the `Main View.ts` I am subscribing to the `dropModel` event and logging out to see what is going on.
Here console output for the dragging GIF above:[![enter image description here][2]][2]

Any idea why the item is disappearing? 

Here is a Plunker recreating the issue: http://plnkr.co/edit/U5AjZ0Gqnxq8bAznYueG?p=preview

  [1]: https://i.stack.imgur.com/TELyc.gif
  [2]: https://i.stack.imgur.com/rmQX2.png

**Comment by cormacrelf** [comment]
Welcome to ng2-dragula! You've made the evergreen, classic blunder of including anything apart from draggable elements in your containers. Remove the <br/> elements, and you'll be on your way! If you wanted to make sure there was room in the container so dragula can find a spot, just add padding.

**Comment by tidusjar** [comment]
Amazing! Thanks!

**Comment by StickNitro** [comment]
I have a similar issue, I have a StackBlitz here (https://stackblitz.com/edit/angular-cm2c1s)

I can drag the 'cog' into one of the grid cells below and that adds to the array (you will see 'Some Widget' display in the cell), but when dragging 'Some Widget' to another cell I am getting an undefined error.

In the second move from one grid cell to another the resulting output from `dropModel` has the `item` property `undefined` and the `targetModel` is an array with an undefined element  (`[undefined]`).

I also have a problem adding additional items to a pane, it seems the `dragulaModel` just gets overwritten with the new model so I only ever have one item in the array
