### ISSUE TITLE
Using trackBy with ngFor causes issues

### ISSUE THREAD

**Issue by Tiedye** [valor-software/ng2-dragula#743]
The model updates correctly, but the view does not.  See https://plnkr.co/edit/34vxuev8SZu9SFjGOm08?p=preview

**Comment by cormacrelf** [comment]
I think you're another poor soul fallen victim to bad Angular API design. trackBy functions take two arguments; the first is an index, the second is the object found by ngFor. It should absolutely be the other way round, but it's not, and all your trackBys are returning 'undefined'. Add a dummy first argument to hold the index.

**Comment by cormacrelf** [comment]
I'm on mobile and can't properly edit the plunk, so close the issue if I'm right.

**Comment by Tiedye** [comment]
Your right!  Closing it now

**Comment by mallagopi999** [comment]
@Tiedye  if we use trackBy the view is not updating. If we don't use trackBy we can't edit the item properly. We are able to edit only one character at a time.
