### ISSUE TITLE
While dragging, Image inside goes bigger?

### ISSUE THREAD

**Issue by sudhirroy-tudip** [valor-software/ng2-dragula#744]
I have ul where li is in for loop. In each li, I have images and some static data. When I drag, Image change it's shape and goes bigger. How can we set size?

**Comment by eyalhakim** [comment]
i am experiencing the same behavior

**Comment by cormacrelf** [comment]
Use your debugger and discover that the copy is inserted into the <body> tag with style attributes to the effect of manual positioning on screen.

If you had css matching .container .dragItem, then it won't match an element in body > .dragItem.
