### ISSUE TITLE
CSS Transitions (animations) on the DIVs being moved when an element is being dropped / sorted

### ISSUE THREAD

**Issue by paw1** [valor-software/ng2-dragula#745]
Is it possible to set css transitions on the DIVs beween which the element is being dropped or sorted?

Example : 

```<div id="container">
<div id="first"></div>
<div id="elementBeingDropped" class="gu-transit"></div>
<div id="third"></div>
```

Here, I would like to have the first and thrid DIVs to have a smooth transition while i'm dragging / sorting the elementBeingDropped div.

Thanks.

**Comment by cormacrelf** [comment]
No. They're not being moved with CSS, they're being re-ordered in the DOM. From a CSS point of view, nothing has changed, so you can't animate anything. This is a limitation of Dragula.
