### ISSUE TITLE
Breaks Angular on fresh install

### ISSUE THREAD

**Issue by alshdavid** [valor-software/ng2-dragula#746]
Adding ng2-dragula to a fresh project breaks the project

Windows 10
Angular CLI
Node 8.1.2
NPM 5.0.3

`ng new`
`ng serve`
`npm install ng2-dragula --save`
`ng serve`
*breaks*

I have tried removing `node_modules` and running `npm i` again
I have tried removing `ng2-dragula` from the `package.json` and the problem persists.

I'm about to test this on another PC to confirm that it's not my configuration.

EDIT: Works on my second computer

![image](https://user-images.githubusercontent.com/12656294/27574566-12f87b88-5b6b-11e7-81e9-7af5279b94b3.png)

**Comment by cormacrelf** [comment]
Uninstall and reinstall @angular/cli globally. That might help. It's not this repo's fault. The error messages you show have nothing to do with ng2-dragula.
