### ISSUE TITLE
Informations version 1.5.0

### ISSUE THREAD

**Issue by vaidd4** [valor-software/ng2-dragula#747]
Hello,
I'm updating some of my modules, and I saw that ng2-dragula jumped from 1.3.1 to 1.5.0.
But there is no tags for it on github and there is only 2 commit on the master branch.
Is there any Changelog or even a bump commit for this version ?

Thanks in advance

**Comment by vaidd4** [comment]
After testing the 1.5.0 resolve the `requires a peer of` warnings on `npm install`.

So the version should reflect this commit : https://github.com/valor-software/ng2-dragula/commit/9a56867cb234ad467f5b1ca192d4aaea9a4a33a6

Is it possible to have a changelog entry or a tag for this version ?

@cormacrelf ?

**Comment by cormacrelf** [comment]
Closing because v1.5.0 tag exists now. I'm not sure if it's accurate, but I'm steamrolling it with 2.0 soon anyway.
