### ISSUE TITLE
[Query] How to correctly install a fork?

### ISSUE THREAD

**Issue by paw1** [valor-software/ng2-dragula#748]
While waiting for PR #704 to get merged, I thought I'd continue development by forking the project and installing the fork.

Steps taken : 

0. uninstalled existing ng2-drghula npm uninstall ng2-dragula --save
1. Forked the project to my github repo
2. Made the changes, changed version number to 2.0.0, and committed the changes
3. Did npm install https://github.com/paw1/ng2-dragula.git --save

Now my node_modules directory contains ng2-dragula-base. However, the src directory only conatins 1 file i.e. package.json. What am i doing wrong? Sorry if this is a noob question, but I've spent quite some time trying to get this working.

**Comment by cormacrelf** [comment]
You need to build the project and commit the bundled up output as well. This is a quirk of this project.

**Comment by paw1** [comment]
@cormacrelf Thank you, got it working. For future reference, anyone trying this would also need to install package "ngm". Clone module -> make your changes -> npm install to install the module dependencies -> install module ngm and run the build script i.e. npm run-script build -> commit to your repo -> npm install your fork into your project.
