### ISSUE TITLE
TypeError: dragula_class_1.dragula is not a function in angular 2

### ISSUE THREAD

**Issue by Gajendrasinh** [valor-software/ng2-dragula#749]
All the step which declair i have follwed but i m getting error can you please help me so solve this
TypeError: dragula_class_1.dragula is not a function
systemjs.config.js

/**
 * System configuration for Angular samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
  System.config({
    paths: {
      // paths serve as alias
      'npm:': 'node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      'app': 'app',

      // angular bundles
      '@angular/animations': 'npm:@angular/animations/bundles/animations.umd.js',
      '@angular/animations/browser': 'npm:@angular/animations/bundles/animations-browser.umd.js',
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser/animations': 'npm:@angular/platform-browser/bundles/platform-browser-animations.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/router/upgrade': 'npm:@angular/router/bundles/router-upgrade.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
      '@angular/upgrade': 'npm:@angular/upgrade/bundles/upgrade.umd.js',
      '@angular/upgrade/static': 'npm:@angular/upgrade/bundles/upgrade-static.umd.js',

      // other libraries
      'rxjs':                      'npm:rxjs',
      'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js',
       /** Path for ng2-file-upload */
      'ng2-file-upload' : 'npm:ng2-file-upload' ,
      'ng2-pdf-viewer': 'node_modules/ng2-pdf-viewer',
      'pdfjs-dist': 'node_modules/pdfjs-dist',
       'ng2-dragula': 'node_modules/ng2-dragula',
       'dragula': 'node_modules/ng2-dragula'
      /** Path for ng2-file-upload */
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      app: {
        main: './main.js',
        defaultExtension: 'js',
        meta: {
          './*.js': {
            loader: 'systemjs-angular-loader.js'
          }
        }
      },
      rxjs: {
        defaultExtension: 'js'
      },
      'ng2-pdf-viewer': { main: 'dist/index.js', defaultExtension: 'js' },
      /** Configuration for ng2-file-upload */
      'ng2-file-upload' : { 
        main: './ng2-file-upload.js',
        defaultExtension: 'js'
      },
      'ng2-pdf-viewer': { main: 'dist/index.js', defaultExtension: 'js' },
      'pdfjs-dist': { defaultExtension: 'js' },
      'ng2-dragula': { main: 'ng2-dragula.js', defaultExtension: 'js' }
      /** Configuration for ng2-file-upload */
    }
  });
})(this);

**app.module.ts**

import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule,ReactiveFormsModule  } from '@angular/forms'; // <-- NgModel lives here
import { RouterModule } from '@angular/router';
import { AppComponent } from './app.component';
import { HeroDetailComponent } from './hero-detail.component';
import { RegistationComponent } from './registration/registration.compoent';
import { LoginComponent } from './login/login.component';
import { AddUserComponent } from './add-user/add-user.component';
import { AppRoutingModule }     from './app-routing.module';
import { FileManagerComponent } from './file-manager/file-manager.component';
import { ChangePasswordComponent } from './change-password/change-password.component';
import { ForgetPasswordComponent } from './forget-password/forget-password.component';
import { UserProfileComponent } from './profile/profile.component';
import { DashboardComponent } from './dashboard/dashboard.component';
import { FilePreviewComponent } from './file-preview/file-preview.component';
import { FooterComponent } from './footer/footer.component';
import { ApprovedDocsComponent } from './approved-docs/approved-docs.component';
import { fileUpload }  from './file-upload/file-upload' ;
import { CompanyRegistrationComponent } from './company-registration/company-registration.component';
import { SignaturePadComponent } from './sign-pad/sign-pad.component';   
import { PdfViewerComponent } from 'ng2-pdf-viewer';
import { HttpModule , JsonpModule }    from '@angular/http';
import { TruncatePipe } from './exponential-strength.pipe';
import { FileSelectDirective, FileDropDirective } from 'ng2-file-upload';
import { DragulaModule , dragula} from 'ng2-dragula';
import { Uploader }      from 'angular2-http-file-upload';

@NgModule({ 
    imports: [
    BrowserModule,
    FormsModule, // <-- import the FormsModule before binding with [(ngModel)]
    AppRoutingModule,
    ReactiveFormsModule,
    HttpModule,
    JsonpModule,
    DragulaModule
  ],
  declarations: [
    AppComponent,
    HeroDetailComponent,
    PdfViewerComponent,
    RegistationComponent,
    LoginComponent,
    AddUserComponent,
    FileManagerComponent,
    ChangePasswordComponent,
    ForgetPasswordComponent,
    UserProfileComponent,
    DashboardComponent,
    FilePreviewComponent,
    FooterComponent,
    ApprovedDocsComponent,
    CompanyRegistrationComponent,
    fileUpload,
    FileSelectDirective,
    SignaturePadComponent,
    TruncatePipe,
    //DragulaModule
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }

**file-preview.component.ts**

import { Component } from '@angular/core';
import { DataService } from '../services/dataservice';
import {ActivatedRoute} from '@angular/router';
import { DragulaService} from 'ng2-dragula/ng2-dragula';

@Component({
    selector: 'file-preview',
    templateUrl: './file-preview.component.html',
    styleUrls: ['./file-preview.component.css'],
    providers :[DataService, DragulaService]
})
export class FilePreviewComponent {
  docsID: any;
  getDocsById : any;
  docsReps : any;
  public many:Array<string> = ['The', 'possibilities', 'are', 'endless!'];
  public many2:Array<string> = ['Explore', 'them'];
  constructor( private dataService: DataService, private route: ActivatedRoute, private dragulaService:DragulaService) {
      this.docsID = route.snapshot.params['id']; // 3

      this.getDocsById = this.dataService.getDocByDocID(this.docsID).subscribe(
        data => {
            if (data.success) {
                this.docsReps = data.data;
            } else {
                console.log('Error : ', data.message);
            }
        });
        
    
        dragulaService.dropModel.subscribe((value:any) => {
            //this.onDropModel(value.slice(1));
        });
        dragulaService.removeModel.subscribe((value:any) => {
            //this.onRemoveModel(value.slice(1));
        });
}

  ngOnInit() {
  }
}

**Error:**

errors.ts:42 ERROR Error: Uncaught (in promise): TypeError: dragula_class_1.dragula is not a function
TypeError: dragula_class_1.dragula is not a function
    at DragulaDirective.ngOnInit (http://localhost:3000/node_modules/ng2-dragula/components/dragula.directive.js:40:42)

![image](https://user-images.githubusercontent.com/10431380/27686626-7b2098f8-5c88-11e7-979d-f937a845f756.png)

**Comment by cormacrelf** [comment]
Closing because dropping Ng 2 support.
