### ISSUE TITLE
dragulaService.removeModel not syncing with model data 

### ISSUE THREAD

**Issue by peb7268** [valor-software/ng2-dragula#751]
So at first I was setting up the dragula service and init'ing everything in the constructor. I fetch my data later though when my redux store is hydrated from the server, I then set my data property to that hydrated value. 

When I do this, my removeModel method is not syncing the model like dropModel does. Do I need to rebind some events or something in the dragula service once I hydrate my data and update the model?

**Comment by cormacrelf** [comment]
If you're using redux, I have to guess that you're modifying an array that's meant to be immutable. In general you cannot use dragulaModel and friends with an immutable data pattern. They modify array contents. I would advise not using them at all for now, instead using your own domIndexOf to implement dragulaModel's functionality and fire redux actions based on regular dragula events.

**Comment by cormacrelf** [comment]
In v2, just don’t use two way binding and your problems will go away.
