### ISSUE TITLE
Cannot install and run valor-software/ng2-dragula demos

### ISSUE THREAD

**Issue by lohiarahul** [valor-software/ng2-dragula#752]
I cloned the repo as is, made no changes whatsoever, installed all packages and attempted a npm start. This is what I get. Any ideas on how to proceed?

> ERROR in Error encountered resolving symbol values statically. Could not resolve ng2-dragula relative to D:/clones/ng2-dragula/demo/src/app/app.module.ts., resolving symbol DragulaDemoMod
> ule in D:/clones/ng2-dragula/demo/src/app/app.module.ts, resolving symbol DragulaDemoModule in D:/clones/ng2-dragula/demo/src/app/app.module.ts
> 
> ERROR in multi webpack-dev-server/client?http://localhost:3200 ./demo/src/main.ts
> Module not found: Error: Can't resolve 'webpack-dev-server/client?http://localhost:3200' in 'D:\clones\ng2-dragula'
>  @ multi webpack-dev-server/client?http://localhost:3200 ./demo/src/main.ts
> ![2017-07-14 16_10_48-app module ts ng2-dragula visual studio code](https://user-images.githubusercontent.com/2647136/28200374-0ca329c6-68af-11e7-9edf-5e930ce0ddfd.png)
> 
> ERROR in multi webpack-dev-server/client?http://localhost:3200 ./demo/src/main.ts
> Module not found: Error: Can't resolve '@ngtools/webpack' in 'D:\clones\ng2-dragula'
>  @ multi webpack-dev-server/client?http://localhost:3200 ./demo/src/main.ts
> webpack: Failed to compile.

**Comment by DavidKroukampDariel** [comment]
I experienced the same thing.
Just ran `npm install ng2-dragula --save` and now I am able to run the demo :)

**Comment by lohiarahul** [comment]
I feel so stupid now..Thanks mate. Cheers..
