### ISSUE TITLE
How to Drag only one item per container in ng2-dragula

### ISSUE THREAD

**Issue by jesus-novologic** [valor-software/ng2-dragula#753]
I generate different containers automatically from arrays, this is my app-component.ts:

```js
columnItems = [
        {
            name: 'Name',
        },
        {
            name: 'User'
        },
        {
            name: 'Email'
        }
    ];
```

An the second Array:

```js
column = [
        {
            name: 'One Column',
        },
        {
            name: 'Two Column'
        },
        {
            name: 'Three Column'
        },
        {
            name: 'Four Column'
        }
    ];
```

on my app-component.html I have this code:

```html
                <div class="wrapper_mapping">
                    <div class="container_mapping system_column" [dragula]="'mapping-columns'">
                        <h5 class="no-drag">System Columns</h5>
                        <div *ngFor="let columnItem of columnItems">{{ columnItem.name }}</div>
                    </div>
                    <div class="container_mapping" [dragula]="'mapping-columns'" *ngFor="let c of column">
                        <h5 class="no-drag" style="display: block;"> {{ c.name }}</h5>
                    </div>
                </div>
```

These generate a 5 columns with the columnsItem on the left and 4 columns to the right, I want to allow drag and drog elements from the left column to each on the right, I use a html tag to create headers and the class "no-drag" makes the header no draggable, two questions:

How could I make the header element fixed, I mean prevent drop elements up the header, I would like to drop elements only above the header?
Also I want to drop only one element for each container on the right, every container on the right should only have one element, restrict drop more than one into it.
Thanks

**Comment by iariasfallas** [comment]
Hi @jesus-novologic.
Any update?
