### ISSUE TITLE
Local images are not displaying in npmjs copy of the package - w/ suggested fix

### ISSUE THREAD

**Issue by MikeBeaton** [valor-software/ng2-dragula#755]
Hi,

I noticed that the local images 

https://github.com/bevacqua/dragula/blob/master/resources/logo.png
https://github.com/bevacqua/dragula/blob/master/resources/demo.png

from [README.MD](https://github.com/valor-software/ng2-dragula/blob/master/README.md) are not displaying correctly in the copy of the README at https://www.npmjs.com/package/ng2-dragula.

From looking at the issue myself plus [this SO answer](https://github.com/npm/npm/issues/12302), I think that the two image links would just need to be changed to

https://raw.githubusercontent.com/bevacqua/dragula/master/resources/logo.png
https://raw.githubusercontent.com/bevacqua/dragula/master/resources/demo.png

though I don't have any straightfoward way to test this for sure.

I have a quick PR of this change which I could submit, if that sounds correct and of use?

Thanks,
Mike

**Comment by cormacrelf** [comment]
I'm not sure why you care, but I'm glad someone does. Go for it.

**Comment by MikeBeaton** [comment]
I guess it doesn't matter much! I just came across the repo on npmjs.com before GitHub. It looks like a useful project, thanks. Here's the PR any road up! #764
