### ISSUE TITLE
Draggble items and droppable container

### ISSUE THREAD

**Issue by opium-draga** [valor-software/ng2-dragula#756]
Is dragula has posibility to do this functionality? https://www.screencast.com/t/K7dMeubk7 (on video i use this module https://www.npmjs.com/package/ng2-drag-drop)

I have list of items what i can dragg to some droppable container, i have spend a lot of time to realize this functionality within dragula, but there is a list of problems:
if do it via creating
- two difference bags, then droppable bag cannot detect when he is overlapped
- one bag, then how to set difference options for one bag, for disable moves for one container and enable it for another

i really don't want have difference modules for drag n drop (one for option above, and another for sorting)

**Comment by cormacrelf** [comment]
Just read the Dragula documentation.
