### ISSUE TITLE
How can I rollback a drag&drop operate?

### ISSUE THREAD

**Issue by zhaochy1990** [valor-software/ng2-dragula#757]
In my scenario, a user drag an object from src to dst. When he drop, some validation will be checked. If passed, continue, otherwise, this block should be put back to the src bag.

src bag-->htmlblock-->drag-->onDrop()
```
onDrop(){
    try{
        //do something
    }catch(e){
        // some error happened, how can I rollback this D&D operation?
    }
}
```
so how can I rollback this operation?
ps. I can't listen to the onDrag event, because I have to know where the htmlblock dropped.

**Comment by utiq** [comment]
@zhaochy1990 did you find out how to do it?

**Comment by zhaochy1990** [comment]
@utiq we use react now

**Comment by cormacrelf** [comment]
#795
