### ISSUE TITLE
Unit test, fake drop event?

### ISSUE THREAD

**Issue by fmontes** [valor-software/ng2-dragula#758]
Hi,

Is there a way to "fake" a drop event in unit tests?

Regards.

**Comment by woontsoudev** [comment]
I tried and its impossible, someone can help with this?

**Comment by cormacrelf** [comment]
It's impossible afaik. You'd need to emulate mouse events at the correct locations, which is ridiculous. I keep saying I'm going to rewrite this, that would be one of the goals. I think it can be done.

**Comment by cormacrelf** [comment]
V2 is absolutely not a rewrite. However, I did create two classes for doing exactly this:

- DrakeFactory, which is an optional DI dependency of DragulaService. By default, DragulaService just uses `new DrakeFactory(dragula)` but you could `{ provide: DrakeFactory, useValue: new DrakeFactory((containers, options) => ...) }`
- MockDrake, which is just a really dumb drake with no DOM manipulation, but that can fire drake events with the `emit` function. Put a MockDrake in the ... above, and keep a reference to it.

Combined, you are almost there on tests. You do have to do source.removeChild and target.insertBefore/appendChild yourself, which can be tricky. But the tests for the library itself are a good guide. (There are a lot of them.)

I will make sure these are part of the public API.

- - -

Note:

The above is pretty difficult to use, and you have to emulate the whole of the dragula library in plain DOM calls. **Arguably, you still can not rely on the tests as they make too many simplifications of what Dragula does.** If you care about unit tests, I would recommend not using ng2-dragula at all, and instead use the more powerful [`angular-skyhook`](https://cormacrelf.github.io/angular-skyhook/). It has a pluggable backend system and doesn’t require DOM manipulation to work, so you can unit test your components in complete isolation with the test backend. There is a testing example in the github repo. There is also a WIP replacement for dragula-style functionality where you can swap out all the business logic and also have complete rendering control (you can provide a template to render for following the mouse that’s entirely different from what you picked up... morph items as they appear in lists with different templates... dope.
