### ISSUE TITLE
when copy:true, angular (click) - event is lost in the new div

### ISSUE THREAD

**Issue by synapps16** [valor-software/ng2-dragula#759]
i use ionic 2 and want to copy that element with ng2-dragula:

```
<div [dragula]='"some-bag"'>
  <button ion-button  (click)="addAtr()">
  </button> 
</div>
```
when i set copy: true, the sibling div element looks like following:

```
  <button ion-button>
  </button> 
```
(click)="addAtr()" seems to be lost in the way.

What can I do?

**Comment by CrackerakiUA** [comment]
have you solved your case?

**Comment by cormacrelf** [comment]
Refer to commentary in #836
