### ISSUE TITLE
Using keyboard events with Dragula for Accessibility

### ISSUE THREAD

**Issue by MikeLavella** [valor-software/ng2-dragula#763]
I'm looking into implementing keyboard events for accessibility with Dragula to change the position of items in a list.  I would want to be able to change the order by dragging and using the keyboard arrows.  I need to kebyoard tab to a dragula list, then tab to the item in that list that I want to move, select it with space/enter and use the mouse up or down arrow to re-position it. The enter or space key would lock the selected item into place. Unless I'm missing something, it looks like Dragula only detects mouse type events such as dragging?  I wasn't clear on how to tie a keyboard event into the Dragula functionality.  Anyone have any advice on the best way to approach this? 

Thanks!

**Comment by cormacrelf** [comment]
Just ignore dragula and implement it yourself. By reordering the array. Use the library ‘mousetrap’ to make it easier. Your biggest problem is that lifting and putting down is a somewhat complex state machine: enter only means put down when you’re already lifted. For that reason I would implement it with `@ngrx/store` — it will be easier to keep track of state that way. State would look like:

```ts
{
    selectedID: number | null;
    lifted: boolean;
    beforeLift: Item[] | null;
    items: Item[];
}
```

Trigger actions with mousetrap, like ‘DownArrow’, then respond differently given whether you are lifted or not (lifted -> move item, not -> select below) in your ngrx reducer.

**Comment by cormacrelf** [comment]
(This will be easier in v2 since the library no longer internally mutates arrays. It’s easier to use with ngrx and async dragulaModels.
