### ISSUE TITLE
Mirror element taking fix left value in horizontal items.

### ISSUE THREAD

**Issue by kundan-kumar1993** [valor-software/ng2-dragula#765]
If I am rendering horizontal item and dragging so mirror element taking a fix left property value which is equals to first item in row.

**Comment by cormacrelf** [comment]
I assume you mean you want the element to follow your mouse on one axis only, and stay locked on another axis? Not possible with dragula, AFAIK. Maybe search issues on bevacqua/dragula.

You can do it with https://cormacrelf.github.io/angular-skyhook/

**Comment by hughanderson4** [comment]
How is dragging vertically not supported?  We have `direction` parameter but it seems to be ignored?!
