### ISSUE TITLE
Example for nested ngFor doesn't work - moving whole column 

### ISSUE THREAD

**Issue by RalfF1** [valor-software/ng2-dragula#766]
The nested ngFor example on the demo page doesn't work (last example on this page: 
http://valor-software.com/ng2-dragula. 
It seems that there is some code missing and I'm not able to reconstruct it.
Any idea how to get the example running - means to move the whole "Group A" or "Group B" column?

Thanks in advance for any idea.
Ralf

**Comment by dennis82m** [comment]
any update on this?

**Comment by RalfF1** [comment]
We did following workaround:

HTML:
        <div>
            <div [dragula]='"parent-bag"' [dragulaModel]='cards'>
                <div class='container' id="col-{{c}}" *ngFor="let cols of cards; let c = index">
                    <div>
                         <div class=”columnDraggable” >……..
                    </div>

                    <div class="rows" [dragula]='"child-bag"' [dragulaModel]='cards[c]'>
                        <div class="itemlist" *ngFor="let row of cols; let r = index">
                            <div class=”card” >……..
                        </div>
                  </div>
                </div>
            </div>
        </div>

Component:
_dragulaService.setOptions('parent-bag', {
      revertOnSpill: true,
      removeOnSpill: false,
      moves: function (el, container, handle) {
        if (handle.className === 'columnDraggable') {
          return handle.classList.contains('columnDraggable');
        } else {
          return false;
        }
      }
    });

    _dragulaService.setOptions('child-bag', {
      removeOnSpill: false,
      moves: function (el, container, handle) {
        if (handle.className === 'card') {
          return handle.className = handle.className;
        }
        return false;
      }
    });

And finally we deactivated following line in Dragula.provider.ts (I do not know for what this line is used for):
target.removeChild(dropElm); // element must be removed for ngFor to apply correctly  

Hope this helps

**Comment by rabierAmbroise** [comment]
Are you trying to achieve that : https://codepen.io/sherbrow/pen/rVZoRp ?

**Comment by RalfF1** [comment]
Looks like that this was what we wanted to achive.
We solved it like this:
![drag01](https://user-images.githubusercontent.com/14012036/33142695-9e90d5b2-cfb7-11e7-8014-d552d9c0f4fc.gif)

**Comment by jjreisfl** [comment]
Example with ngfor working. might be usefull for someone
https://angular2dragula.stackblitz.io

**Comment by cormacrelf** [comment]
closed in 8b10353

**Comment by s-gbz** [comment]
This is distantly related to #663 (at least by topic of nested groups & my struggle while searching).
Check out a possible solution that worked for [my case](https://github.com/valor-software/ng2-dragula/issues/663#issuecomment-846930080)
