### ISSUE TITLE
Remove an element while copySortSource is true

### ISSUE THREAD

**Issue by fttx** [valor-software/ng2-dragula#767]
I need to copy the element when is dragged from A to B, but i also need to remove it when it is dragged from B to anything else

Nothing happens when i call remove() while copySortSource is true, because of the way dragula is made -> https://github.com/bevacqua/dragula#optionscopy.

But at least when i'm not using angular, i can always remove elements by accessing the DOM. 
Is there any workaround?

**Comment by fttx** [comment]
I solved by removing copy and copySortSource, and using a ngFor.
Every time an element is dropped out from A, i reassign to the array the original content, and everything else works as expected by it self.

Example: 
https://github.com/fttx/barcode-to-pc-server/blob/bbaaa0913b887f4d9392e7d4db5c2ddccfeea307/src/app/pages/main/main.component.ts#L73
https://github.com/fttx/barcode-to-pc-server/blob/bbaaa0913b887f4d9392e7d4db5c2ddccfeea307/src/app/pages/main/main.component.html#L61

There is only a detail that i don't like: when i start dragging out an element from A, its "shadow" disappears from inside a

**Comment by cormacrelf** [comment]
Ref #282
