### ISSUE TITLE
Confirming before drop not working with observable

### ISSUE THREAD

**Issue by NingenJanai** [valor-software/ng2-dragula#769]
I have the following code where the drop subscription gets mapped to a subscription from a confirm service I have created and works fine in all other cases:

```
this.dragulaService.drop
            .switchMap(value => {
                return this.modalService.confirm('Confirm', 'Are you sure')
            })
            .filter(res => res == false)
            .subscribe(res => {
                this.dragulaService.find('my-bag').drake.cancel(true);
            });
```

The problem is that the drake.cancel is not working if I do it inside the subscribe method, any work around?

Thanks in advance

**Comment by cormacrelf** [comment]
What does ‘not work’ mean? Has no effect? I’m guessing that’s because asking the modal service is asynchronous, and cancelling has to happen synchronously (I think). There isn’t a way to cancel asynchronously as far as I’m aware. But you could revert the drop.

**Comment by NingenJanai** [comment]
Thanks, yes, that seems to be the issue, I solved it by saving the model state before the drop and reverting if afterwars if the user cancels it with the modal.

**Comment by mmbassetto** [comment]
@NingenJanai How u do that?
