### ISSUE TITLE
Need to stop sorting of draggable elements

### ISSUE THREAD

**Issue by CoreJADeveloper** [valor-software/ng2-dragula#772]
Hi!

Thanks for such a beautiful work.

I need help to implement my requirements. I want to sort my copied element to dropped area but not in dragged elements too.

So i think `copySortSource:true` is the way. But it sorts elements in both drag and drop side.

Does `copySortSource` function has parameters like we get for `copy` -

`copy: function(el,source) {
       return source.classList.contains('no-drop');
 },`

**Comment by karansood** [comment]
@CoreJADeveloper Incase this is still needed, check [282](https://github.com/valor-software/ng2-dragula/issues/282#issuecomment-224427939).
