### ISSUE TITLE
reorder columns of a grid in ionic 3

### ISSUE THREAD

**Issue by vikceo** [valor-software/ng2-dragula#774]
i was trying to implement drag and drop functionality using it.
my use case is a ion-grid having a single ion-row with 10 -15 ion-col.  Right now on desktop the col flows down on the screen depending upon the screen width as expected.

however, i want these to be able to reorder by end user by simply drag drop. 

all the examples i see are using divs or list. is it possible and supported?

**Comment by cormacrelf** [comment]
Have you tried it? I don’t see any reason why it wouldn’t, but you’d have to switch the ‘direction’ property on the Drake manually as the columns collapse into rows.

**Comment by viksakshum** [comment]
Yes it did work

**Comment by adibro500** [comment]
hello i am not able to implement column reordering using ng2-dragula. The rows do get reordered but not the columns. thanks in advance
