### ISSUE TITLE
after drag and drop how do I save the new order in an array?

### ISSUE THREAD

**Issue by fayeyen** [valor-software/ng2-dragula#775]
I use the drag and drop to rearrange the posting images in an reactive form. After the user rearrange how to save this in new array?

**Comment by learnuser521** [comment]
If your ngFor is compiled from array, you may wish to have it synced. For that purpose you need to provide model by setting the dragulaModel attribute on the bag element.

<ul [dragula]='"bag-one"' [dragulaModel]='items'>
  <li *ngFor="let item of items"></li>
</ul>

**Comment by aipirvu** [comment]
For `"ng2-dragula": "2.1.1"` it seems that the model no longer gets updated. I have a similar structure:

```html
<div [dragula]="bagName" [dragulaModel]="widgets">
    <div *ngFor="let widget of widgets">
       ...
    </div>
</div>
```

**Comment by cormacrelf** [comment]
Read the v2 upgrade guide.

**Comment by eieimon** [comment]
@cormacrelf  I use [(dragulaModel)] with upgrade guide documentation and got the correct array order in return but I got a problem that the items don't arrange in UI view. If I remove **[(dragulaModel)]**, it arranges in UI view but I don't got new order array.

**#Angular - 7.2.15** **#ng2-dragula - 2.1.1**

```
<div dragula="DRAGME" [(dragulaModel)]="itemLists">
   <div *ngFor="let crop of itemLists; trackBy: trackUpdate;">
      <span *ngIf="isDrag" class="handle"></span>`
      <div>...</div>
   </div>
</div>
``` 


```
let options: DragulaOptions = {
   moves: (el, source, handle) => {
      return handle.className.includes('handle')
   }
}
this.dragulaService.createGroup("DRAGME", options);

this.subs.add(this.dragulaService.dropModel("DRAGME")
  .subscribe(({ sourceModel, targetModel, item }) => {
    console.log(sourceModel)        // get the correct arrange array
  })
);
```
