### ISSUE TITLE
Update dragula configuration on dragulaOptions change

### ISSUE THREAD

**Issue by abdulkareemnalband** [valor-software/ng2-dragula#776]
angular          : 4.3.6
ng2-dragula   : 1.5.0
dragula          : 3.7.2
chrome          : 61.0.3163.100

Update dragula configuration on `dragulaOptions` change
```ts
class SomeComponent implements AfterContentInit {
     public dragOptions = { 
       // some options
     };
     @ViewChild('container')
     private container:ElementRef;
     ngAfterContentInit(){
         this.dragOptions = Object.assign({},
                 this.dragOptions,
                 {mirrorContainer: this.container.nativeElement});
         // after this dragula configutation should update 
   }
}
```

template
```html
<div dragula='someid' [dragulaOptions]="dragOptions" #container>
    <div *ngFor="..."></div>
</div>
```

This is required because we dont get container reference before dragula is created

**Comment by cormacrelf** [comment]
Actuall, updating with a new options object isn't possible to do in-library. Dragula doesn't expose any way of doing this, at least not with the ability to revert to defaults.

You could drop the `{}, ` from your Object.assign, that might work. Because it would modify the existing object. But it's up to you.

**Comment by cormacrelf** [comment]
Update: keeping a reference to the options object and simply updating it works.

https://stackblitz.com/edit/ng2-dragula-776?file=src%2Fapp%2Fapp.component.ts (scroll down).

**Comment by cormacrelf** [comment]
Update: keeping a reference to the options object and simply updating it / Object.assigning onto it works.

https://stackblitz.com/edit/ng2-dragula-776?file=src%2Fapp%2Fapp.component.ts (scroll down).

**Comment by cormacrelf** [comment]
FWIW, still works in v2.

https://stackblitz.com/edit/ng2-dragula-781-776-v2?file=src%2Fapp%2Fsome.component.ts
