### ISSUE TITLE
Demo isn't running

### ISSUE THREAD

**Issue by Michel73** [valor-software/ng2-dragula#777]
I did following:
1. Clone the `ng2-dragula`-repo
2. `npm install`
3. `npm run build`
4. `npm run link`
5. `npm start`
and get the error:
```ERROR in ./demo/src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/home/vagrant/git/ng2-dragula/demo/src'
 @ ./demo/src/main.ts 5:0-82
 @ multi webpack-dev-server/client?http://localhost:4200 ./demo/src/main.ts
webpack: Failed to compile.
```

**Comment by hatemzidi** [comment]
hi, 
i just upgrade @angular/cli to the latest version ... seems to be working fine.

**Comment by swirlsky** [comment]
Run `npm i enhanced-resolve@3.3.0` inside _ng2-dragula_. This should help.

**Comment by Michel73** [comment]
@swirlsky thanks, that helped

**Comment by bownie** [comment]
Tried the above but still have the same error as reported at the top. Running some modern angular-cli and I'm wondering if this is interfering?

Your global Angular CLI version (1.4.1) is greater than your local
version (1.0.0). The local Angular CLI version is used.

To disable this warning use "ng set --global warnings.versionMismatch=false".
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0
node: 8.5.0
os: darwin x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/compiler-cli: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/language-service: 2.4.3
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/router: 3.4.3
@angular/tsc-wrapped: 0.5.1
@angular/cli: 1.0.0
