### ISSUE TITLE
Setting [dragula] to null doesn't disable dragging

### ISSUE THREAD

**Issue by JosephSKh** [valor-software/ng2-dragula#784]
I need to disable draggin in a certain state and setting [dragula] to null OR undefined doesn't do so

any ideas?
thx

**Comment by josiahaltschuler** [comment]
Hi @JosephSKh. I did this:

1. Label the elements that you want to disable with their own class, like class="no-drag"

2. Set the "moves" option by calling the "setOptions" service in your constructor like this:

`constructor(private dragulaService: DragulaService) {
    dragulaService.setOptions('my-dragula-bag', {
      moves: (el, source, handle, sibling) => !el.classList.contains('no-drag')
    });
}`

**Comment by JosephSKh** [comment]
@josiahaltschuler thank you for your reply, yes actually I've done this at last, but it just wasn't the solution I want to head to because of some requirements, I still need to fix this later , but thx man for your solution :)

**Comment by josiahaltschuler** [comment]
@JosephSKh No problem!

**Comment by renehamburger** [comment]
Another (and probably cleaner) way of achieving the same is to provide two instances of the wrapper element, one with and one without dragula attributes, and move the content of the wrapper into an `<ng-template>` (or <template> in Angular2), e.g.:

```html
<div *ngIf="draggable"
     [dragula]="bagName"
     [dragulaModel]="collection">
  <ng-container *ngTemplateOutlet="items"></ng-container>
</div>
<div *ngIf="!draggable">
  <ng-container *ngTemplateOutlet="items"></ng-container>
</div>
<ng-template #items>
  <ng-container *ngFor="let item of collection">
    ...
  </ng-container>
</ng-template>

```

**Comment by renehamburger** [comment]
In Angular4+, it should be possible to use `else` to simplify this further:

```html
<div *ngIf="draggable; else items" [dragula]="bagName" [dragulaModel]="collection">
  <ng-container *ngTemplateOutlet="items"></ng-container>
</div>
<ng-template #items>
  <ng-container *ngFor="let item of collection">
    ...
  </ng-container>
</ng-template>
```

**Comment by cormacrelf** [comment]
Is that really cleaner though? Not really. HTML is the least clean part of Angular. Keep in in TS.

But yes, there should be an easier way. Probably similar to the destruction logic in #794.

**Comment by cormacrelf** [comment]
In v2, you'll be able to just set [dragula] to null.

**Comment by chetankh23** [comment]
@renehamburger The solution you posted above, so does it make component draggable at run time ?

**Comment by AnthonyLenglet** [comment]
> In v2, you'll be able to just set [dragula] to null.
> 
> Update: you can do that now.

this is something we can do, however it throws an error if dragulaModel is set

```
[dragula]="hasEditPermissions ? 'bagName' : null"
[(dragulaModel)]="items"
```

```Cannot destructure property `drake` of 'undefined' or 'null'.```

```ts
...
else if (changes && changes.dragulaModel) {
  const { previousValue: prev, currentValue: current, firstChange } = changes.dragulaModel;
  const { drake } = this.group;
...
```

**Comment by quicktree** [comment]
@AnthonyLenglet 
I circumvented that issue with a different approach:
`
[dragula]="condition  ? 'items' : null"
[dragulaModel]="condition ? items: null"
dragulaModelChange)="reorderItems($event)"
`

I get that it's not a proper solution, but it does circumvent the error; Also in my case the method reorderItems() was already needed for other operations. Not sur about your situation but it may help.

**Comment by rmur** [comment]
For a newer version I have added it the following way : 

```
constructor(private readonly dragulaService: DragulaService) {
        dragulaService.createGroup('test', {
            moves: (el, source, handle, sibling) =>
                !el.classList.contains('no-drag')
        });
    }
```
