### ISSUE TITLE
Drag and drop components and persisting their position 

### ISSUE THREAD

**Issue by robertsmith2** [valor-software/ng2-dragula#786]
This might be a feature request or a question. not so much an issue..
```
<div class="row" [dragula]="'components'">
  <component-one></component-one>
  <component-two></component-two>
</div>
```

This works amazing.. is there documentation on best way to persist the component position in the class so I can save it to a database?

**Comment by cormacrelf** [comment]
The documentation clearly mentions the `[dragulaModel]` directive. Next time read it before asking what’s in it!
