### ISSUE TITLE
Keylistener gets ignored in IE when dragged element is at target position

### ISSUE THREAD

**Issue by alexandermikuta** [valor-software/ng2-dragula#790]
When dragging an element and subscribing with `this.dragula.drag.subscribe` wh are using the following keylistener:
`this.keydownListener = this.renderer.listen('body', 'keydown', (keyboard: KeyboardEvent) => {
      if (keyboard.key === 'Escape') {
        drake.cancel(true);
      }
    });`

When drag starts everything works as expected when pressing Escape, but in IE as soon as the element is moved to another position (but without release mouse and therefore before dragend) the keylistner is ignored. In other Browsers everything works as expected.

**Comment by cormacrelf** [comment]
`KeyboardEvent.key` is `Esc'` in IE11. Use `keyCode` instead. Also this is clearly unrelated to ng2-dragula. Next time use a breakpoint in your developer console before leaping to conclusions.
