### ISSUE TITLE
Setting dragulaModel causes the cards in the same container gets deleted while dragging

### ISSUE THREAD

**Issue by hhsecond** [valor-software/ng2-dragula#792]
Hi Team,
I set the dragulaModel in the custom component I have created. While dragging, in the same container, my task gets deleted from the view but not from the actuall array tasks.

` <app-stage-task [dragula]='"bagName"' [dragulaModel]='tasks' *ngFor="let task of tasks" [task]="task"></app-stage-task>`

If I don't set the dragulaModel property, I don't see this behavior.

**Comment by KevinJMC** [comment]
+1

**Comment by cormacrelf** [comment]
You're using it incorrectly. You must set [dragula] and [dragulaModel] on a container element. Like a div.

```html
<div dragula="TASKS" [dragulaModel]="tasks">
  <app-stage-task *ngFor="let task of tasks" [task]="task"></app-stage-task>
</div>
```
