### ISSUE TITLE
Draggle revert problem

### ISSUE THREAD

**Issue by praveen4554** [valor-software/ng2-dragula#795]
Hi all,

   I have 2 components in the 1st component, implement draggle drag and drop after dropping the element to container emit an event, navigate to 2nd component. In the 2nd component done some operations and emit an event to 1st component based on the emit value I would like to revert the value in the container but  I am unable to revert it by using cancel and remove model.  For storing the current state of the dragula, using a service still I am unable to store the current state of dragula

can anyone help me please

Thanks,
Praveen

**Comment by cormacrelf** [comment]
Dragula does not store a history of your application state. You will have to do that yourself. You may confront the problem that dragulaModel modifies the array you pass to it. You can work around that by storing a shallow clone (`array.slice(0)` or `[...array]`) before it has a chance to get modified.

The best solution would be using ngrx/store, never using dragulaModel, and using redux-undo or similar to store states and revert them.

**Comment by ghalib-mustafa** [comment]
If you want to use the native Dragula events to achieve this. The following piece of code can help you revert the last drop asynchronously to its previous location.
```
var originalParent, originalNextSibling;
drake.on('drag', function (el, source) {
	// Store the original parent and next sibling of the dragged element
	originalParent = el.parentNode;
	originalNextSibling = el.nextElementSibling;
});

drake.on('drop', function (el, target, source, helper) {
	setTimeout(function () {
		// move back the card
		if (originalNextSibling) {
			originalParent.insertBefore(el, originalNextSibling);
		} else {
			originalParent.appendChild(el);
		}
	}, 2000);
});
```
