### ISSUE TITLE
Inconsistent dropzones with side-by-side containers

### ISSUE THREAD

**Issue by manuelhuber** [valor-software/ng2-dragula#799]
Reordering container via drag and drop does not work consistently when containers are side-by-side instead of above/below one another.

Create a dragula bag and have 2 containers per row. Then try to drag the left one to the right position and vice versa. You will notice the following:
- When dragging a container to the right, you need to have to mouse cursor located in the lower half of the target position.
![dragula - forward top](https://user-images.githubusercontent.com/14292619/32899606-b736cae8-caeb-11e7-84b5-dbaef7f6d496.png)
![dragula - forward bottom](https://user-images.githubusercontent.com/14292619/32899605-b70f4dba-caeb-11e7-8099-67642333299c.png)
- When dragging a container to the left, you need to have to mouse cursor located in the upper half of the target position.
![dragula - backwards bottom](https://user-images.githubusercontent.com/14292619/32899608-b769a6fc-caeb-11e7-965b-c0fe2da23c4a.png)
![dragula - backwards top](https://user-images.githubusercontent.com/14292619/32899609-b7973bee-caeb-11e7-915a-4b8fcc25ac72.png)

When the mouse is in the "wrong" half, the container won't move.

I tried this simply by modifiying the example on the offical Dragula preview site.

![dragula - css modifications](https://user-images.githubusercontent.com/14292619/32899607-b750e388-caeb-11e7-8024-34d8ea0b850b.png)

I'm using:
Chrome Version 61.0.3163.100 (Official Build) (64-Bit)
Node v6.11.2
NPM 3.10.10
Dragula ^1.5.0
Angular 4.4.3
Angular CLI 1.4.3

The problem also occurs on
https://valor-software.com/ng2-dragula/index.html
with
Firefox 56.0.2
Chrome Version 61.0.3163.100 (Official Build) (64-Bit)

**Comment by jrajput** [comment]
hi, Is there any solution for this problem? I am also facing the same.

**Comment by manuelhuber** [comment]
Haven't found anything yet

**Comment by ochikov** [comment]
I have the same issue. What happend ? Somebody fix it ?

**Comment by chetankh23** [comment]
Anyone has a solution for this issue ?
