### ISSUE TITLE
Dragging a child component from one parent to another

### ISSUE THREAD

**Issue by hassanasad** [valor-software/ng2-dragula#800]
Hi - I am successfully able to drag a child element from within a parent component. However i wanted to know what would be best way to enable child element dragging between multiple parents?

So for instance:
[PARENT A]
- [Child A]
- [Child B]

[PARENT B]
- [Child A]

If i want to drag "Child B" from Parent A to Parent B (considering all of them are separate components, any suggestion how to come about it?

**Comment by swirlsky** [comment]
Add a `[dragula]` directive with the same value to both parents.

**Comment by hassanasad** [comment]
But i don't want to allow dragging of the parent component. Just the
children inside of it between parents. :)

**Comment by swirlsky** [comment]
The dragula directive is not to make an element movable, but to set it as a bag, the elements of which should be movable.

**Comment by hassanasad** [comment]
okay thanks - my scenario has changed slightly.

The items inside the Parent can move AND the parent can move themselves too.

Now the issue - When i move the parent, it moves just fine. However when i move the item inside the parent (child) - the parent element moves also.

Some dummy mark for context
```
<div [dragula]="'parent'">
   <app-parents *ngFor="let parent of parents">
          <div [dragula]="'children'">
              <app-children *ngFor="let child of children"></app-children>
          </div>
   </app-parents>
</div>
```

**Comment by hassanasad** [comment]
Actually i was able to fix that issue in Angular code - something similar to https://github.com/bevacqua/dragula/issues/31#issuecomment-305718986

**Comment by Ajita999** [comment]
@hassanasad can you explain your solution briefly?
Thanks in advance
