### ISSUE TITLE
Unable to select text inside draggable element

### ISSUE THREAD

**Issue by aurinko-vicky** [valor-software/ng2-dragula#802]
I've issue that I cannot select text for copying inside draggable element. The option ignoreInputTextSelection is set to true, however it does not help. Does anybody know how it is possible to enable dragging and selecting of the text at the same time? 
I can provide my code if it is needed. 
Thanks in advance.

**Comment by cormacrelf** [comment]
If you're talking about a plain `<p>` or span, then no, you can't do it. How would it know wchich 'mousedown ... mousemove' events were drags, and which were text selections? I would recommend instead adding a drag handle, outside the text you want to be selectable.
