### ISSUE TITLE
Dragula integration with Angular 2.0.0-rc.4 MODULELESS app

### ISSUE THREAD

**Issue by karim-ag** [valor-software/ng2-dragula#806]
I'm using ng2-dragula in my angular 2 with webpack app.
I do not have an NgModule as I'm using rc4.
After installing ng2-dragula, when I import it in a component I get the type error:
`dragular.module.js:17 Uncaught TypeError: core_1.NgModule is not a function`

the webpack build is working fine, but I get the previous error when opening the page.

any ideas?

**Comment by TekSiDoT** [comment]
Dragular depends on "@angular/*": "^2.3.1 || >=4.0.0", I'm pretty sure that kind of backwards compatibility is not in the author's scope.

**Comment by karim-ag** [comment]
I guess so, thanks TekSiDot
