### ISSUE TITLE
Not working with angular 5.1.2

### ISSUE THREAD

**Issue by romain10009** [valor-software/ng2-dragula#813]
ng2-dragula v1.5.0 does not work with angular 5.1.2. It does work with angular 5.0.0 in my project though. 

Issue : The object when dragged over the receiving bag does not show in it and when mouse is released, nothing happens, the object is back where drag started from.

**Comment by renannobile** [comment]
It's happening on Angular ^4 as well.

**Comment by renannobile** [comment]
@romain10009 Did you find a fix for this?

**Comment by romain10009** [comment]
No I didn't find. I stick to angular 5.2.0-beta.1 that works

**Comment by IdanCo** [comment]
any news? not working with 5.2.2 as well.

Issue seems to happen only when bag includes ng-for.

looks like a dup of #822

**Comment by renannobile** [comment]
What seems to be the problem, at least in my occasion, was the lack of css.

After importing css in my index.html, everything worked fine.
