### ISSUE TITLE
Getting dropped angular component instance

### ISSUE THREAD

**Issue by jrajput** [valor-software/ng2-dragula#814]
Hi Please let me know if there is any way to get dropped angular component instance in onDrop event. I want to get hold on dropped component instance to update its model.

**Comment by cormacrelf** [comment]
This is a bad idea. The method for doing this would be exactly the same as moving the model to an Angular Service and modifying it there, except that you would also be tying your components together in a ball of spaghetti code. Just don't. If you really had to, you would need to store references to all the component instances in a service, when you could just store the data there instead.
