### ISSUE TITLE
Cannot add/remove sealed array elements on Drop

### ISSUE THREAD

**Issue by ToxicToast** [valor-software/ng2-dragula#816]
Title.

Getting "Cannot add/remove sealed array elements" when i try to drag & drop List Elements.

Angular Version: 5.1.3
CLI Version: 1.5.0
OS: win32 x64
Node: 7.7.4
ng2-dragula: 1.5.0

**Comment by s001dxp** [comment]
Why was this closed? Is there a fix? I'm having the same issues.

**Comment by cormacrelf** [comment]
Are you were using a sealed array? Or sealed objects?

**Comment by s001dxp** [comment]
Nevermind--I did a deep clone of the array I'm passing to dragulaModel and that fixed the issue. Apparently the spread operator only produce a shallow copy. The inner object were all references of a sealed object.
