### ISSUE TITLE
Issue with dragulaModel

### ISSUE THREAD

**Issue by StealthyDev** [valor-software/ng2-dragula#82]
Hey! thanks for the free Angular2 plugin. I face a weird problem when I use dragulaModel. Please correct me if my understanding is wrong.

Issue: If I add dragulaModel to keep track of changes in the UI, the item I move disappears.

Here is the document with screenshots, explaining the problem:
[ng2-dragula-dragulaModel-table.docx](https://github.com/valor-software/ng2-dragula/files/135097/ng2-dragula-dragulaModel-table.docx)

**Comment by NathanWalker** [comment]
That is definitely interesting. I'd need to dive into it deeper to investigate and not sure when I will have time to do so. I'll add `help wanted` here and if someone from the community knows what is the cause, please post here.

**Comment by StealthyDev** [comment]
Thanks @NathanWalker, I can debug and get you more info

**Comment by arozwalak** [comment]
Hi @StealthyDev. I don't know if it helps. But this is my template and it works with dragulaModel attribute.

```
<tbody [dragula]="'mybox'" [dragulaModel]="items">
            <tr *ngFor="#item of items">
                <td>{{item.type}}</td>
                <td>{{item.id}}</td>
                <td>{{item.name}}</td>
                <td>X</td>
            </tr>
        </tbody>
```

**Comment by StealthyDev** [comment]
Fresh eye never hurts :)

Thanks @arozwalak, it worked perfectly. I had `*ngFor` on `tbody`, which generated a of `tbody `on my table. This confused `dragulaModel `updates with false parent DOM.

Wrong code:
```
<tbody ***ngFor="#item of items"** [dragula]="'mybox'" [dragulaModel]="items">
            <tr>
                <td>{{item.type}}</td>
```

**Comment by StealthyDev** [comment]
Not a defect.

**Comment by nikkwong** [comment]
Not really an unreasonable assumption since that's how it's placed in the docs: 


````
<ul>
  <li *ngFor="let item of items" [dragula]='"bag-one"' [dragulaModel]='items'></li>
</ul>
````

It may be worthwhile to note that the directive should be placed on a parent to the ```ngFor```.

**Comment by jeryRazakarison** [comment]
I felt on this too so now, waiting for this PR #484 that fixes the documentation.

**Comment by shikhaBasra** [comment]
```
<tbody [dragula]="'mybox'" [dragulaModel]="items">
<ng-container>
            <tr *ngFor="#item of items">
                <td>{{item.type}}</td>
                <td>{{item.id}}</td>
                <td>{{item.name}}</td>
                <td>X</td>
            </tr>
<tr><td colspan='4'>Test</td></tr>
</ng-container>
        </tbody>
```

If I use ng-container as above then ng2-dragula gives error while dropping row.
Cannot find value of undefined.
Can please somebody help me in resolving this issue?
