### ISSUE TITLE
Dragula doesn' work on Angular 5.2.1

### ISSUE THREAD

**Issue by dilotec-2015** [valor-software/ng2-dragula#822]
Dragula doesn' work on Angular 5.2.1

Installed Versions:
Angular CLI: 1.5.5
Node: 8.9.3
OS: win32 x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

angular/cdk: 5.0.4
angular/cli: 1.5.5
angular/material: 5.0.4
angular-devkit/build-optimizer: 0.0.36
angular-devkit/core: 0.0.22
angular-devkit/schematics: 0.0.42
ngtools/json-schema: 1.1.0
ngtools/webpack: 1.8.5
schematics/angular: 0.1.11
schematics/schematics: 0.0.11
typescript: 2.6.2
webpack: 3.8.1

**Comment by lishichao1002** [comment]
same question

**Comment by romain10009** [comment]
Working good on angular 6.0.0-beta.2 !

**Comment by Yehuda2018** [comment]
Adding Dragula css to index.html directlty  solves the issue.
1. Copy css from ../node_modules/dragula/dist/dragula.css.
2. Paste to index.html  into style tags. Should look like below:
<style>
        .gu-mirror {
            position: fixed !important;
            margin: 0 !important;
            z-index: 9999 !important;
            opacity: 0.8;
            -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=80)";
            filter: alpha(opacity=80);
        }

        .gu-hide {
            display: none !important;
        }

        .gu-unselectable {
            -webkit-user-select: none !important;
            -moz-user-select: none !important;
            -ms-user-select: none !important;
            user-select: none !important;
        }

        .gu-transit {
            opacity: 0.2;
            -ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=20)";
            filter: alpha(opacity=20);
        }
    </style>
