### ISSUE TITLE
Add method for intercepting a drop

### ISSUE THREAD

**Issue by chrillewoodz** [valor-software/ng2-dragula#823]
A method for intercepting a drop when using dragulaModel should be added, and if that method returns true or false it will allow/disallow the drop. This is required when having to do some checks on the model item itself rather than the element that is being dragged.

**Comment by matheusAle** [comment]
Hello Friend!
I do not think it's necessary. Of we do the 'accepts' method returns false. And define a callback in the 'cancel' method. We will have the element information dragged, but it will not be moved / copied to the container.
```
dragulaService.cancel.subscribe(val => console.log(val));
    dragulaService.setOptions('playlist-bag',{
      accepts: (el, target, source, sibling) => {
        return false;
      }
    })
```


sorry for my english I'm learning...

**Comment by cormacrelf** [comment]
In v2, we don’t mutate arrays. You can choose not to use two-way binding, and then conditionally apply the changes represented by the now-useful dropModel and removeModel events.
