### ISSUE TITLE
Getting dropped element x,y position

### ISSUE THREAD

**Issue by danzrou** [valor-software/ng2-dragula#824]
I have an image (background image on div) on which I want to drop some elements from a menu.
How can I get the mouseEvent or the latest mirrored element x.y position to dynamically set it on the dropped element?

Thanks!

**Comment by cormacrelf** [comment]
You cannot. Dragula and this wrapper do not have that functionality. It is Trello-style or bust.

You could try [angular-skyhook](https://cormacrelf.github.io/angular-skyhook/) -- try the XY pad example for a similar thing.
