### ISSUE TITLE
Drop event called multiple times

### ISSUE THREAD

**Issue by amitvchaudhary** [valor-software/ng2-dragula#828]
I have a parent component called A which has multiple child components called B.
For example:
- A
----- B
------B
------B

I have dragula service for parent component A to drag and drop child components B. But, I also have dragula service for each child component B (for nested drag and drop within child component). 

So, when any item meant for parent component A is dropped, the child components' drop event is also getting called. So, if there are 3 child components then there will be 4 drop events called (1 parent and 3 children).

Can someone please help me to call only one parent and one child (which I am interacting with at a time).

**Comment by lmarcelocc** [comment]
Hi,

did you find a solution already?

**Comment by sixteenpaws** [comment]
FYI, I believe this will fix your issue: in the declaration of your component add viewProviders: [DragulaService].

Example:
```
@Component({
    selector: 'app-child-component',
    templateUrl: 'child-component.component.html',
    viewProviders: [DragulaService]
})
```

**Comment by 1456118242** [comment]
@sixteenpaws I used your method.However, I found that the items of the two lists should not be dragged in different lists. Thank you for helping me, please?

**Comment by 16Paws** [comment]
@1456118242 if I am understanding you correctly just make sure that the bag names are different in each list and dragging between them will not be possible.

**Comment by 1456118242** [comment]
@16Paws  the bag names are same Thanks

**Comment by lmarcelocc** [comment]
@1456118242  that's the reason and what @16Paws  is telling you. You should use different bag names.

**Comment by 1456118242** [comment]
@lmarcelocc  I use different bag names,But have no effect .Do I need to set up some operations?

**Comment by 1456118242** [comment]
delete  viewProviders: [DragulaService]. and the bag names are same ,Then work .but Drop event called multiple times

**Comment by cormacrelf** [comment]
Don’t inject multiple services. Stick to one global service.

One ‘bag’ is the drag at A level, and the other is at B level. Have two bags. It’s easier to think of them the way react-dnd has ‘item types’.

Then, in the code where you handle drop events, segregate your logic by bag name.

**Comment by cormacrelf** [comment]
Can anyone explain why they are using more than one service instance? I don't understand how there is a use case for that.

**Comment by AhHa45** [comment]
There is no use case, it should be a singleton, otherwise you'll run into trouble.

**Comment by Adondriel** [comment]
I fixed this issue by not using the subscribe model of event capture. Instead use the older, less "modern" method to capture the drop event, but exclusively, it only finds the events of drops from the component that you write this in:
        this.dragulaService.find('bag').drake.on('drop', (dropElm: any, target: any, source: any, sibling: any) => {
//do stuff here.
});

**Comment by cormacrelf** [comment]
I’m closing this now, but if you’re reading this thread, here are the takeaways:

1. **Do not** inject DragulaService into viewProviders. Import the module. Once.

2. If you want to limit the scope of where items can be dropped, **just use a different bag name.** You should name your bags properly, like “CARD” or “TODO”. When you don’t want some items to interact, give them a different bag name. For parent/child, that might be “LIST” vs “CARD”. A bag is like a react-dnd ‘item type’.
