### ISSUE TITLE
[Help] - Using it with Angular Material Table

### ISSUE THREAD

**Issue by lmarcelocc** [valor-software/ng2-dragula#831]
Hi all, 

hope that anyone can help me :)

I'm using angular material to build a [table](https://material.angular.io/components/table/overview).

What I've right now is this:
```
<mat-header-row *matHeaderRowDef="_displayedColumns"></mat-header-row>
<mat-row *matRowDef="let row; columns: _displayedColumns;" [dragula]='"first-bag"'></mat-row>
```

But since the `<mat-row></mat-row>` set's something like this:
<img width="583" alt="st1" src="https://user-images.githubusercontent.com/6483007/36255688-ed23b492-1247-11e8-8bee-4d8b213a6d1d.png">

this is happening (everything within <mat-row> is being draggable):
![giphy](https://user-images.githubusercontent.com/6483007/36256531-4a34b638-124b-11e8-9b13-cd15391886ae.gif)

My goal is that all the row should be draggable and not only the field.

Anyone can help?

Thank you in advance.

**Comment by kdubious** [comment]
Why is this closed?

**Comment by cormacrelf** [comment]
The dragula directive is for use on containers. You have made your row a container, so every direct child will be draggable. That includes cells. Instead, put the dragula directive on a column. You may have trouble with the header, which you probably don't want being draggable, so you will probably need a wrapper div around just the rows, with the directive on that instead.

```html
<column>
  <header></header>
  <div dragula="first-bag">
    <row></row>
    <row></row>
    <row></row>

  </div>
</column>
```

**Comment by The224** [comment]
I understand this concept.

But Angular Material generate is own column, in this case is `ul`. If we put the `dragula` directive on the `mat-row`every "`li`" become draggable. If we put this on the mat-table, is the entire table who became draggable.

**Comment by imvikaskohli** [comment]
@lmarcelocc Have you find any success on drag and drop using ng2-dragula with angular material table

**Comment by imvikaskohli** [comment]
@The224 If we use dragulaService setOptions

    dragulaService.setOptions('catg-data', {
      revertOnSpill: true,
      moves: function (el:any, container:any, handle:any):any {
        if (el.classList.contains('mat-header-row')) {
             return false; // this will not allow any header to move
         }
        // console.log(el, container);
        return true;
      }
    });

**Comment by furevor** [comment]
@imvikaskohli I am getting error 

> property "setOptions" does not exist in "DragulaService".

 How does it work for you?

**Comment by cormacrelf** [comment]
@furevor it was renamed in v2. Read the README please.

**Comment by DylanWelgemoed** [comment]
@imvikaskohli So this works partially. Basically this stops you from dragging the header row but if I take a row from below it, I will be able to move it on top of the header row. Any Solution to this?

**Comment by cormacrelf** [comment]
You can’t. See my comment in #884.
