### ISSUE TITLE
model sync does not create objects in the right way

### ISSUE THREAD

**Issue by niecore** [valor-software/ng2-dragula#833]
When objects are transferred from one model to another the objects are not created in the right way. Basically just the properties are copied.

- Is there a option where I can "help" dragula to correctly create the objects in the new model?

Thanks in advance!

EDIT:: This only happens when you use the copy function.

**Comment by cormacrelf** [comment]
Hot tip: don’t use model sync at all. It’s not for you. Just subscribe to events and use data attributes to attach ids to dragged elements.

**Comment by niecore** [comment]
Yes, Thanks for your reply.
