### ISSUE TITLE
Issue with Angular Mat-Panel and dragula copy-option

### ISSUE THREAD

**Issue by Jodelautomat** [valor-software/ng2-dragula#836]
Dear all,

I really need your help in this matter, because I'm really stuck here.

I want to you dragula in a "checklist" designer, therefore I have 2 bags: 1 bag where the 5 different checktypes are in and the checklist-bag.
moving the items between the bags works just fine, I can open and close the mat-panel as usual.

But as soon as I enably the copy:true option, whenever I drag&copy an item to the checklist-bag, the functionality "dies". I can't open and close the dragged&copied mat-panel anymore, seems like the copy function of dragula creates a new mat-panel but not the open/close event in the background?

Any ideas how to solve this?
thank you in advance!

**Comment by cormacrelf** [comment]
This is a limitation of ng2-dragula and dragula in general. It cannot create an Angular component for you, no matter what `copy: true` would appear to imply. `mat-panel` is an Angular component, but all dragula can do is copy the DOM elements that it rendered.

So, the copied DOM elements will not have any event handlers on them. You have to ensure, somehow, that the target list gets re-rendered. If it does, the copied DOM gets wiped out and replaced with a real one from a new Angular component.

You might do this through `[dragulaModel]`, which is perhaps the most bug-prone feature of the library, or through a YourDragService that listens to drop events and applies changes to your model that reflect what ng2-dragula says it's doing. The reason `[dragulaModel]` is bad at copying is roughly the same reason Dragula is bad at copying: #709, for example. It can't create custom objects for you, it only does a basic `JSON.parse(JSON.stringify(...))`-style clone. You want to handle all of that yourself, even if it's more difficult.
