### ISSUE TITLE
Create a component and drop into the drop area

### ISSUE THREAD

**Issue by prashantnorbrik** [valor-software/ng2-dragula#841]
Dragula is very smooth compared to other libraries that I worked with in the past. 

I have an issue which seems to be a bit unique as I haven't found anyone else with the same problem. 

I am using Angular 5 to build a drag and drop forms builder. 

There are two main areas in the builder, left hand side toolbar which has a list of control that can be dropped into the drop area in the right hand side area. 

I am using copy function and tapping onto the onDrop function to manipulate the copied element to add extra html. 

Now, with angular 5 I was thinking of generating components dynamically and adding the item being dropped. Components can only be created using viewcontainerref which goes into the reference view. 

In the onDrop the first parameter is the element being copied which is what I want to use as viewcontainerref which is what I am not able to achieve. 

Sample code below:

```
  private onDrop(args: any) {
    let [e, el] = args;
    console.log("onDrop");
    console.log(e);
    console.log(el);
    e.innerHTML = "<b>" + e.innerHTML + "</b>";
    const componentFactory = this.componentFactoryResolver.resolveComponentFactory(HelpComponent);
    // const containerRef = this.viewContainerRef;
    //containerRef.clear();
    //containerRef.createComponent(componentFactory);
    
    // this.dynamicInsert.clear();
    // var b = this.dynamicInsert.createComponent(componentFactory);
    // console.log(b);
    // var a:any = componentFactory.create(this.dynamicInsert.injector, e);
    var a:any = componentFactory.create(this.dynamicInsert.injector);
    e.append(a.hostView.rootNodes[0]);
  }

```

![image](https://user-images.githubusercontent.com/22040243/37440820-98340236-2852-11e8-9cde-f2931261bea6.png)

**Comment by tucq88** [comment]
I'm working on exact same issue. Let's share our solution if one get it first.

**Comment by prashantnorbrik** [comment]
I seem to have resolved the issue :) 

See code. I am closing the issue.

```
var ref = componentFactory.create(this.injector, [], e);
this.dynamicInsert.insert(ref.hostView);
```

**Comment by saiskarur** [comment]
HI Friends,
I am new for ng2-dragula !.
I have issue with create drop element dynamically. It seems not compiling when the element defined by string and  rendered on view by [innerHTML].  My code are below, can you please any one assist me.

dnd-letter.html :
------
\<p class="title question" (click) = "playIt(activity.title.id)" [innerHTML]=" text | dragDropSpot : '__'" ><\/p>

dnd-letter.ts:
-------------
this.text = 'This __ is __.';

dragandspot.ts:
-----------------
import { Pipe, PipeTransform, } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';

@Pipe({
  name: 'dragDropSpot',
})
export class DragDropSpotPipe implements PipeTransform {

	constructor(private sanitized: DomSanitizer) {}

  transform(value: any, args: any): any {
        var re = new RegExp(args, 'gi'); //'gi' for case insensitive and can use 'g' if you want the search to be case sensitive.
        return this.sanitized.bypassSecurityTrustHtml(value.replace(re, '<span class="container drop" #selector dragula="REVERT"><span class=""> aaaaaa</span></span>'));
  }
}

**Comment by NikitaPooja** [comment]
I need that functionality but I did not understand the code. can you please help me out this problem?
