### ISSUE TITLE
drake On Remove Parameter Mismatch

### ISSUE THREAD

**Issue by OliverUlm** [valor-software/ng2-dragula#842]
I have a rather complex layout with several bags. In some circumstances the backing arrays would not update correctly due to the indizes between the models and containers arrays on the drake not lining up correctly.

I found out that while the DragulaService handles the remove event from dragula it only expects 2 parameters ( el and source). Dragula however provides 3 (el, parent and source). Quite often parent is identical to source so it's no issue but sometimes (and I've not yet found out why) it's not identical and ng2-dragula tries to remove the object from the parent instead of the actual source.

The issue is easily remedied by adding the missing parameter in the DragulaService like this:

`drake.on('remove', function (el, parent, source) {`

PS: Affected version: 1.5.0

**Comment by cormacrelf** [comment]
PR is #855
