### ISSUE TITLE
Provide dragulaModelChange emitter

### ISSUE THREAD

**Issue by moniuch** [valor-software/ng2-dragula#843]
I am trying to use dragula in a list component which is dumb - it is supposed to just receive input, process drag and drop internally, and emit a `reorder` event whenever items or their order changed. Although we can use dragula events to determine when to emit reorder event, I thought it would be a nice addon if we could have `dragulaModelChange` output (as a companion to `dragulaModel` input). Then in my code I could:

```
<ul [dragula]='"bag-one"' [dragulaModel]='items' (dragulaModelChange)='reorder.emit($event)'>
  <li *ngFor="let item of items"></li>
</ul>
```

**Comment by moniuch** [comment]
The `removeModel` and `dropModel` events are good to hav, however for simple implementations `dragulaModelChange` event (as described in the original post) with the final synced array would be much more intuitive and quicker to consume. Dev will want to have the final array passed as `$event` in the original example, regardless of `drop` or `remove` type of operation.

**Comment by cormacrelf** [comment]
I think this would go hand in hand with not mutating the array passed to dragulaModel.

**Comment by cormacrelf** [comment]
Added in 53f8d415a28722b2c0e8099c9a0dff78effc50af

Note that in v2, two-way binding will be required for basic use. This is because the library will no longer mutate the arrays you give it. Instead, it will shallow clone them, and emit dropModel/removeModel and dragulaModelChange.
