### ISSUE TITLE
Provide threshold setting for dragover

### ISSUE THREAD

**Issue by moniuch** [valor-software/ng2-dragula#844]
When I am dragging an item, I need to drag the item quite far before the dragover condition fires.

<img width="326" alt="screen shot 2018-03-17 at 23 46 21" src="https://user-images.githubusercontent.com/681956/37560710-bd26107e-2a3d-11e8-8afa-4642cb63b0ee.png">

Unfortunately the screenshot removed the cursor but it was at mid-height of the dragged item "0 quam". You can see that the drag was quite far into the "5 eu" element and still was not signalled as dragover. Seems like there is a threshold of 50% of the height of the dragover item.

I would like to be able control the threshold for the pre-drop condition distance. Say, 30% would mean 30% from the edge from which dragging enters the element. Feels like lower threshold is more user-friendly.

**Comment by cormacrelf** [comment]
This seems like a bug upstream with Dragula. Good luck getting it fixed or even merging a PR, nobody has for a year.
