### ISSUE TITLE
CSS `display: block !important` breaks dragging

### ISSUE THREAD

**Issue by pdmccormick** [valor-software/ng2-dragula#845]
## Issue

Using the `!important` modifier on the `display` property causes items within a containing bag to be stuck in place and unable to be moved.

## Sample

In the following example, the items in black can be freely moved and reordered, while the items in red (which have styling `display: block !important`) are stuck in place.

```
<style>
.display-block {
    display: block;
}

.display-block-important {
    display: block !important;
    color: red;
}
</style>
<div>
    <div class='wrapper'>
        <div class='container' [dragula]='"first-bag"'>
            <div class='display-block'>You can move these elements between these two containers</div>
            <div class='display-block'>Moving them anywhere else isn't quite possible</div>
            <div class='display-block'>There's also the possibility of moving elements around in the same container, changing their position</div>
        </div>
        <div class='container' [dragula]='"first-bag"'>
            <div class='display-block-important'>These elements cannot be moved</div>
            <div class='display-block-important'>Neither amongst themselves nor between containers</div>
            <div class='display-block-important'>They are stuck in place</div>
        </div>
    </div>
</div>
```

## Tested browsers

* Firefox 59.0.1 (64-bit Ubuntu 16.04)
* Chromium 64.0.3282.167 (Official Build, 64 bit Ubuntu 16.04)

**Comment by pdmccormick** [comment]
This turned out to be a Dragula issue which [I've reported](https://github.com/bevacqua/dragula/issues/560) and am working to get my solution accepted there.

**Comment by cormacrelf** [comment]
Closing for upstream.
