### ISSUE TITLE
Styling .gu-transit affects .gu-mirror

### ISSUE THREAD

**Issue by moniuch** [valor-software/ng2-dragula#848]
I am quoting my own post from SO below:

I am using ng2-dragula and trying to achieve an effect where the intended drop place is signalled by an insert line rather than an empty box. Somehow though, when I style the `.gu-transit` element like so:
```
.gu-transit {
  height: 0px;
  border: 1px solid red;
}
```
it also affects the `.gu-mirror` element (the drag helper) - it acquires same height.

As someone suggested the following solution ie. adding `!important`:
 
```
.gu-transit { height: 0px !important; }
.gu-mirror { height: inherit !important; }
```
I used the same technique to separate `opacity` (which got "linked" just as the height was). However the border would only briefly, almost unnoticeably, appear after drop. Adding `!important` on the border property didn't solve my problem.

Could ng2-dragula do a better job unlinking these two classes and provide more control over their styling? Could anything be done to make the above-mentioned "insert" scenario easier to achieve?

**Comment by cormacrelf** [comment]
No. This library wraps Dragula. That is the class list that gets applied by Dragula. You can use the CSS `:not(... selector ...)` to get more granular combinations.
