### ISSUE TITLE
deal with nested drag and drop with help of drag handle 

### ISSUE THREAD

**Issue by missionraj** [valor-software/ng2-dragula#850]
inside my parent-bag there is child-bag how to drag and drop  with the handle   for   both the parent and child bag using moves functions
`  this.dragula.setOptions('parent-bag', {
            moves: function (el, container, handle) {
                 return handle.classList.contains('handle');
            }
          });`

my html file 
`<div [dragula]='"parent"' [dragulaModel]='questions'>
  <div >
   <div class="handle" ></div>
    <div >
      <div class="option"></div>
      <div>option 1</div>
      <div class="option"></div>
      <div>option 2</div>
       <div class="option"></div>
      <div>option 3</div>
    </div>
</div>
</div>`

**Comment by cormacrelf** [comment]
You can’t use one handle to drag in two different bags. How would Dragula know what bag you meant?

I think you just want to add the same moves function to both bag configurations.

**Comment by cormacrelf** [comment]
Refer #808
