### ISSUE TITLE
Update to Angular 6+

### ISSUE THREAD

**Issue by Enngage** [valor-software/ng2-dragula#853]
Any chance you can bump this to Angular 6+? Currently it is working perfectly fine in latest `rc` release of Angular even in complex scenarios (we have nested lists etc..)

**Comment by icepoint0** [comment]
in v6  will be error 

ReferenceError: global is not defined

**Comment by cormacrelf** [comment]
closing #849

**Comment by cormacrelf** [comment]
Also the version constraints don't stop you from using it with v6: `"^2.3.1 || >=4.0.0"`
