### ISSUE TITLE
npm build errors

### ISSUE THREAD

**Issue by juanchaur** [valor-software/ng2-dragula#857]
While doing the npm build I have the following stacktrace:

```

[01:29:07] → Command failed: ngc -p src
Error at /Users/j/Desktop/ng2-dragula/node_modules/@types/tapable/index.d.ts:247:22: ',' expected.
```
tons of messages like that.
Does anybody know what happened?

**Comment by cormacrelf** [comment]
@types/tapable now seems to requiring TypeScript 2.3, with defaults for generic types.
