### ISSUE TITLE
How do I stop/cancel the drag event?

### ISSUE THREAD

**Issue by csjasonwong** [valor-software/ng2-dragula#858]
Hi,
I would like to the Drap cancelled/stopped if certain conditions met.
"this._dragulaService.find('first-bag').drake.cancel(true); " only works for the onDrop, but it gives error in the onDrag.. Please help. Thanks!

This is how I trigger my onDrag method

    _dragulaService.drag.subscribe((value) => {
      console.log(`drag: ${value[0]}`);
      this.onDrag(value.slice(1));
    });

  private onDrag(args) {
    let [e, el] = args;
 // I have a condition check and cancel the event if the condition meets
  }

**Comment by larryeby** [comment]
```
constructor(private dragulaService: DragulaService) {
    this.dragulaService.setOptions('YOUR-BAG-NAME', {
      moves: (element, source, handle, sibling) => {
        if (SOME-CONDITION) {
          return false;
        }
        return true;
      }
    });
  }
```

**Comment by csjasonwong** [comment]
Hi Lawrence,


Thank you for your reply.


I did put something like that before, but I keep getting this error "Bag named: "bag-one" already exists." in File DragulaService, Method "add".


Any idea? thanks!


Jason

________________________________

**Comment by larryeby** [comment]
Hi Jason, I removed my comment because I thought I was answering a different problem. Sorry about that. Is this error happening because you're switching out components and a component is being destroyed? I do this in my constructor for this reason:

```
if (this.dragulaService.find('YOUR-BAG-NAME') !== undefined) {
      this.dragulaService.destroy('YOUR-BAG-NAME');
}
```

That way if I have forms in between tabs and one form is destroyed, but I'm still using the same template, it recreates the bag.

**Comment by csjasonwong** [comment]
Thank you @larryeby !

Actually, I'm trying to stop the drop on the drop event as I need to check the condition by the args passed through. I tried to use ... this._dragulaService.find(MY_BAG_NAME).drake.cancel(true), but effect what so ever.....

I'm using angular 5
Any suggestions would be appreciated. THANK YOU!

Jason

**Comment by VitorHFLopes** [comment]
@csjasonwong you could use [invalid](https://github.com/bevacqua/dragula#optionsinvalid) option from setOptions method.

```javascript
this._dragulaService.setOptions('bag', {
  invalid: (element, handle) => handle.className.indexOf('someClass') > -1,
});
```
