### ISSUE TITLE
Failed to execute 'insertBefore' on 'Node': The new child element contains the parent.

### ISSUE THREAD

**Issue by csjasonwong** [valor-software/ng2-dragula#859]
Hello, has anyone came across this error?

When I drag my list item that has its child elements expanded. I got this exception

Thanks.

**Comment by csjasonwong** [comment]
Found solution!
In the css file!
   /*
     To prevent the "Uncaught HierarchyRequestError:
     Failed to execute 'insertBefore' on 'Node':
     The new child element contains the parent." error, 
     just make the selected element's shadow reject all mouse events:
     Reference: https://github.com/bevacqua/dragula/issues/52 commented by Syforce
    */
    pointer-events: none;

**Comment by lucasBertola** [comment]
@csjasonwong THANK YOU! THANK YOU! AND!!! THANK YOU!!!

**Comment by JensUweB** [comment]
I have the same problem, but absolutely no idea where to put `pointer-events: none;`
My elements are looking like this: `<li><a href="...">...</a></li>`

"just make the selected element's shadow reject all mouse events:"
A shadow has a mouse event???

Some example code would be really helpful.
