### ISSUE TITLE
 this._dragulaService.find(MY_BAG_NAM).drake.cancel(true);  NOT WORKING

### ISSUE THREAD

**Issue by csjasonwong** [valor-software/ng2-dragula#861]
Dear everyone,

Using Angular 5,

On the drop event, I call this line to stop the drop: this._dragulaService.find(MY_BAG_NAM).drake.cancel(true) ;  but has no effect what so ever. 

Any help will be appreciated, THANKS!

Jason

**Comment by MNorgren** [comment]
Did you find your solution to this? If so, could you please share?
