### ISSUE TITLE
How to get model Name insted of Html ?

### ISSUE THREAD

**Issue by aadii104** [valor-software/ng2-dragula#862]
Hello,
I am trying to create a Trello kind of small app.
here, I am in need of getting the particular model Names in which I am going to drop the item and the one from where I am picking the item. So, simply I can update this info in the backend.
Please suggest a way todo this.
thanks.

**Comment by aadii104** [comment]
Hello,
I am trying to create a Trello kind of small app.
here, I am in need of getting the particular model Names in which I am going to drop the item and the one from where I am picking the item. So, simply I can update this info in the backend.
Please suggest a way todo this.
thanks.

**Comment by cormacrelf** [comment]
Use a data attribute on the element being dragged, and use Element.getAttribute to pull it off.
