### ISSUE TITLE
Bag inside a bag

### ISSUE THREAD

**Issue by soyJairoCosta** [valor-software/ng2-dragula#864]
Hello there!

I want to creaet a project where I drop elements and then add new elements inside that one created.

¿Is there any way to doing that?

Regards!

P.S: Explanation...

BAG ONE:
[ [X] [Y] [Z] ]

BAG TWO:
[ [A] [B] [C] ]

1. Move from bag one to an element:
{ [X] }
2. Move from bag two to the copy of bag one inside the element:
{ [X [A] ] }

**Comment by cormacrelf** [comment]
A bag is not a single container. It can be many containers that can be dragged between. I don’t understand your problem, but it is not possible to move “from” one bag to any other place. All drags occur within one bag, so you can only move between containers within the same bag.

Bag is a terrible word for describing this. I wish it had never been used. ‘Drake’ might be better, but it literally means male duck, so I’m not sure of any realistic benefit.

**Comment by cormacrelf** [comment]
Closing because it still doesn’t make any sense to me.
