### ISSUE TITLE
Drag and drop is no shadow effect

### ISSUE THREAD

**Issue by Yos5ef** [valor-software/ng2-dragula#866]
Drag and drop is no shadow effect

**Comment by Yos5ef** [comment]
<ul [dragula]='"third-bag"'  [dragulaModel]='items' style="z-index: 9999;">
  <li
    *ngFor="let item of items"
  >{{item}}</li>
</ul>

constructor(private dragulaService: DragulaService) {
    dragulaService.setOptions('third-bag', {
      removeOnSpill: true
    });
  }

**Comment by cormacrelf** [comment]
This makes no sense. Please clarify or close the issue.
