### ISSUE TITLE
拖拽动画失效

### ISSUE THREAD

**Issue by L-value** [valor-software/ng2-dragula#870]
您好，我使用的是ng2-dragula 1.5.0版本，当我把angular 升级到6.0版本之后，我发现拖拽的动画都失效了，我应该怎么办？

**Comment by cormacrelf** [comment]
The library does not provide any animations. These are yours, I suppose? I can't really help you.

**Comment by vasyliv** [comment]
@L-value please try to import CSS file from node_modules\dragula\dist\dragula.css to root of your project.

**Comment by L-value** [comment]
ok ,I solve this problem when i import the dragula.min.css.
thank you very much~
