### ISSUE TITLE
Edit copy component

### ISSUE THREAD

**Issue by ely-alamillo** [valor-software/ng2-dragula#871]
This is more of a question than an issue.

I'm trying to drag n drop an element into a new bag but is there a way that the element being copied to the new bag be edited. For example I drag element with attribute `formControlName="x"` and when I drag(copy) to the other bag I would like to change the `formControlName` to `y`.

**Comment by cormacrelf** [comment]
Dragula does not pick up entire components, it picks up HTML fragments and clones them elsewhere. If you want to render a different Angular template, then you should render a different Angular template.

Also, you cannot drag to an ‘other bag’. Another container, perhaps — which could be rendered from a different Angular template. Note that the little transparent preview in the destination spot is still just a DOM clone, but if your destination is re-rendered, it will be wiped out.
