### ISSUE TITLE
Copy destroies object methods in Dragula model

### ISSUE THREAD

**Issue by luzel** [valor-software/ng2-dragula#873]
I know this is a feature not a bug. Copy uses JSON.stringify(JSON.parse()) to clone dragged model item.

I have issue with this feature as my object has methods for data manipulation.

How to preserve methods in object? Is there any callback  that can be used to recreate object with needed methods? What is best practice for this situation?

**Comment by cormacrelf** [comment]
Wait a few days. I’m working on 2.0. It will be incremental but hopefully stave off this exact often-duplicated issue for a couple of years.

**Comment by cormacrelf** [comment]
#608 #490

**Comment by cormacrelf** [comment]
Also if you really want flexibility over what happens when you drag and drop things...

https://cormacrelf.github.io/angular-skyhook/
