### ISSUE TITLE
[bug report] ERROR in node_modules/ng2-dragula/dist/DrakeWithModels.d.ts(1,23): error TS2688: Cannot find type definition file for 'dragula'.

### ISSUE THREAD

**Issue by juusee** [valor-software/ng2-dragula#876]
- [x] Build errors, incompatibility, errors that prevent using the library entirely
- [ ] Incorrect behaviour with `[dragulaModel]`
- [ ] Performance issue
- [ ] Documentation/demo problem
- [ ] Other

**Describe the bug**

When started using v2 got this error after compiling: `ERROR in node_modules/ng2-dragula/dist/DrakeWithModels.d.ts(1,23): error TS2688: Cannot find type definition file for 'dragula'.`

**Versions**

 - `@angular/core`: 6.0.9
 - `ng2-dragula`: 2.0.0
 - `rxjs`: 6.2.2

**Comment by cormacrelf** [comment]
Instant fix might be to install “@types/dragula”. I might look into whether this should be a dependency.

**Comment by cormacrelf** [comment]
Although maybe add a typeRoots entry in tsconfig for “node_modules/@types”?

**Comment by juusee** [comment]
Installing types for dragula worked, thanks

**Comment by cormacrelf** [comment]
v2.0.1 released
