### ISSUE TITLE
[bug report]: Trying to nest dragula items, however items are replicating randomly

### ISSUE THREAD

**Issue by alshdavid** [valor-software/ng2-dragula#878]
I am trying to copy items from a source bag which contains "base items" which, when dropped into the big spot, convert into their "final form".

One of these base items is a "group" item, which can contain other base items (aside from other groups).

When copying items into the nested bag, it seems to copy the entire bag into the nested bag.
It's especially bad if there are already items in the bag to begin with

Here's a code example.

https://stackblitz.com/edit/angular-zgcekn

![image](https://user-images.githubusercontent.com/12656294/43186836-3e302924-9033-11e8-9661-612b987355d7.png)

**Comment by cormacrelf** [comment]
In future, please fill out the issue template correctly.

This is actually a bug, so thanks for reporting.

**Comment by cormacrelf** [comment]
v2.0.2 out now.
