### ISSUE TITLE
[usage question] How to use dragulaModel with <mat-tree>

### ISSUE THREAD

**Issue by furevor** [valor-software/ng2-dragula#879]
- [X] My issue title starts with `[usage question]`
- [X] I have thoroughly read through the README, and I have looked at the demos to see if my use case has obvious examples.
- [X] I have read the [dragula docs](https://github.com/bevacqua/dragula).
- [X] I have searched through the **[`ng2-dragula` issues](https://github.com/valor-software/ng2-dragula)** for related problems, including closed issues, and I didn't find anything.
- [x] I have browsed through [the issues labeled "future reference"](https://github.com/valor-software/ng2-dragula/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22future+reference%22).

**Please select what kind of bug this is**

- [ ] Build errors, incompatibility, errors that prevent using the library entirely
- [X] Incorrect behaviour with `[dragulaModel]`
- [ ] Performance issue
- [ ] Documentation/demo problem
- [ ] Other

**Describe the bug**
I am using angular material tree and I want drag and drop elements in it. It's ok to d&d when I try to swap elements of base dragulaModel array, but when I am trying to swap children of one of the dragulaModel array, I get error.. 

**To Reproduce**

1. Open example.
2. Swap tree elements between each other
3. Toggle one of them
4. Swap them again
5. See error

Here is minimal reproduction of this behavior of [StackBlitz](https://stackblitz.com/edit/angular-btygwb). 

**Expected behavior**
I am expected that I can swap dragulaModel's children between each other, and also parents of this elements between each other

**Versions**

 - `@angular/core`: [e.g. 6.0.7]
 - `ng2-dragula`: [e.g. 2.0.0]/[2.0.1]/[2.0.2]

**Comment by cormacrelf** [comment]
This is not a usage question. It is a bug report. How is it this hard to file a bug report correctly? Not one of the issues posted after the issue templates were applied has managed to.

Your blitz isn't using ng2-dragula 2.0.2. Unfortunately I think StackBlitz caches latest versions for WAY too long. Please upgrade to 2.0.2 on your local machine and see if it still works.

**Comment by furevor** [comment]
When I was creating this example on stackblitz, I have noticed that there is 2.0.1 version, but a few hours ago I have tried 2.0.2v on local code but have the same result. Sorry for wrong template, I really don't understand what I need to feel more, I am kinda newbie:) should I change it to bug report?

**Comment by cormacrelf** [comment]
No, but it really isn't that hard.

**Comment by cormacrelf** [comment]
Ok, now that I understand what you're doing here... it isn't a bug report. Indeed. My apologies. Still fill out the template completely next time! The checklist is there for a reason, so people actually do the items on it.

And FYI, this is absolutely not going to work. Using two-way binding on the dragula model will never work when the array is meant to be computed from a tree through a tree flattener. You will have to use `[dragulaModel]` (no `()`),  compute a diff between `targetModel` and the flattened data, and convert the diff to operations on your ChecklistDatabase.... don't do this, it is way too painful.

Instead, don't use a tree flattener, just use a regular tree, with many local [dragulaModel].

**Comment by furevor** [comment]
Sorry, I have changed issue to bug report template before read your answer...

**Comment by cormacrelf** [comment]
Haha, issue templates are terrible. The worst. This is why people use other issue trackers.

**Comment by furevor** [comment]
Thanks for reply, I will try!

**Comment by furevor** [comment]
But one more question, what is "regular tree, with many local [dragulaModel]" ..?

**Comment by furevor** [comment]
You mean use [dragulaModel] istead of [(dragulaModel)] with what? What does it mean "regular tree"?

**Comment by cormacrelf** [comment]
A regular tree just means a 'nested tree'. https://github.com/angular/material2/blob/master/src/demo-app/tree/tree-demo.ts -- use the nested version.

And still don't use two-way binding, just compare sourceModel and targetModel with the existing tree data and make updates as necessary. Good luck.

**Comment by furevor** [comment]
Thanks!
