### ISSUE TITLE
[bug report] Two-way binding with dragulaModel on map items

### ISSUE THREAD

**Issue by LeandreLPP** [valor-software/ng2-dragula#881]
**REQUIRED: Before you file a bug report**

Change each `[ ]` to `[x]` when you have done it.

- [x] My issue title starts with `[bug report]`
- [x] I have thoroughly read through the README, and the [dragula docs](https://github.com/bevacqua/dragula).
- [x] I have searched through the **[`ng2-dragula` issues](https://github.com/valor-software/ng2-dragula/issues)** for related problems, including closed issues, and I didn't find anything.
- [x] I have searched through the **[upstream `dragula` issues](https://github.com/bevacqua/dragula/issues)** for related problems, including closed issues, and I didn't find anything.
- [x] I am using the latest version of `ng2-dragula`
- [x] I have read through the ['classic blunders' section of the README](https://github.com/valor-software/ng2-dragula#classic-blunders) and I am not doing any of them
- [x] I have browsed through [the issues labeled "future reference"](https://github.com/valor-software/ng2-dragula/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22future+reference%22).

**Please select what kind of bug this is**

- [ ] Build errors, incompatibility, errors that prevent using the library entirely
- [x] Incorrect behaviour with `[dragulaModel]`
- [ ] Performance issue
- [ ] Documentation/demo problem
- [ ] Other

 *(If you can, please fork and submit a pull request! See the [development](https://github.com/valor-software/ng2-dragula#development) section of the README.)*

**Describe the bug**

When trying to use two-way binding with "[(dragulaModel)]" on a map entry (which is an array), I get a "Unexpected token" error.

**To Reproduce**

1. Create a `Map<any,any[]>`
2. Try to bind `[(dragulaModel)]="map.get(i)"`
3. See error

Here is a [StackBlitz][stackblitz] of a minimal working (or rather, not working) example.

[stackblitz]: https://stackblitz.com/edit/dragula-map-bug&file=src/app/app.component.html

**Expected behavior**

The not-working example should behave exactly the same than the workaround example.

**Disclaimer**

I'm rather new to Angular so this error might be caused by my own incompetence. If it is so, please tell me where I went wrong.

**Versions**

 - `@angular/core`: [e.g. 6.0.4]
 - `ng2-dragula`: [e.g. 2.0.0]

**Comment by cormacrelf** [comment]
Two-way binding sets variables, specifically lvalues. Is `map.get(i)` an lvalue? Can you write `map.get(i) = whatever`? I didn't think so.

`[dragulaModel]="map.get(i)" (dragulaModelChange)="map.set(i, $event)"`

**Comment by LeandreLPP** [comment]
Thanks for the explanation.
