### ISSUE TITLE
[bug report] Error: Group named: "GROUPNAME" already exists.

### ISSUE THREAD

**Issue by mostwired** [valor-software/ng2-dragula#885]
**REQUIRED: Before you file a bug report**

Change each `[ ]` to `[x]` when you have done it.

- [x ] My issue title starts with `[bug report]`
- [x ] I have thoroughly read through the README, and the [dragula docs](https://github.com/bevacqua/dragula).
- [x ] I have searched through the **[`ng2-dragula` issues](https://github.com/valor-software/ng2-dragula/issues)** for related problems, including closed issues, and I didn't find anything.
- [x ] I have searched through the **[upstream `dragula` issues](https://github.com/bevacqua/dragula/issues)** for related problems, including closed issues, and I didn't find anything.
- [x ] I am using the latest version of `ng2-dragula`
- [ x] I have read through the ['classic blunders' section of the README](https://github.com/valor-software/ng2-dragula#classic-blunders) and I am not doing any of them
- [x ] I have browsed through [the issues labeled "future reference"](https://github.com/valor-software/ng2-dragula/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22future+reference%22).

**Please select what kind of bug this is**

- [ ] Build errors, incompatibility, errors that prevent using the library entirely
- [ ] Incorrect behaviour with `[dragulaModel]`
- [ ] Performance issue
- [ ] Documentation/demo problem
- [x ] Other

 *(If you can, please fork and submit a pull request! See the [development](https://github.com/valor-software/ng2-dragula#development) section of the README.)*

**Describe the bug**

Following an example online (https://valor-software.com/ng2-dragula/index.html), defined a container (div) with dragula="GROUPNAME" (and draggable children populated via *ngFor):

```
<div class="scrollable-container" dragula="GROUPNAME" [(dragulaModel)]="myItems">

    <div *ngFor="let item of myItems; index as itemIndex">
    ....
```

then in class constructor added:

```
const options: any = {
                moves: (el, container, handle) => {
                    return handle.className === 'drag-handle';
                } 
            };

dragulaService.createGroup('GROUPNAME', options);

```
An error is thrown on the first load (and every _other_ time a page is refreshed via F5):

core.js:1671 ERROR Error: Uncaught (in promise): Error: Group named: "GROUPNAME" already exists.
Error: Group named: "GROUPNAME" already exists.
    at DragulaService.push../node_modules/ng2-dragula/dist/fesm5/ng2-dragula.js.DragulaService.add (ng2-dragula.js:136)
    at DragulaService.push../node_modules/ng2-dragula/dist/fesm5/ng2-dragula.js.DragulaService.createGroup (ng2-dragula.js:190)

**To Reproduce**

Refresh the page several times (F5). The error is thrown every other time. 

**Expected behavior**

Dragula containers get initialized with options provided.

**Screenshots**

**Versions**

 - `@angular/core`: 6.1.0
 - `ng2-dragula`: 2.0.2

**Browsers affected**

Only tested in Chrome

**Additional context**
Previous version of Dragula used setOptions method - where options would be set on existing Dragula containers. This version only provides create group method, and "options is the options object used to create the drake. Modifying it won't do anything useful.".

**Comment by cormacrelf** [comment]
You should be aware that the name of the method was changed precisely because it did NOT change options on existing drakes, and was misleading.

But I will investigate.

**Comment by cormacrelf** [comment]
(Also, can you please try logging something in your constructor? It is about 99% likely your component is simply being jnstantiated twice. There is no such thing as objects persisting over refresh.)

**Comment by mostwired** [comment]
Of course I didn't make the destroy() call :) That seemed to have caused the issue. Doing a quick and dirty test-drive of the library, I wasn't sure that would be required, since F5 refresh shouldn't persist anything  - but may have been due to my routing setup.

**Comment by craftpip** [comment]
In my case, i ran `dragulaService.createGroup('GROUPNAME', options);` in the `AfterViewInit` hook, that gave me the same error
Moving the `createGroup` method into the constructor solved the issue.

**Comment by cormacrelf** [comment]
For reference, that's because a group will be automatically created if you use the directive, so you have to beat it to the punch.

**Comment by roopeshreddy** [comment]
I see the comment in the code that, couple of methods along with .destroy() is for testing purpose, hopefully this will not go PRIVATE.

**Comment by masoudarvishian** [comment]
I was using it in my `DialogComponent`. So first of first, I put `this.dragulaService.destroy('GROUPNAME');` in my code and the error disappeared.

**Comment by giacomodeglinnocenti** [comment]
In my case this was due to multiple instantiation as of the following wrong code:

`    ngOnInit() {
    }

    ngOnChanges(changes: SimpleChanges): void {
        this.initDragAndDrop();
    }`

the correct one has to be the following:

`    ngOnInit() {
        this.initDragAndDrop();
    }

    ngOnChanges(changes: SimpleChanges): void {
    }`

the changes from the model/s to the UI doesn't need a dragula component re-init.
