### ISSUE TITLE
Dragula event is repeated

### ISSUE THREAD

**Issue by ahmedeldeeb25** [valor-software/ng2-dragula#886]
I'm using Dragula in simple task with angular 5, in the first time it works fine but when i'm leaving the page and return again the event logic is repeat twice, when leaving and return again repeat three times and so on...
so what is the problem here

```
ngOnInit() {

 this.dragula.dragend().subscribe(value => {          
              console.log("Service Value "+value);
        });
}
```
the console message is repeat,I'm trying to destroy it in ngOnDestoy() but still the same problem

```
 this.dragula.dragend().subscribe().unsubscribe();
        if (this.dragula.find('bag-items') !== undefined) {
            this.dragula.destroy('bag-items');
            console.log("Malek destroy")
          }
```

**Comment by cormacrelf** [comment]
The documentation takes care to note that you must unsubscribe from any subscriptions you make. All of the example code using events includes the required ngOnDestroy code. Your code doesn’t do that (you did it wrong). Please find out how to use basic RxJS subscriptions somewhere else.

**Comment by ahmedeldeeb25** [comment]
@cormacrelf   but i'm unsubscribe the subscriptions of the event in ngOnDestroy()

**Comment by ahmedeldeeb25** [comment]
@cormacrelf Do you mean to use `this.dragula.dragend().subscribe()` is another place not in `ngOnInit()`

**Comment by ahmedeldeeb25** [comment]
The solution is very simple just like this : 
ngOnInit() {

 dragevent = this.dragula.dragend().subscribe(value => {          
              console.log("Service Value "+value);
        });
}
and in ngOnDestroy() method unsubscribe it 
dragevent.unsubscribe() 

the solution is very simple but not you will need to add it in the documentation

@cormacrelf
