### ISSUE TITLE
Drag and drop issue

### ISSUE THREAD

**Issue by samruddhinangare** [valor-software/ng2-dragula#887]
I have two adjacent components where i want to move the elements from right component to left and right elements shouldn't be rearranged inside its container instead the elements of right should only be dropped or rearranged in the left container/component itself.
I tried the sample from **https://valor-software.com/ng2-dragula/index.html** , but getting error for `createGroup()` function unidentified .
Please let me know how can i fix the issue or what is the right way to implement dragula between multiple components.

**Comment by cormacrelf** [comment]
Nobody can help you with this issue in its current form. Please fill out the issue template and actually describe your problem. The word “unidentified” is not enough.
