### ISSUE TITLE
[bug report] dragulaModel 2-way binding produces unexpected result on dynamically-added dragula containers

### ISSUE THREAD

**Issue by mostwired** [valor-software/ng2-dragula#888]
**REQUIRED: Before filing a bug report**

Change each `[ ]` to `[x]` when you have done it.

- [x ] My issue title starts with `[bug report]`
- [x ] I have read the [README](https://github.com/valor-software/ng2-dragula), especially the ['classic blunders' section](https://github.com/valor-software/ng2-dragula#classic-blunders), and the [dragula docs](https://github.com/bevacqua/dragula).
- [x ] I have searched through the [`ng2-dragula` issues](https://github.com/valor-software/ng2-dragula/issues) for related problems, including closed issues.
- [ x] I have browsed through the [issues labeled "future reference"](https://github.com/valor-software/ng2-dragula/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22future+reference%22) for problems that have been solved before or have a known workaround.
- [x ] I am using the latest version of `ng2-dragula`.

**Describe the bug (required)**

Please refer to StackBlitz for code:
[https://stackblitz.com/edit/angular-vul6ph](https://stackblitz.com/edit/angular-vul6ph)

When adding dynamic containers, dragulaModel two-way binding sometimes duplicates items into targetModel from unrelated containers; or at times just nulls the dragged item (as in GIF example below). 

**To Reproduce (required)**

Steps to reproduce the behavior are shown in the GIF below:

![ng2dragula](https://user-images.githubusercontent.com/9535192/43996751-9e33b39c-9d97-11e8-905f-2647eb2701ef.gif)

[stackblitz]: https://stackblitz.com/edit/angular-vul6ph

**Screenshots (optional)**

**Versions (required)**

Please state which versions of the following packages you have installed:

 - `@angular/core`: 6.1.2
 - `ng2-dragula`: 2.0.1 (also happens in 2.0.2)

**Comment by cormacrelf** [comment]
Thanks for a well-crafted issue! This does look very similar to the terrible bug that prompted 2.0.2, over at #878. I updated the blitz to 2.0.2 and it looks like it doesn’t happen any more. Can you confirm that? Or does it still break in your own code?

**Comment by mostwired** [comment]
I think 2.0.2 fixed that. Stackblitz was installing 2.0.1 by default. After upgrading, I don't see this issue anymore. 👍
