### ISSUE TITLE
error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'EventEmitter<any>' has no compatible call signatures.

### ISSUE THREAD

**Issue by lakinmohapatra** [valor-software/ng2-dragula#889]
Hi 
I am facing this error while using drgaula service 
error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'EventEmitter<any>' has no compatible call signatures.

Please advise. 

Thanks,
Lakin

**Comment by lakinmohapatra** [comment]
error TS2339: Property 'createGroup' does not exist on type 'DragulaService'.

**Comment by lakinmohapatra** [comment]
Fixed it

**Comment by wcjord** [comment]
What was the fix?
