### ISSUE TITLE
Building Issues with error in ng2-dragula.d.ts

### ISSUE THREAD

**Issue by ochikov** [valor-software/ng2-dragula#891]
**REQUIRED: Before filing a bug report**

Change each `[ ]` to `[x]` when you have done it.

- [x ] My issue title starts with `[bug report]`
- [x] I have read the [README](https://github.com/valor-software/ng2-dragula), especially the ['classic blunders' section](https://github.com/valor-software/ng2-dragula#classic-blunders), and the [dragula docs](https://github.com/bevacqua/dragula).
- [x] I have searched through the [`ng2-dragula` issues](https://github.com/valor-software/ng2-dragula/issues) for related problems, including closed issues.
- [x] I have browsed through the [issues labeled "future reference"](https://github.com/valor-software/ng2-dragula/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22future+reference%22) for problems that have been solved before or have a known workaround.
- [x] I am using the latest version of `ng2-dragula`.

**Describe the bug (required)**

When I install the library and try to build the project using ```ng-serve``` I am getting the following error:

**ERROR in Metadata version mismatch for module /Users/user/project/Name.Web.Angular/node_modules/ng2-dragula/dist/ng2-dragula.d.ts, found version 4, expected 3, resolving symbol PropertiesModule in /Users/user/project/Name.Web.Angular/src/app/properties/properties.module.ts, resolving symbolPropertiesModule in /Users/user/project/Name.Web.Angular/src/app/properties/properties.module.ts**

If I go to ng2-dragula.d.ts and change the version from 4 to 3, it is building correctly.

 - `@angular/core`: ^4.4.6
 - `ng2-dragula`: ^2.0.2

**Comment by cormacrelf** [comment]
Yep. I dropped Angular < 6 support in 2.0. See the release notes and migration guide.
