### ISSUE TITLE
[feature request] I need an element no draggable

### ISSUE THREAD

**Issue by menme95** [valor-software/ng2-dragula#892]
**REQUIRED: Before filing a feature request**

Change each `[ ]` to `[x]` when you have done it.

- [x] My issue title starts with `[feature request]`
- [x] I have thoroughly read through the README, and the [dragula docs](https://github.com/bevacqua/dragula).
- [x] I have searched through the **[`ng2-dragula` issues](https://github.com/valor-software/ng2-dragula/issues)** for related problems, including closed issues, and I didn't find anything.

**Is your feature request related to a problem? Please describe.**

I have a div with n components A inside it and one component B that the user can click to add a component A. I need the component B wouldn't be draggable.

**Describe the solution you'd like**

I want to drag components A and component B always stay the last one.

![image](https://user-images.githubusercontent.com/22968155/44404630-d5ea5c80-a546-11e8-8ea9-4a46d82a9d86.png)

**Comment by cormacrelf** [comment]
dupe #884, filed just the other day. It’s not ever (EVER) going to be a feature, but there will always be ways to work around.
