### ISSUE TITLE
Issue with create dynamic drop element using pipe

### ISSUE THREAD

**Issue by saiskarur** [valor-software/ng2-dragula#893]
HI Friends,
I am new for ng2-dragula !.
I have issue with create drop element dynamically. It seems not compiling when the element defined by string and  rendered on view by [innerHTML].  My code are below, can you please any one assist me.

dnd-letter.html :
------
\<p class="title question" (click) = "playIt(activity.title.id)" [innerHTML]=" text | dragDropSpot : '__'" ><\/p>

dnd-letter.ts:
-------------
this.text = 'This __ is __.';

dragandspot.ts:
-----------------
import { Pipe, PipeTransform, } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';

@Pipe({
  name: 'dragDropSpot',
})
export class DragDropSpotPipe implements PipeTransform {

	constructor(private sanitized: DomSanitizer) {}

  transform(value: any, args: any): any {
        var re = new RegExp(args, 'gi'); //'gi' for case insensitive and can use 'g' if you want the search to be case sensitive.
        return this.sanitized.bypassSecurityTrustHtml(value.replace(re, '<span class="container drop" #selector dragula="REVERT"><span class=""> aaaaaa</span></span>'));
  }
}

**Comment by cormacrelf** [comment]
That’s not how Angular works! innerHTML does not compile templates. I am simply horrified by this code. If you’re trying to make raw user input work with drag and drop — get your users to enter data in lists in the first place, and store it that way. What you’re doing now looks incredibly dangerous. You should stop coding immediately, take a deep breath, and google “XSS”. That’s all the help I can give you without this being contributory negligence.

**Comment by saiskarur** [comment]
Hi cormacrelf,

Thanks for your response, Sorry i am new for angular as well dragula, hence its very challenge for me to create drop spot dynamically. However the drop spot will be changed asper the input which are generated by user with json. It could be great if you can share some idea.

Thanks.
