### ISSUE TITLE
Save position of dragged items with dragula-drag-and-drop -- Angular Version

### ISSUE THREAD

**Issue by miteshngandhi** [valor-software/ng2-dragula#894]
**REQUIRED: Before filing a usage question**

Change each `[ ]` to `[x]`  when you have done it.

- [x] My issue title starts with `[usage question]`
- [x] I have read the [README](https://github.com/valor-software/ng2-dragula), especially the ['classic blunders' section](https://github.com/valor-software/ng2-dragula#classic-blunders)
- [x] I have looked at the [demos](https://valor-software.com/ng2-dragula/) to see if my use case has obvious examples.
- [x] I have searched the [`ng2-dragula` issues](https://github.com/valor-software/ng2-dragula/issues), including closed issues.
- [x] I have browsed [the issues labeled "future reference"](https://github.com/valor-software/ng2-dragula/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22future+reference%22) for problems that have been solved before.

**Use case description (required)**
Hi,

I am working on Angular 6 application and planning to use ng2-dragula. In my application I need to save the state/order of the dragged elements. I have gone through the documentation but didn't find the details. I might have overlooked, not sure.
Can you please confirm that is it possible to save the position/order of dragged items? If yes, how?

Appreciate the early response. Thanks in advance.

**Can you show a demo, or a picture of what you want to achieve?**

If so, please link it here.

**Additional context**

Add any other context here.

**Comment by cormacrelf** [comment]
I'm going to refer you to the README there.
