### ISSUE TITLE
div中使用了拖拽，子div也使用了拖拽 字类的就被父类覆盖了

### ISSUE THREAD

**Issue by liupeng328** [valor-software/ng2-dragula#895]
![default](https://user-images.githubusercontent.com/19989280/44710815-9213cc00-aadf-11e8-9083-7a713622275e.png)

**Comment by liupeng328** [comment]
`
<div dragula="MODULES">
this is work
    <div dragula="SUB">
          not work
   </div>
</div>

`

**Comment by liupeng328** [comment]
div is  not show

**Comment by liupeng328** [comment]
如图

**Comment by liupeng328** [comment]
@cormacrelf  how to use ??
Prevent bubbles

**Comment by cormacrelf** [comment]
Please read the example code. There is one using “handles” that does exactly this.

**Comment by cormacrelf** [comment]
https://github.com/valor-software/ng2-dragula/blob/master/modules/demo/src/app/examples/10-nested.component.ts

**Comment by liupeng328** [comment]
Problem solving


Thanks very much

**Man, you are great.**
`moves: (el, source, handle) => handle.className.indexOf("modules-handel") != -1`
