### ISSUE TITLE
[bug report]: CSS breaks down when I drag the elements

### ISSUE THREAD

**Issue by monis01** [valor-software/ng2-dragula#898]
**REQUIRED: Before filing a bug report**

Change each `[ ]` to `[x]` when you have done it.

- [x] My issue title starts with `[bug report]`
- [ ] I have read the [README](https://github.com/valor-software/ng2-dragula), especially the ['classic blunders' section](https://github.com/valor-software/ng2-dragula#classic-blunders), and the [dragula docs](https://github.com/bevacqua/dragula).
- [x] I have searched through the [`ng2-dragula` issues](https://github.com/valor-software/ng2-dragula/issues) for related problems, including closed issues.
- [ ] I have browsed through the [issues labeled "future reference"](https://github.com/valor-software/ng2-dragula/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22future+reference%22) for problems that have been solved before or have a known workaround.
- [x] I am using the latest version of `ng2-dragula`.

Hi
I am using ng2-dragula version:`2.0.2` with angular `5.2.11`. One of section in my application looks something like this 

![screenshot from 2018-09-08 16-03-10](https://user-images.githubusercontent.com/7036532/45253450-c65f7600-b384-11e8-8b3c-1d4685e135ef.png)

where I can drag component `Untitled Component` to different sections. I am facing problem with css, it is breaking down when I starts dragging.
(image_1)
![screenshot from 2018-09-08 16-03-23](https://user-images.githubusercontent.com/7036532/45253568-0f182e80-b387-11e8-8cd2-faa9f53fd0a3.png)
(image_2)
![screenshot from 2018-09-08 16-03-23 copy 111](https://user-images.githubusercontent.com/7036532/45253581-4b4b8f00-b387-11e8-8e0c-9eb884d6ce4a.png)

Same also the case with the elements `elem_0` when I am dragging to some other column.
![screenshot from 2018-09-08 16-52-19](https://user-images.githubusercontent.com/7036532/45253624-f8260c00-b387-11e8-8115-ff3e34b84f33.png)

Do I need to add extra class when I start dragging the element??

PS: These two dragging has separate bagNames but problem is same i.e. css breaks down

**Comment by cormacrelf** [comment]
Not a bug, it’s well-defined Dragula behaviour. The dragged element is cloned and appended to body. Any styles that depended on being inside a parent are gone. Rewrite your CSS.
