### ISSUE TITLE
[usage question] DragulaOptions

### ISSUE THREAD

**Issue by tcarlsen** [valor-software/ng2-dragula#899]
- [x] My issue title starts with `[usage question]`
- [x] I have read the [README](https://github.com/valor-software/ng2-dragula), especially the ['classic blunders' section](https://github.com/valor-software/ng2-dragula#classic-blunders)
- [x] I have looked at the [demos](https://valor-software.com/ng2-dragula/) to see if my use case has obvious examples.
- [x] I have searched the [`ng2-dragula` issues](https://github.com/valor-software/ng2-dragula/issues), including closed issues.
- [x] I have browsed [the issues labeled "future reference"](https://github.com/valor-software/ng2-dragula/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22future+reference%22) for problems that have been solved before.

**Use case description (required)**
What to use DragulaOptions

**Additional context**

Following the README
```typescript
    dragulaService.createGroup("VAMPIRES", {
      removeOnSpill: true
    });
```

I get the following error:
```
error TS2345: Argument of type '{ removeOnSpill: boolean; }' is not assignable to parameter of type 'DragulaOptions<any>'.
  Object literal may only specify known properties, and 'removeOnSpill' does not exist in type 'DragulaOptions<any>'.
```

**Comment by cormacrelf** [comment]
You don’t have `@types/dragula’`. Get the latest version of Ng2-Dragula, and it will be installed.

**Comment by cormacrelf** [comment]
https://github.com/valor-software/ng2-dragula/blob/master/modules/ng2-dragula/src/DragulaOptions.ts

**Comment by tcarlsen** [comment]
I do have that installed. I did upgrade from 1.5 to 2.1

**Comment by cormacrelf** [comment]
Maybe a typescript upgrade is in order

**Comment by cormacrelf** [comment]
Also probably some typeRoots settings in your tsconfig

Basically, this stuff works in new Angular apps, so there’s something wrong with the way your types/dragula is being resolved or installed.

**Comment by cormacrelf** [comment]
Can you import directly from `@types/dragula`? i.e.

```ts
import { DragulaOptions } from 'dragula';
const x: DragulaOptions = {
    moves: () => true,
};
```

As I posted above, `ng2-dragula` depends directly on those type defs, and the DragulaOptions<T> exported by this library just extend the originals, so all properties from `@types/dragula` are available. Unless your typescript isn't picking up the appropriate `* => @types/*` implicit mapping through the `typeRoots` compiler option.

**Comment by CrackerakiUA** [comment]
Works for me, thanks

**Comment by mythcyrax** [comment]
OK, after a few lost hours, I managed to have it working thanks to @cormacrelf :
`

import { DragulaService } from '../../../../node_modules/ng2-dragula';
import { DragulaOptions } from 'dragula';
...
constructor(

        ...,

        private dragulaService: DragulaService) {

            let options: DragulaOptions = {
                moves: (el, source, handle) => handle.className.includes('drag-handle')
            }

            this.dragulaService.createGroup("steps-bag", options);
    }`

**Comment by thomae82** [comment]
Thank you for sharing this solution, works great

**Comment by jkyoutsey** [comment]
I just did an `npm install @types/ng2-dragula@latest` and that did the trick.
