### ISSUE TITLE
[usage question] Copy items, but accept unique items only

### ISSUE THREAD

**Issue by Hesesses** [valor-software/ng2-dragula#901]
**REQUIRED: Before filing a usage question**

Change each `[ ]` to `[x]`  when you have done it.

- [x] My issue title starts with `[usage question]`
- [x] I have read the [README](https://github.com/valor-software/ng2-dragula), especially the ['classic blunders' section](https://github.com/valor-software/ng2-dragula#classic-blunders)
- [x] I have looked at the [demos](https://valor-software.com/ng2-dragula/) to see if my use case has obvious examples.
- [x] I have searched the [`ng2-dragula` issues](https://github.com/valor-software/ng2-dragula/issues), including closed issues.
- [x] I have browsed [the issues labeled "future reference"](https://github.com/valor-software/ng2-dragula/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22future+reference%22) for problems that have been solved before.

**Use case description (required)**

I want to copy from source list to target list (there are multiple target lists). Target list should not allow multiple items of the same item. So if Target list has item with id:1, it can accept id:2, but not id:1 anymore.

Any ideas?

**Comment by cormacrelf** [comment]
Dupe #867
