### ISSUE TITLE
Is there any way to drag something and drop something else ?

### ISSUE THREAD

**Issue by majidazn** [valor-software/ng2-dragula#908]
Is there any way to drag something and drop something else ?
like email builders ; user drags images and whenever drop it, html drops  there

for example I have a list 

`  items = [
   {
      name: 'Name A',
      html:'<a href="#">sample a tag</a>' 
    },
  ];`

**Comment by cormacrelf** [comment]
You mean exactly like this?

https://cormacrelf.github.io/angular-skyhook/examples/index.html#/sortable/quiz
