### ISSUE TITLE
why dragula change the inline style of drop item?

### ISSUE THREAD

**Issue by majidazn** [valor-software/ng2-dragula#910]
- [x] My issue title starts with `[usage question]`
- [x] I have read the [README](https://github.com/valor-software/ng2-dragula), especially the ['classic blunders' section](https://github.com/valor-software/ng2-dragula#classic-blunders)
- [x] I have looked at the [demos](https://valor-software.com/ng2-dragula/) to see if my use case has obvious examples.
- [x] I have searched the [`ng2-dragula` issues](https://github.com/valor-software/ng2-dragula/issues), including closed issues.
- [x] I have browsed [the issues labeled "future reference"](https://github.com/valor-software/ng2-dragula/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22future+reference%22) for problems that have been solved before.

when I drop a html tag, its inline css style change and some of them remove from the tag. why Dragula doing this? and how can change this behavior ?

< div style="background:url('background.jpg') no-repeat #333 "> </ div>

changed to blow code after drop it

< div bgcolor=# 333> </ div>

**Comment by cormacrelf** [comment]
If it's doing that, it's not because of this library. `dragula` runs `cloneElement`. Not something we can fix here.

**Comment by majidazn** [comment]
Thank you for the response. it happens because of HTML security reasons,Not `dragula`
