### ISSUE TITLE
Property 'on' in type 'MockDrake' is not assignable to the same property in base type 'DrakeWithModels'

### ISSUE THREAD

**Issue by rkgoswami** [valor-software/ng2-dragula#913]
This issue was not there when I started using this library but later on, found this issue (shown in attachment below):
![dragula-bug](https://user-images.githubusercontent.com/17023647/47650621-ccb0e800-dba6-11e8-8317-e9447846587f.PNG)

Issue is very simple:
- `Drag` interface has a method `on(events: string, callback: Function): Drake;` => file `index.d.ts`
- Interface `DrakeWithModels` extends `Drake`
- Class `MockDrake` implements `DrakeWithModels`, where method `on(events: string, callback: Function): void;` is overriden but the return type is changed, which is not allowed.

Fix is simple change the return type for method `on` in Interface `Drag` to void;

**Comment by Razor164** [comment]
same problem angular 7.0.0

**Comment by Razor164** [comment]
![screenshot_3](https://user-images.githubusercontent.com/26738019/47652142-3674c600-db96-11e8-91ea-e2a66ce2bbaf.png)

**Comment by adlerzz** [comment]
I've solved this problem by adding 
`"@types/dragula": "2.1.33",`
to my **package.json**

**Comment by peteichuk** [comment]
I've solved this problem by
[@angular/cdk/drag-drop](https://www.c-sharpcorner.com/article/drag-and-drop-using-angular-7/)

**Comment by tomasznastaly** [comment]
same problem today, Angular 6.1.0

**Comment by petterlabraaten** [comment]
ng2-dragula@2.1.0 expects @types/dragula@^2.1.33, so I solved it by globally uninstalling @types/dragula (which was version 2.1.34) and installing 2.1.33 instead.

**Comment by wizquest-labs** [comment]
@adlerzz 's solution definitely helped

**Comment by mba3gar** [comment]
@petterlabraaten can you tell me how to do it ? because i can't find the @types/dragula in my package.json

**Comment by Razor164** [comment]
npm i @types/dragula

**Comment by mba3gar** [comment]
@Razor164 even after installing the types dragula, reconfigure the package.json to 2.1.33 do the npm install again i am facing the same problem how did you solve it ?

**Comment by skydever** [comment]
I did `npm install @types/dragula@2.1.33 --save-dev` and it solved the issue on my side

@mba3gar are you sure you installed 2.1.33? you can run `npm install @types/dragula@2.1.33 --save-dev` again to be sure (and I would set it as dev dependency) ...

**Comment by mba3gar** [comment]
am using the following dragula for ionic mobile application, it works fine and smoothly on web with ionic serve but once i push it to mobile i face the same issue with MockService thing.
i wonder how i can solve this weird issue

**Comment by rkgoswami** [comment]
> @petterlabraaten can you tell me how to do it ? because i can't find the @types/dragula in my package.json

Go to your package.json of your project and add `"@types/dragula": "2.1.33"` into your `"dependencies": { } `. And the do, `npm i`

**Comment by mba3gar** [comment]
Thank you guys my problem is fixed @skydever  @rkgoswami @Razor164 well appreciated

**Comment by dilotec-2015** [comment]
the same problem :(

**Comment by hermosillaeveris** [comment]
The problem is interface declaration in index.d.ts:

    interface Drake {
        containers: Element[];
        dragging: boolean;
        start(item:Element): void;
        end(): void;
        cancel(revert:boolean): void;
        cancel(): void;
        remove(): void;
        **on(events: string, callback: Function): Drake;**
        destroy(): void;
    }

MockDrake.d.ts constructor no is valid:

    constructor(containers?: Element[], options?: DragulaOptions, models?: any[][]);
    dragging: boolean;
    start(item: Element): void;
    end(): void;
    cancel(revert: boolean): void;
    cancel(): void;
    remove(): void;
    private emitter$;
    private subs;
    **on(event: string, callback: Function): void;**
    destroy(): void;

It needs to be changed by:

    constructor(containers?: Element[], options?: DragulaOptions, models?: any[][]);
    dragging: boolean;
    start(item: Element): void;
    end(): void;
    cancel(revert: boolean): void;
    cancel(): void;
    remove(): void;
    private emitter$;
    private subs;
    **on(event: string, callback: Function): Drake;**
    destroy(): void;

**Comment by rkgoswami** [comment]
> **on(events: string, callback: Function): Drake;**

But please verify if the method `on(event: string, callback: Function)` really return anything or the mistake is in the interface definition.
```
interface Drake {
    ...

    on(event: string, callback: Function): Drake; //Drake => void , if it does not return anything
}
```

**Comment by hermosillaeveris** [comment]
It like interface mistake:

on method return void:

     */
    on(event, callback) {
        this.subs.add(this.emitter$
            .pipe(filter(({ eventType }) => eventType === event))
            .subscribe(({ args }) => {
            callback(...args);
        }));
    }
It is the interface that should be changed, sorry

interface Drake {
    containers: Element[];
    dragging: boolean;
    start(item:Element): void;
    end(): void;
    cancel(revert:boolean): void;
    cancel(): void;
    remove(): void;
    **on(events: string, callback: Function): void;**
    destroy(): void;
}

**Comment by rkgoswami** [comment]
> It like interface mistake:
> 
> on method return void:
> 
> ```
>  */
> on(event, callback) {
>     this.subs.add(this.emitter$
>         .pipe(filter(({ eventType }) => eventType === event))
>         .subscribe(({ args }) => {
>         callback(...args);
>     }));
> }
> ```
> It is the interface that should be changed, sorry
> 
> interface Drake {
> containers: Element[];
> dragging: boolean;
> start(item:Element): void;
> end(): void;
> cancel(revert:boolean): void;
> cancel(): void;
> remove(): void;
> **on(events: string, callback: Function): void;**
> destroy(): void;
> }

Then we should raise a issue on `dragula` library (dependent library of `ng2-dragula`) => https://github.com/bevacqua/dragula

**Comment by koraysels** [comment]
I didn't have this problem in 7.0.0. But now I do. I havent changed a thing. super weird. 
The only thing that worked was ```npm install``` with yarn it didn't do the trick. i can't wrap my head arround it, but there it is..

**Comment by carl-parrish** [comment]
running into the same problem but so far setting to @types/dragula@2.1.33 isn't working (with ng2-dragula@2.0.4)

**Comment by VladimirValov** [comment]
100% solution
ng2-dragula@2.0.0
@types/dragula@2.1.33

Since ng2-dragula has dependencies  "@types/dragula": "^2.1.33".
In this case we will have version 2.1.34

**Comment by cormacrelf** [comment]
Please see https://github.com/valor-software/ng2-dragula/issues/912#issuecomment-435002312

**Comment by pranavjeet123** [comment]
just remove ng-dragula from package.json file . Now run this cli command which will bring latest ng-dragula "^2.1.1".
npm i ng2-dragula.

It solves the problem .

**Comment by Akhi1** [comment]
> 
> 
> I've solved this problem by adding
> `"@types/dragula": "2.1.33",`
> to my **package.json**

Worked for me. Thank you @adlerzz
