### ISSUE TITLE
Click event fired on drop in firefox

### ISSUE THREAD

**Issue by amineparis** [valor-software/ng2-dragula#927]

**Comment by cormacrelf** [comment]
Doesn't happen on https://valor-software.com/ng2-dragula/. It's on your end, I think.

**Comment by TheParad0X** [comment]
It does happen, but it seems to be a Bug from Dragula: https://github.com/bevacqua/dragula/issues/564

**Comment by s-gbz** [comment]
Hey @TheParad0X are there any updates on your side?
Facing the same issue here :(
