### ISSUE TITLE
[feature request] The find() method should return null instead of undefined

### ISSUE THREAD

**Issue by exedor** [valor-software/ng2-dragula#928]
- [X] My issue title starts with `[feature request]`
- [X] I have thoroughly read through the README, and the [dragula docs](https://github.com/bevacqua/dragula).
- [X] I have searched through the **[`ng2-dragula` issues](https://github.com/valor-software/ng2-dragula/issues)** for related problems, including closed issues, and I didn't find anything.

**Is your feature request related to a problem? Please describe.**
Not really

The find() method returns "undefined" which I believe is in appropriate. I think maybe you might be looking at it from the perspective of the group. If you execute find() using the name of a group that has not yet been created with createGroup, then technically, but definition, it is undefined. However, I don't think that's how most devs think about a value that is undefined. According to the convention within the language for the use of undefined vs null, I think most devs would see the value coming back from find and start wondering if the find method itself is undefined. null isn't a valid group anyway and when you are dealing with data that can't legitimately have a null value and one which is returned via method like find, null is more appropriate.

**Describe the solution you'd like**
have the find() method return null instead of undefined for groups that do not exist. It would also be helpful if the return value of the find() method when no groups exist is documented in the Readme.

**Comment by cormacrelf** [comment]
Nope. Array.prototype.find returns undefined if it couldn’t find anything. Also, I think this may be the most trivial issue ever, so congrats, I wish I had a party hat to give you.
