### ISSUE TITLE
[Feature request] support multi drag items

### ISSUE THREAD

**Issue by TKul6** [valor-software/ng2-dragula#936]
**REQUIRED: Before filing a feature request**

Change each `[ ]` to `[x]` when you have done it.

- [X ] My issue title starts with `[feature request]`
- [ X] I have thoroughly read through the README, and the [dragula docs](https://github.com/bevacqua/dragula).
- [ X] I have searched through the **[`ng2-dragula` issues](https://github.com/valor-software/ng2-dragula/issues)** for related problems, including closed issues, and I didn't find anything.

**Is your feature request related to a problem? Please describe.**
I need to drag several items from one container (a table) to another container (tree component).
I'm not sure if Dragula support dragging multiple items to a container.

**Describe the solution you'd like**
It will be helpful if the dragula component would know how to drag multiple items.
As I see it, it doesn't actually need to know when the user drag multiple elements (although it will be useful), but need to support this behavior by doing the following things:
- Support marking element as "being dragged" (change the opacity).
- Support changing the drag image (something like angular material's [drag preview](https://material.angular.io/cdk/drag-drop/overview#customizing-the-drag-preview) can be useful).
- Support having multiple elements when subscribing to `dragularService.dropModel` observable.
(I'm not really need this, but I think it is required for the feature itself).

Mentioned above.

**Describe alternatives you've considered**
I consider disabling the d&d in my system, but I really don't wanna do that.

Thanks

**Comment by niralmunjariya** [comment]
I also need a similar feature to drag and drop multiple items from one Dragula container to another.

**Comment by TKul6** [comment]
Any news guys?

**Comment by cormacrelf** [comment]
This has come up many times before, and the answer is always no, this is a tiny wrapper around Dragula that will not add complex opinionated features like that. If dragula ever gets maintained again, you would request it there, but considering that is super unlikely, just do it yourself.

Dupe #283

https://github.com/valor-software/ng2-dragula/issues/283#issuecomment-395916582
