### ISSUE TITLE
Dragula disable drag to reorder

### ISSUE THREAD

**Issue by markand911** [valor-software/ng2-dragula#939]
I am using this awesome library for drag and drop functionality. Dragula is very good at drag and drop.
One thing I am trying to do is to disable dragging to reorder in own container. But should allow dragging if going to drop in a connected/linked container.
for example following two div tags as containers

```
<div dragula="dropContainer" id="dropbag1" [(dragulaModel)]="bagOneModel">
   <div *ngFor="let model of bagOneModel" class="col-sm-2 col-md-2 col-lg-2">
     {{model}}
   </div>
</div>


<div dragula="dropContainer" id="dropbag2" [(dragulaModel)]="bag2Model">
   <div *ngFor="let model of bag2Model" class="col-sm-2 col-md-2 col-lg-2">
     {{model}}
    <!-- don't allow re ordering in this container -->
   </div>
</div>
```

**Comment by dmkorol** [comment]
Hi, @markand911 
I had a similar problem today. I need to disable some items and forbid insert any items between.
I didn't found any interceptors or option that runs before item lent.
But there is a dirty solution with change items after drag'n'drop
` this.dragulaService.dropModel("VAMPIRES").subscribe( (arg) => {
      const {targetModel, item, target} = arg;
 
      /** Check when blue column and blue item was picked */
      if(target['dataset']['group'] === 'blue' && item.group === 'blue') {
        const initPos = this.vamps.indexOf(item);
        const currPos = targetModel.indexOf(item);
        /** Hack that need to change items only after item is lended */
        setTimeout(_ =>{
          targetModel.splice(currPos, 1);
          targetModel.splice(initPos, 0, item);
          /**TODO: good user expiriance to add some toast/notification for user that change order is forbidden */
        }, 0);
      
      } else if(item.group === 'blue'){
        /** Change color of item because otherwise we have to handle special order when this item will be drop back to the inital column */
        item.group = 'none';
      }
    });
  }`
https://stackblitz.com/edit/ng2-dragula-base-iarvru

**Comment by cormacrelf** [comment]
Please use the `accepts` property on the `createGroup` method. It's in the upstream Dragula documentation.
