### ISSUE TITLE
Hook to confirm/cancel a removeModel?

### ISSUE THREAD

**Issue by markand911** [valor-software/ng2-dragula#943]
Hi,

I have set removeOnSpill: true for my dragula group. In most cases i want to remove item if dropped outside container. But in just one case i want to revert the item if dropped outside container.

I was wondering that is there any dragula event which will fire before remove. So that i can perform some validation before removing item. I found this #552 issue. Great example of how to hook to drop event. I am not sure that i can apply the same method to hook to removeModel event. Or is there any other better way to handle this scenario.

Thanks a lot.

**Comment by cormacrelf** [comment]
Does nobody read docs or search old issues any more? There’s an issue template reminding you to do that. There is a Drake API for this, but as other issues have noted, it is synchronous so you must know at the time, not check an API call etc.

**Comment by cormacrelf** [comment]
Sorry, wrong issue on that last comment. Basically: no. You can only cancel drops, unless you implement all the model handling yourself. But if you’re going to handle it all, you may as well use `@angular-skyhook/sortable`, I would recommend doing the array manipulation with Immer.

**Comment by cormacrelf** [comment]
Also see #940 which was basically he same issue 3 weeks ago
