### ISSUE TITLE
The dragulaModelChange is not emitting correct order of an array

### ISSUE THREAD

**Issue by torabshaikh** [valor-software/ng2-dragula#945]
**REQUIRED: Before filing a bug report**

Change each `[ ]` to `[x]` when you have done it.

- [x ] My issue title starts with `[bug report]`
- [x ] I have read the [README](https://github.com/valor-software/ng2-dragula), especially the ['classic blunders' section](https://github.com/valor-software/ng2-dragula#classic-blunders), and the [dragula docs](https://github.com/bevacqua/dragula).
- [x] I have searched through the [`ng2-dragula` issues](https://github.com/valor-software/ng2-dragula/issues) for related problems, including closed issues.
- [x] I have browsed through the [issues labeled "future reference"](https://github.com/valor-software/ng2-dragula/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22future+reference%22) for problems that have been solved before or have a known workaround.
- [x] I am using the latest version of `ng2-dragula`.

**Describe the bug (required)**
The dragulaModelChange is not emitting correct order of an array.  Drop Modal API of DragulaServie is also giving the same repsonse.

**To Reproduce (required)**

1. Create a minimal angular app that uses ng2-Dragula and which pring the value emitted from the dragulaModelChange  event.
2. Reorder List using drag and drop.
3. Reorder again and Observe that it is not reordering the emitted value.
I am attaching a demo myself. Please follow steps and observe the bug in the console.
[stackblitz]: https://stackblitz.com/edit/dragulabug?file=src%2Fapp%2Fapp.component.html

**Screenshots (optional)**
![screenshot 53](https://user-images.githubusercontent.com/18557453/53477932-c02c9580-3a9b-11e9-819f-05400226fe89.png)

**Versions (required)**

Please state which versions of the following packages you have installed:

-@angular/common: 7.2.7
-@angular/compiler: 7.2.7
-@angular/core: 7.2.7
-@angular/forms: 7.2.7
-@angular/platform-browser: 7.2.7
-@angular/platform-browser-dynamic: 7.2.7
-@angular/router: 7.2.7
-core-js: 2.6.5
-ng2-dragula: 2.1.1
-rxjs: 6.4.0
-zone.js: 0.8.29

**Browsers affected (optional)**
 Google Chrome( Version 72.0.3626.119 (Official Build) (64-bit))

**Additional context (optional)**

**Comment by cormacrelf** [comment]
You’re never saving the changes of drags. The first drag makes a correct dropModel event, but after that, the pageList variable hasn’t changed whereas the UI is still modified. 

Add round braces to dragulaModel: `[(dragulaModel)]=`
