### ISSUE TITLE
[usage question] Update object values with drop ng2-dragula

### ISSUE THREAD

**Issue by tvbishan** [valor-software/ng2-dragula#959]
**REQUIRED: Before filing a usage question**

- [x] My issue title starts with `[usage question]`
- [x] I have read the [README](https://github.com/valor-software/ng2-dragula), especially the ['classic blunders' section](https://github.com/valor-software/ng2-dragula#classic-blunders)
- [x] I have looked at the [demos](https://valor-software.com/ng2-dragula/) to see if my use case has obvious examples.
- [x] I have searched the [`ng2-dragula` issues](https://github.com/valor-software/ng2-dragula/issues), including closed issues.
- [x] I have browsed [the issues labeled "future reference"](https://github.com/valor-software/ng2-dragula/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22future+reference%22) for problems that have been solved before.

**Use case description (required)**

I am using ng2-dragula 2.1.1 in my Angular 6 project. I have 2 lanes like below.

![image](https://user-images.githubusercontent.com/12027448/57693027-d9d68580-7665-11e9-8795-347a26c2ed24.png)

Data structure is like below.

    {
     "groupA":[{"itemName":"Item A","itemGroup":"A"},{"itemName":"Item B","itemGroup":"A"},{"itemName":"Item C","itemGroup":"A"},{"itemName":"Item D","itemGroup":"A"}],
     "groupB":[{"itemName":"Item 1","itemGroup":"B"},{"itemName":"Item 2","itemGroup":"B"},{"itemName":"Item 3","itemGroup":"B"},{"itemName":"Item 4","itemGroup":"B"}]
    }

Assume I am dragging `Item A` from **Group A** to **Group B**. After drop `Item A` in **Group B**, I need to update the `Item A`'s `itemGroup` from **A** to **B**.

Also same scenario applies when dragging an item from **Group B** to **Group A**. Need to update the `itemGroup` from **B** to **A**.

**component.html**

    

    <div class="wrapper" dragula="COLUMNS" [(dragulaModel)]="groups.groupA">
        <div class="container" *ngFor="let group of groups.groupA">
          <span class="group-handle">{{group.itemName}}</span>
        </div>
    </div>
    <div class="wrapper" dragula="COLUMNS" [(dragulaModel)]="groups.groupB">
        <div class="container" *ngFor="let group of groups.groupB">
          <span class="group-handle">{{group.itemName}}</span>
        </div>
    </div>

    

**component.ts**

    constructor(private dragulaService: DragulaService) {
    
		dragulaService.createGroup('COLUMNS', {
			  revertOnSpill: true
			});	
		this.subs.add(dragulaService.dropModel('COLUMNS')
			  .subscribe(({ name, el, target, source, sibling, sourceModel, targetModel, item }) => {

			  })
			);

    }

How can I achieve this?

**Comment by cormacrelf** [comment]
You want me to write the line of code in the middle of component.ts for you? Did you try doing exactly what you described and changing itemGroup?

**Comment by tvbishan** [comment]
`item.itemGroup = (item.itemGroup === 'A') ? 'B' : 'A';`

This will work for above scenario. But when there are more than 2 lanes (assume 5 or 6 lanes), can't go with above solution.

**Comment by cormacrelf** [comment]
I mean, this is pretty basic programming. You have so many other variables to inspect. File an issue on an open source repository if you have put in a lot of effort to no avail, and wonder if the library might be inherently limited, but not just so you can get other people to do your work for you.

**Comment by cormacrelf** [comment]
Ok that was snarky, but here’s a clue: your divs (source and target) currently store no information about what group they contain.

**Comment by tvbishan** [comment]
Ok. Here is what I am doing currently. 

- Assign an id to div.

```
<div class="wrapper" dragula="COLUMNS" [(dragulaModel)]="groups.groupA" id="A">
    <div class="container" *ngFor="let group of groups.groupA">
      <span class="group-handle">{{group.itemName}}</span>
    </div>
</div>
<div class="wrapper" dragula="COLUMNS" [(dragulaModel)]="groups.groupB" id="B">
    <div class="container" *ngFor="let group of groups.groupB">
      <span class="group-handle">{{group.itemName}}</span>
    </div>
</div>
```
- Access the id from target
```
this.subs.add(dragulaService.dropModel('COLUMNS')
   .subscribe(({ name, el, target, source, sibling, sourceModel, targetModel, item }) => {
      
      item.itemGroup = target.id;

   })
);
```
I was looking for any built-in function to achieve this.

**Comment by cormacrelf** [comment]
Well, there isn’t and won’t be. But well done.
