### ISSUE TITLE
Scroll not working 

### ISSUE THREAD

**Issue by azaddeveloper** [valor-software/ng2-dragula#972]
I have a list of text elements and want to automatically scroll my list to the bottom when I'm dragging my new element. Is there is any way to solve this issue? while digging this issue some peoples have suggested  [**dom-autoscroller**](https://github.com/cormacrelf/dragula-touch-demo).
But it's also not working.  Please help me to solve this issue.

**Comment by cormacrelf** [comment]
https://github.com/cormacrelf/dragula-touch-demo

**Comment by azaddeveloper** [comment]
There is  an issue with the library. It also not working.
this.ds.add('bag', drake);         // no such function

**Comment by cormacrelf** [comment]
There’s a big huge message up the top of the readme saying it needs an upgrade to ng2-dragula v2. I haven’t touched it in a long time.
